// Auto-generated by scripts/sync-catalog.js — do not edit by hand.
// Synced from https://playbound.club at 2026-09-23T16:29:33.058Z
//
// These mirror TAGS and FEATURES in platform/src/lib/gamePayload.ts. Change
// them there; the next catalog sync brings them across.

export const TAGS = [
  "2D",
  "Pixel Art",
  "Classic",
  "Competitive",
  "LAN",
  "Mods",
  "Open World",
  "Sandbox",
  "Sci-Fi",
  "Fantasy",
  "Evil",
  "Space Trading",
  "Turn-Based",
  "Arena Shooter",
  "Kart Racing",
  "Browser",
  "Indie",
  "Retro",
  "Base Building",
  "Esports",
  "Open Source",
  "Cross-Platform",
  "Fangame",
  "Free To Play",
  "Historical",
  "Neo Geo",
  "Party",
  "PvP",
  "Soccer",
  "Tactical"
];

export const FEATURES = [
  "Multiplayer",
  "Singleplayer",
  "Co-op",
  "Couch Co-Op",
  "Split-Screen Co-op",
  "Hotseat",
  "LAN Support",
  "Dedicated Servers",
  "Cross-play",
  "Controller Support",
  "Flightstick Support",
  "PlayBound Controller Support",
  "Family Friendly",
  "Mod Support",
  "Map Editor",
  "Level Editor",
  "Custom Maps",
  "Community Content",
  "Replays",
  "Ranked Ladder",
  "Spectator Mode",
  "Story Campaign",
  "Team Play"
];
