import crypto from "crypto";
import dbConnect from "@/lib/db";
import BugReport from "@/lib/models/BugReport";
import type { BugReportSource } from "@/lib/bugReports";

export type AutoBugInput = {
  event: "launch_failed" | "install_failed" | "error";
  source: BugReportSource;
  code?: string | null;
  message?: string | null;
  gameSlug?: string | null;
  editionSlug?: string | null;
  gameTitle?: string | null;
  launcherVersion?: string | null;
  platform?: string | null;
  userAgent?: string | null;
  userId?: string | null;
  phase?: string | null;
};

function hashMessage(message: string): string {
  return crypto.createHash("sha256").update(message.slice(0, 400)).digest("hex").slice(0, 16);
}

/** Stable key so identical open failures bump one bug instead of flooding Admin. */
export function autoBugFingerprint(input: AutoBugInput): string {
  const parts = [
    input.event,
    input.source,
    input.code || "UNKNOWN",
    input.gameSlug || "",
    input.editionSlug || "",
    hashMessage(String(input.message || "")),
  ];
  return parts.join("|").slice(0, 240);
}

/**
 * Create or bump an auto-generated Admin bug from telemetry.
 * Best-effort: never throws to the telemetry ingest path.
 */
export async function upsertAutoBugReport(input: AutoBugInput): Promise<void> {
  try {
    const message = String(input.message || "").trim() || "No message";
    const code = String(input.code || "UNKNOWN").slice(0, 80);
    const fingerprint = autoBugFingerprint(input);
    const now = new Date();

    await dbConnect();

    const existing = await BugReport.findOne({
      fingerprint,
      autoGenerated: true,
      status: { $in: ["open", "reviewing"] },
    });

    if (existing) {
      existing.occurrenceCount = (existing.occurrenceCount || 1) + 1;
      existing.lastSeenAt = now;
      if (input.launcherVersion) existing.launcherVersion = input.launcherVersion.slice(0, 40);
      if (input.platform) existing.platform = input.platform.slice(0, 40);
      await existing.save();
      return;
    }

    const slugLabel = input.gameSlug || "unknown";
    const title = `[${input.event}] ${slugLabel} · ${code}`.slice(0, 160);
    const description = [
      `Auto-reported from telemetry \`${input.event}\`.`,
      `Code: ${code}`,
      input.phase ? `Phase: ${input.phase}` : null,
      input.gameSlug ? `Game: ${input.gameTitle || input.gameSlug}` : null,
      input.editionSlug ? `Edition: ${input.editionSlug}` : null,
      "",
      message.slice(0, 4000),
    ]
      .filter((line) => line !== null)
      .join("\n")
      .slice(0, 8000);

    await BugReport.create({
      title,
      description,
      source: input.source === "website" ? "website" : "launcher",
      autoGenerated: true,
      fingerprint,
      errorCode: code,
      gameSlug: input.gameSlug || null,
      editionSlug: input.editionSlug || null,
      occurrenceCount: 1,
      lastSeenAt: now,
      launcherVersion: input.launcherVersion || null,
      platform: input.platform || null,
      userAgent: input.userAgent || null,
      submittedBy: input.userId || null,
      submitterName: "Auto",
      status: "open",
    });
  } catch (err) {
    console.error("upsertAutoBugReport failed:", err);
  }
}

/** Map a saved telemetry event into an auto bug when applicable. */
export async function maybeUpsertAutoBugFromTelemetry(opts: {
  event: string;
  properties?: Record<string, unknown>;
  userId?: string | null;
  userAgent?: string | null;
}): Promise<void> {
  const event = opts.event;
  if (event !== "launch_failed" && event !== "install_failed" && event !== "error") return;

  const props = opts.properties || {};
  const sourceProp = typeof props.source === "string" ? props.source : "";
  const source: BugReportSource = sourceProp === "website" ? "website" : "launcher";

  await upsertAutoBugReport({
    event,
    source,
    code: typeof props.code === "string" ? props.code : null,
    message: typeof props.message === "string" ? props.message : null,
    gameSlug: typeof props.gameSlug === "string" ? props.gameSlug : null,
    editionSlug: typeof props.editionSlug === "string" ? props.editionSlug : null,
    gameTitle: typeof props.gameTitle === "string" ? props.gameTitle : null,
    launcherVersion: typeof props.launcherVersion === "string" ? props.launcherVersion : null,
    platform: typeof props.platform === "string" ? props.platform : null,
    phase: typeof props.phase === "string" ? props.phase : null,
    userAgent: opts.userAgent || null,
    userId: opts.userId || null,
  });
}
