import type { Metadata } from "next";
import type { Game } from "@/lib/data/types";
import type { Edition } from "@/lib/editionTypes";
import { EDITION_TYPE_LABELS } from "@/lib/editionTypes";
import { SITE_NAME } from "@/lib/site";

/** Generated by app/opengraph-image.tsx; used when a page supplies no image. */
const DEFAULT_OG_IMAGE = "/opengraph-image";

/** Meta descriptions get truncated around 160 chars; keep a little headroom. */
export function clampDescription(text: string, max = 158): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(" ");
  return `${cut.slice(0, lastSpace > 80 ? lastSpace : cut.length)}…`;
}

/**
 * Assemble a description from strongest fact to weakest, stopping once it is
 * long enough to be useful.
 *
 * clampDescription only ever enforced a ceiling, so a page whose lead sentence
 * was a short tagline shipped a ~100-character description — long enough to be
 * valid, short enough that search engines rewrite it from page copy instead.
 * Callers pass the specifics they have and the tail sentences fill the gap;
 * anything already past `min` stops early rather than padding for its own sake.
 */
export function buildDescription(
  parts: (string | false | null | undefined)[],
  min = 120,
  max = 158
): string {
  const usable = parts.map((p) => (p ? String(p).trim() : "")).filter(Boolean);
  let out = "";
  for (const part of usable) {
    const next = out ? `${out} ${part}` : part;
    // Once past `min`, refuse a part that would overflow — appending it only to
    // clamp it back would leave the description ending mid-clause ("no account,…").
    if (next.length > max && out.length >= min) break;
    out = next;
    if (out.length >= min) break;
  }
  return clampDescription(out, max);
}

export function sizeLabel(sizeMB: number): string {
  if (!sizeMB) return "small";
  return sizeMB >= 1000 ? `${(sizeMB / 1000).toFixed(1)} GB` : `${sizeMB} MB`;
}

/**
 * Builds page metadata with a canonical URL.
 *
 * The canonical is the single most important field here: it collapses all nine
 * `?tab=` variants of a game page into one indexable URL, and it stops the
 * preview domain from being treated as authoritative.
 */
export function pageMetadata(opts: {
  title: string;
  description: string;
  path: string;
  images?: string[];
  type?: "website" | "article";
  publishedTime?: string;
  noIndex?: boolean;
}): Metadata {
  const description = clampDescription(opts.description);
  /*
   * Falling back to the generated site card rather than omitting images.
   *
   * app/opengraph-image.tsx would normally supply og:image for free, but that
   * file convention only fills in where metadata does not define openGraph
   * itself. Because this helper always returns an openGraph object, every page
   * that did not pass its own images — /alternatives and /compare among them —
   * shipped with no og:image at all and no card when shared.
   */
  const images = opts.images?.length ? opts.images : [DEFAULT_OG_IMAGE];
  return {
    title: opts.title,
    description,
    alternates: { canonical: opts.path },
    /*
     * follow stays true on purpose. This flag is for pages too thin to deserve
     * their own search result, not for pages we want crawlers to avoid — they
     * still link to games we very much want crawled, and nofollow would strip
     * those internal paths for no benefit.
     */
    ...(opts.noIndex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      type: opts.type ?? "website",
      url: opts.path,
      siteName: SITE_NAME,
      title: opts.title,
      description,
      images,
      ...(opts.publishedTime ? { publishedTime: opts.publishedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: opts.title,
      description,
      images,
    },
  };
}

/** Metadata for routes that must never be indexed (auth, admin, personal). */
export function privateMetadata(title: string): Metadata {
  return {
    title,
    robots: { index: false, follow: false },
  };
}

/**
 * Game page description, assembled from catalog facts and pricing awareness.
 *
 * Front-loads verifiable specifics — pricing tier, license, platforms, and size —
 * ensuring paid titles never falsely claim to be free.
 */
export function gameDescription(game: Game): string {
  const genre = game.genres.slice(0, 2).join("/");
  const priceType = game.access?.priceType;
  const platforms = game.platforms.length ? game.platforms.join(", ") : "PC";
  const size = sizeLabel(game.sizeMB);

  let lead: string;
  let accessNote: string;

  if (priceType === "PAID") {
    lead = `${game.title} is a ${genre} game for ${platforms}.`;
    accessNote = game.sizeMB ? `Download size: ${size}. ${game.license}.` : `${game.license}.`;
  } else if (priceType === "PAID_BASE_GAME_REQUIRED") {
    lead = `${game.title} is an open engine & client for ${platforms}.`;
    accessNote = `Requires original base game assets. ${size}, ${game.license}.`;
  } else {
    const freeClaim = game.qualityBar?.genuinelyFree
      ? "Free forever, no pay-to-win"
      : "Free to play";
    lead = `${game.title} is a free ${genre} game for ${platforms}.`;
    accessNote = `${size}, ${game.license}. ${freeClaim}.`;
  }

  return buildDescription([
    lead,
    game.tagline,
    accessNote,
    game.longDescription || game.description,
  ]);
}

/**
 * Game page title.
 *
 * The root layout appends " · PlayBound" (12 characters), so target roughly
 * 40–50 characters here. Removes "Free" prefix for commercial titles.
 */
export function gameTitle(game: Game): string {
  const label = game.genres[0] ?? "Game";
  const priceType = game.access?.priceType;

  if (priceType === "PAID") {
    return `${game.title} — ${label}`;
  }

  if (priceType === "PAID_BASE_GAME_REQUIRED") {
    return `${game.title} — ${label} Engine`;
  }

  return `${game.title} — Free ${label}`;
}

/**
 * Edition page title.
 *
 * The root layout appends " · PlayBound". Avoids redundant game name repetition
 * if the edition name already mentions it.
 */
export function editionTitle(edition: Edition, game: Game): string {
  const typeLabel = EDITION_TYPE_LABELS[edition.type] || "Edition";
  const lowerEd = edition.name.toLowerCase();
  const lowerGame = game.title.toLowerCase();

  const acronym = game.title
    .split(/[\s:-]+/)
    .map((w) => w[0]?.toLowerCase())
    .join("");

  const hasOverlap =
    lowerEd.includes(lowerGame) ||
    lowerGame.includes(lowerEd) ||
    (acronym.length >= 3 && lowerEd.includes(acronym)) ||
    Boolean(game.aliases?.some((a) => a.length >= 2 && lowerEd.includes(a.toLowerCase())));

  if (hasOverlap) {
    return `${edition.name} — ${typeLabel}`;
  }

  return `${edition.name} — ${game.title} ${typeLabel}`;
}

/**
 * Edition page meta description.
 *
 * Assembled from edition details, parent game identity, and prerequisite requirements.
 */
export function editionDescription(edition: Edition, game: Game): string {
  const typeLabel = (EDITION_TYPE_LABELS[edition.type] || "edition").toLowerCase();
  const lead = edition.shortDescription
    ? edition.shortDescription
    : `${edition.name} is a ${typeLabel} edition of ${game.title}.`;

  const requiresBase =
    game.access?.priceType === "PAID" ||
    game.access?.priceType === "PAID_BASE_GAME_REQUIRED" ||
    edition.requirements?.notes?.toLowerCase().includes("require") ||
    edition.requirements?.notes?.toLowerCase().includes("client");

  const requirementClause = requiresBase
    ? `Requires ${game.title} installation or game files.`
    : undefined;

  const featuresClause = edition.features?.length
    ? `Features ${edition.features.slice(0, 3).join(", ")}.`
    : undefined;

  const actionClause =
    edition.installMethod === "playbound_installer"
      ? "Install in one click with the PlayBound launcher."
      : undefined;

  return buildDescription([
    lead,
    requirementClause,
    featuresClause,
    edition.description,
    actionClause,
  ]);
}

