// Auto-generated by scripts/sync-catalog.js — do not edit by hand.
// Synced from https://playbound.club at 2026-08-17T07:51:17.424Z
// 64 game(s)

module.exports = [
  {
    "slug": "0ad",
    "title": "0 A.D.",
    "blurb": "Ancient warfare, stunningly rendered, forever free.",
    "kind": "direct-installer",
    "art": [
      "#713f12",
      "#eab308"
    ],
    "approxSize": "~3.0 GB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Historical",
      "Base Building",
      "Empire",
      "Skirmish"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/0ad/shot-1786819596543.webp",
    "url": "https://releases.wildfiregames.com/0ad-0.28.0-win64.exe",
    "fileName": "0ad-0.28.0-win64.exe",
    "versionLabel": "0.28.0",
    "knownExePaths": [
      "%PROGRAMFILES%\\0 A.D. alpha\\binaries\\system\\pyrogenesis.exe",
      "%PROGRAMFILES(X86)%\\0 A.D. alpha\\binaries\\system\\pyrogenesis.exe",
      "%LOCALAPPDATA%\\Programs\\0 A.D. alpha\\binaries\\system\\pyrogenesis.exe",
      "%LOCALAPPDATA%\\0 A.D. alpha\\binaries\\system\\pyrogenesis.exe"
    ],
    "installRoot": "%PROGRAMFILES%\\0 A.D. alpha",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-25T19:46:51.681Z"
  },
  {
    "slug": "asphalt-legends",
    "title": "Asphalt Legends",
    "blurb": "Arcade racing with licensed cars — free to download, live-service shop attached.",
    "kind": "external",
    "art": [
      "#7c2d12",
      "#fbbf24"
    ],
    "approxSize": "~10.0 GB",
    "genres": [
      "Racing",
      "Arcade"
    ],
    "tags": [
      "Free to Play",
      "Licensed Cars",
      "Controller",
      "Live Service"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/asphalt-legends/cover-c900fee3285f1c32.webp",
    "url": "https://store.steampowered.com/app/1815780/Asphalt_Legends/",
    "note": "Free on Steam (and Epic). Live-service client — always-online.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux",
      "Android",
      "iOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T18:29:49.930Z"
  },
  {
    "slug": "beyond-all-reason",
    "title": "Beyond All Reason",
    "blurb": "Thousand-unit RTS battles that melt GPUs and minds.",
    "kind": "github-installer",
    "art": [
      "#450a0a",
      "#f87171"
    ],
    "approxSize": "~2.2 GB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Large Scale",
      "Team Games",
      "Economy",
      "Competitive"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/beyond-all-reason/cover-989bd0c965f96f3a.webp",
    "repo": "beyond-all-reason/BYAR-Chobby",
    "assetPattern": "Beyond-All-Reason-.*\\.exe$",
    "knownExePaths": [
      "%LOCALAPPDATA%\\Programs\\Beyond-All-Reason\\Beyond-All-Reason.exe",
      "%LOCALAPPDATA%\\Programs\\Beyond-All-Reason\\Beyond All Reason.exe",
      "%LOCALAPPDATA%\\Programs\\Beyond All Reason\\Beyond-All-Reason.exe",
      "%LOCALAPPDATA%\\Programs\\Beyond All Reason\\Beyond All Reason.exe",
      "%PROGRAMFILES%\\Beyond-All-Reason\\Beyond-All-Reason.exe",
      "%PROGRAMFILES%\\Beyond All Reason\\Beyond All Reason.exe",
      "%PROGRAMFILES(X86)%\\Beyond-All-Reason\\Beyond-All-Reason.exe"
    ],
    "note": "Opens the BAR launcher — click Update, then Start.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-25T19:46:51.806Z"
  },
  {
    "slug": "endless-sky",
    "title": "Endless Sky",
    "blurb": "Trade, explore, and fight across a living galaxy.",
    "kind": "github-zip",
    "art": [
      "#1e1b4b",
      "#818cf8"
    ],
    "approxSize": "~450 MB",
    "genres": [
      "Space",
      "RPG",
      "Simulation"
    ],
    "tags": [
      "Space Trading",
      "Open World",
      "Story",
      "Exploration"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://playbound.club/games/endless-sky/cover.webp",
    "repo": "endless-sky/endless-sky",
    "assetPattern": "^EndlessSky-win64-.*\\.zip$",
    "exeHint": "EndlessSky",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.764Z"
  },
  {
    "slug": "everquest",
    "title": "EverQuest",
    "blurb": "Classic MMORPG — official progression and legendary private eras.",
    "kind": "external",
    "art": [
      "#0f172a",
      "#38bdf8"
    ],
    "approxSize": "~12.0 GB",
    "genres": [
      "RPG"
    ],
    "tags": [
      "MMORPG",
      "Classic",
      "Fantasy",
      "PvE"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/everquest/shot-1786800205997.webp",
    "url": "https://www.everquest.com",
    "note": "Prefer an edition: EverQuest Live (Daybreak LaunchPad), Project Quarm, or Project 1999.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.487Z"
  },
  {
    "slug": "flightgear",
    "title": "FlightGear",
    "blurb": "Flight simulation for the whole planet — free as in freedom.",
    "kind": "direct-installer",
    "art": [
      "#0c4a6e",
      "#7dd3fc"
    ],
    "approxSize": "~2.0 GB",
    "genres": [
      "Simulation"
    ],
    "tags": [
      "Flight",
      "Open World",
      "Multiplayer",
      "Realistic"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/flightgear/cover-16fc21781c469aeb.webp",
    "exeHint": "fgfs",
    "url": "https://download.flightgear.org/release-2024.1/flightgear-2024.1.6-windows-amd64.exe",
    "fileName": "flightgear-2024.1.6-windows-amd64.exe",
    "versionLabel": "2024.1.6",
    "knownExePaths": [
      "%PROGRAMFILES%\\FlightGear 2024.1.6\\bin\\fgfs.exe",
      "%PROGRAMFILES(X86)%\\FlightGear 2024.1.6\\bin\\fgfs.exe",
      "%PROGRAMFILES%\\FlightGear\\bin\\fgfs.exe",
      "%PROGRAMFILES(X86)%\\FlightGear\\bin\\fgfs.exe",
      "%LOCALAPPDATA%\\Programs\\FlightGear 2024.1.6\\bin\\fgfs.exe",
      "%LOCALAPPDATA%\\Programs\\FlightGear\\bin\\fgfs.exe"
    ],
    "registryTitles": [
      "FlightGear"
    ],
    "connectArgs": [
      "--multiplay=out,10,{host},{port}"
    ],
    "note": "Opens the official FlightGear Windows setup — finish the wizard, then Play.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T08:04:23.526Z"
  },
  {
    "slug": "freeciv",
    "title": "Freeciv",
    "blurb": "Build an empire turn by turn — infinitely rewritable.",
    "kind": "direct-installer",
    "art": [
      "#1e3a8a",
      "#93c5fd"
    ],
    "approxSize": "~60 MB",
    "genres": [
      "Strategy",
      "Simulation"
    ],
    "tags": [
      "Turn-Based",
      "4X",
      "Multiplayer",
      "Mods"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/freeciv/cover-1786801205721.webp",
    "exeHint": "freeciv-gtk4",
    "url": "https://files.freeciv.org/packages/windows/Freeciv-3.2.5-msys2-win64-10-gtk4-setup.exe",
    "fileName": "Freeciv-3.2.5-msys2-win64-10-gtk4-setup.exe",
    "versionLabel": "3.2.5",
    "knownExePaths": [
      "%PROGRAMFILES%\\Freeciv-3.2.5-win64-10-client-gtk4\\freeciv-gtk4.exe",
      "%PROGRAMFILES(X86)%\\Freeciv-3.2.5-win64-10-client-gtk4\\freeciv-gtk4.exe",
      "%PROGRAMFILES%\\Freeciv-3.2.5-msys2-win64-10-gtk4\\freeciv-gtk4.exe",
      "%PROGRAMFILES(X86)%\\Freeciv-3.2.5-msys2-win64-10-gtk4\\freeciv-gtk4.exe",
      "%LOCALAPPDATA%\\Programs\\Freeciv-3.2.5-win64-10-client-gtk4\\freeciv-gtk4.exe"
    ],
    "registryTitles": [
      "Freeciv"
    ],
    "connectArgs": [
      "--server",
      "{host}",
      "--port",
      "{port}"
    ],
    "note": "Opens the official Freeciv GTK4 setup — finish the wizard, then Play.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T08:04:23.492Z"
  },
  {
    "slug": "hedgewars",
    "title": "Hedgewars",
    "blurb": "Turn-based hedgehog warfare. Yes, really.",
    "kind": "direct-installer",
    "art": [
      "#3f2d0c",
      "#fde047"
    ],
    "approxSize": "~180 MB",
    "genres": [
      "Strategy",
      "Arcade"
    ],
    "tags": [
      "Artillery",
      "Party",
      "Turn-Based",
      "Couch Co-op"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/hedgewars/cover-1957b70b8d9c642e.webp",
    "url": "https://www.hedgewars.org/download/releases/Hedgewars-1.0.0.exe",
    "knownExePaths": [
      "%PROGRAMFILES%\\Hedgewars\\hedgewars.exe",
      "%PROGRAMFILES(X86)%\\Hedgewars\\hedgewars.exe",
      "%LOCALAPPDATA%\\Programs\\Hedgewars\\hedgewars.exe"
    ],
    "connectArgs": [
      "--connect",
      "{host}:{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.927Z"
  },
  {
    "slug": "luanti",
    "title": "Luanti",
    "blurb": "An infinite voxel sandbox — and an engine for a thousand games.",
    "kind": "github-zip",
    "art": [
      "#14532d",
      "#a3e635"
    ],
    "approxSize": "~150 MB",
    "genres": [
      "Sandbox",
      "Simulation"
    ],
    "tags": [
      "Voxel",
      "Building",
      "Survival",
      "Game Platform"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://playbound.club/games/luanti/cover.webp",
    "repo": "luanti-org/luanti",
    "assetPattern": "-win64\\.zip$",
    "exeHint": "luanti|minetest",
    "connectArgs": [
      "--go",
      "--address",
      "{host}",
      "--port",
      "{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Android"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.826Z"
  },
  {
    "slug": "mega-man-unlimited",
    "title": "Mega Man Unlimited",
    "blurb": "A complete NES-style Mega Man fangame — unofficial, free, finished.",
    "kind": "external",
    "art": [
      "#1e3a8a",
      "#38bdf8"
    ],
    "approxSize": "~300 MB",
    "genres": [
      "Platformer",
      "Action"
    ],
    "tags": [
      "Fangame",
      "Retro",
      "NES-style",
      "Singleplayer"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/mega-man-unlimited/cover-b159d09c82b58ae9.webp",
    "url": "https://megaphilx.com/index.php/home/games/mega-man-unlimited/",
    "note": "Unofficial fangame. Download only from the creator’s site — PlayBound does not host the zip.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-06T20:27:47.260Z"
  },
  {
    "slug": "mindustry",
    "title": "Mindustry",
    "blurb": "Factory-building tower defense with serious depth.",
    "kind": "github-jar",
    "art": [
      "#3f1d0b",
      "#fb923c"
    ],
    "approxSize": "~250 MB",
    "genres": [
      "Tower Defense",
      "Strategy",
      "Sandbox"
    ],
    "tags": [
      "Automation",
      "Factory",
      "Co-op",
      "Waves"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/mindustry/cover-ecdc927c983ba5d3.webp",
    "repo": "Anuken/Mindustry",
    "assetPattern": "^Mindustry\\.jar$",
    "connectArgs": [
      "{host}:{port}"
    ],
    "note": "Requires Java 17+ (Adoptium Temurin).",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Android",
      "iOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.723Z"
  },
  {
    "slug": "naev",
    "title": "Naev",
    "blurb": "A 2D galaxy of freedom, factions, and consequences.",
    "kind": "github-installer",
    "art": [
      "#0f172a",
      "#38bdf8"
    ],
    "approxSize": "~400 MB",
    "genres": [
      "Space",
      "RPG"
    ],
    "tags": [
      "Open World",
      "Factions",
      "Trading",
      "Story"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://playbound.club/games/naev/cover.webp",
    "repo": "naev/naev",
    "assetPattern": "win64\\.exe$",
    "knownExePaths": [
      "%PROGRAMFILES%\\Naev\\naev.exe",
      "%PROGRAMFILES(X86)%\\Naev\\naev.exe",
      "%PROGRAMFILES%\\naev\\naev.exe",
      "%LOCALAPPDATA%\\Programs\\naev\\naev.exe",
      "%LOCALAPPDATA%\\Programs\\Naev\\naev.exe"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.907Z"
  },
  {
    "slug": "next-gen-chess",
    "title": "Next-Gen Chess",
    "blurb": "Chess that teaches you while you play.",
    "kind": "external",
    "url": "https://ngchess.com",
    "art": [
      "#831843",
      "#f472b6"
    ],
    "approxSize": "Browser",
    "genres": [
      "Strategy"
    ],
    "tags": [
      "Browser",
      "Indie"
    ],
    "launchMethods": [
      "browser"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-08-03T17:05:12.686Z",
    "coverImage": "https://ngchess.com/img/og-card.png?v=2026-06-28"
  },
  {
    "slug": "openciv3",
    "title": "OpenCiv3",
    "blurb": "Civilization III rebuilt for modern modders and platforms.",
    "kind": "github-zip",
    "art": [
      "#1e3a5f",
      "#f59e0b"
    ],
    "approxSize": "~150 MB",
    "genres": [
      "Strategy",
      "Simulation"
    ],
    "tags": [
      "4X",
      "Turn-Based",
      "Mods",
      "Sandbox"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/openciv3/cover-ab9ef491806b900a.webp",
    "repo": "C7-Game/OpenCiv3",
    "assetPattern": "OpenCiv3_.*-Windows\\.zip$",
    "exeHint": "OpenCiv3",
    "note": "Runs standalone with placeholder art. PlayBound sets windowed 1920×1080 (Library → Display to change). Optional: install Civilization III Complete (Steam/GOG) for original graphics — OpenCiv3 auto-detects it.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-08T20:29:04.605Z"
  },
  {
    "slug": "openra",
    "title": "OpenRA",
    "blurb": "Classic real-time strategy, rebuilt for the modern age.",
    "kind": "github-zip",
    "art": [
      "#7f1d1d",
      "#f59e0b"
    ],
    "approxSize": "~350 MB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Classic",
      "Base Building",
      "Ranked",
      "Mods",
      "LAN"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/openra/cover-1786820561186.webp",
    "repo": "OpenRA/OpenRA",
    "assetPattern": "x64-winportable\\.zip$",
    "exeHint": "RedAlert|OpenRA",
    "connectArgs": [
      "Game.Connect={host}:{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.588Z"
  },
  {
    "slug": "openttd",
    "title": "OpenTTD",
    "blurb": "Build a transport empire, one rail at a time.",
    "kind": "openttd-zip",
    "art": [
      "#164e63",
      "#67e8f9"
    ],
    "approxSize": "~200 MB",
    "genres": [
      "Simulation",
      "Strategy"
    ],
    "tags": [
      "Trains",
      "Logistics",
      "Management",
      "Sandbox"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://playbound.club/games/openttd/cover.webp",
    "exeHint": "openttd",
    "connectArgs": [
      "-n",
      "{host}:{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.744Z"
  },
  {
    "slug": "shattered-pixel-dungeon",
    "title": "Shattered Pixel Dungeon",
    "blurb": "The roguelike that respects your time and ruins your evening.",
    "kind": "github-zip",
    "art": [
      "#3b0764",
      "#e879f9"
    ],
    "approxSize": "~60 MB",
    "genres": [
      "Roguelike",
      "RPG"
    ],
    "tags": [
      "Permadeath",
      "Turn-Based",
      "Pixel Art",
      "Runs"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/shattered-pixel-dungeon/shot-1786803222908.webp",
    "repo": "00-Evan/shattered-pixel-dungeon",
    "assetPattern": "Windows\\.zip$",
    "exeHint": "ShatteredPD|Shattered",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Android",
      "iOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.785Z"
  },
  {
    "slug": "supertux",
    "title": "SuperTux",
    "blurb": "Run, jump, and slide through a frosty platforming classic.",
    "kind": "github-zip",
    "art": [
      "#0c4a6e",
      "#e0f2fe"
    ],
    "approxSize": "~250 MB",
    "genres": [
      "Platformer",
      "Arcade"
    ],
    "tags": [
      "2D",
      "Family Friendly",
      "Level Editor",
      "Classic"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/supertux/shot-1786802447216.webp",
    "repo": "SuperTux/supertux",
    "assetPattern": "win64-portable\\.zip$",
    "exeHint": "supertux",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.866Z"
  },
  {
    "slug": "supertuxkart",
    "title": "SuperTuxKart",
    "blurb": "Kart racing chaos for the whole couch.",
    "kind": "github-zip",
    "art": [
      "#14532d",
      "#4ade80"
    ],
    "approxSize": "~900 MB",
    "genres": [
      "Racing",
      "Arcade"
    ],
    "tags": [
      "Kart Racing",
      "Split-Screen",
      "Family Friendly",
      "Party"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/supertuxkart/shot-1786820105718.webp",
    "repo": "supertuxkart/stk-code",
    "assetPattern": "-win\\.zip$",
    "exeHint": "supertuxkart",
    "connectArgs": [
      "--connect-now={host}:{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Android"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.660Z"
  },
  {
    "slug": "battle-for-wesnoth",
    "title": "The Battle for Wesnoth",
    "blurb": "A legendary open-source fantasy strategy epic.",
    "kind": "direct-installer",
    "art": [
      "#312e81",
      "#a78bfa"
    ],
    "approxSize": "~700 MB",
    "genres": [
      "Strategy",
      "RPG"
    ],
    "tags": [
      "Turn-Based",
      "Fantasy",
      "Campaigns",
      "Hotseat"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/battle-for-wesnoth/cover-98c555dbf1f767cd.webp",
    "url": "https://sourceforge.net/projects/wesnoth/files/wesnoth-1.18/wesnoth-1.18.7/wesnoth-1.18.7-win64.exe/download",
    "fileName": "wesnoth-1.18.7-win64.exe",
    "versionLabel": "1.18.7",
    "knownExePaths": [
      "%PROGRAMFILES%\\Battle for Wesnoth 1.18\\wesnoth.exe",
      "%PROGRAMFILES(X86)%\\Battle for Wesnoth 1.18\\wesnoth.exe",
      "%LOCALAPPDATA%\\Programs\\Battle for Wesnoth 1.18\\wesnoth.exe",
      "%LOCALAPPDATA%\\Programs\\Battle for Wesnoth\\wesnoth.exe"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.639Z"
  },
  {
    "slug": "tinywind-pixel-pirate-sailing-game",
    "title": "Tinywind — Pixel Pirate Sailing Game",
    "blurb": "Outsail the Royal Navy in your browser. Real sailing physics, 5-minute voyages, 30 historical treasures to recover. Free to play.",
    "kind": "external",
    "url": "https://tinywind.io/",
    "art": [
      "#831843",
      "#f472b6"
    ],
    "approxSize": "Browser",
    "genres": [],
    "tags": [
      "Browser",
      "Indie"
    ],
    "multiplayer": false,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-07-25T20:06:07.464Z",
    "coverImage": "https://tinywind.io/opengraph-image?ca63dcafdaa67b1f"
  },
  {
    "slug": "unvanquished",
    "title": "Unvanquished",
    "blurb": "Aliens vs humans in asymmetric FPS-strategy warfare.",
    "kind": "github-zip",
    "art": [
      "#052e16",
      "#86efac"
    ],
    "approxSize": "~850 MB",
    "genres": [
      "FPS",
      "Strategy"
    ],
    "tags": [
      "Asymmetric",
      "Team-Based",
      "Base Building",
      "Sci-Fi"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/unvanquished/cover-4760390b4f3a0a69.webp",
    "repo": "Unvanquished/updater",
    "assetPattern": "UnvUpdaterWin\\.zip$",
    "exeHint": "UnvanquishedUpdater|updater",
    "connectArgs": [
      "+connect",
      "{host}:{port}"
    ],
    "note": "Installs the Unvanquished updater, which downloads the game.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-25T19:46:51.947Z"
  },
  {
    "slug": "veloren",
    "title": "Veloren",
    "blurb": "A voxel world of dragons, dungeons, and endless horizons.",
    "kind": "direct-installer",
    "art": [
      "#1e3a5f",
      "#34d399"
    ],
    "approxSize": "~1.6 GB",
    "genres": [
      "RPG",
      "Sandbox"
    ],
    "tags": [
      "Voxel",
      "Open World",
      "Co-op",
      "Exploration"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "exeHint": "airshipper",
    "url": "https://gitlab.com/veloren/airshipper/-/releases/v0.17.0/downloads/binaries/windows-installer-x86_64",
    "fileName": "airshipper-installer.exe",
    "versionLabel": "0.17.0",
    "knownExePaths": [
      "%LOCALAPPDATA%\\Programs\\Airshipper\\airshipper.exe",
      "%LOCALAPPDATA%\\airshipper\\airshipper.exe",
      "%PROGRAMFILES%\\Airshipper\\airshipper.exe",
      "%PROGRAMFILES(X86)%\\Airshipper\\airshipper.exe"
    ],
    "registryTitles": [
      "Airshipper",
      "Veloren"
    ],
    "note": "Installs Airshipper, which downloads and updates Veloren.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.703Z"
  },
  {
    "slug": "villagers-and-heroes",
    "title": "Villagers & Heroes",
    "blurb": "A fantasy MMO with one account and one character across PC and mobile.",
    "kind": "direct-installer",
    "art": [
      "#166534",
      "#bef264"
    ],
    "approxSize": "~1.7 GB",
    "genres": [
      "MMO",
      "RPG"
    ],
    "tags": [
      "Fantasy",
      "Cross-Platform",
      "Casual MMO"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/villagers-and-heroes/cover-1786171794131-x36qh3.webp",
    "exeHint": "Villagers|VH|MadOtter",
    "url": "https://villagersandheroes.com/VHSetup.exe",
    "fileName": "VHSetup.exe",
    "knownExePaths": [
      "%PROGRAMFILES%\\Villagers and Heroes\\Villagers and Heroes.exe",
      "%PROGRAMFILES(X86)%\\Villagers and Heroes\\Villagers and Heroes.exe",
      "%PROGRAMFILES%\\Mad Otter Games\\Villagers and Heroes\\Villagers and Heroes.exe",
      "%PROGRAMFILES(X86)%\\Mad Otter Games\\Villagers and Heroes\\Villagers and Heroes.exe",
      "%LOCALAPPDATA%\\Programs\\Villagers and Heroes\\Villagers and Heroes.exe",
      "%LOCALAPPDATA%\\Villagers and Heroes\\Villagers and Heroes.exe"
    ],
    "registryTitles": [
      "Villagers and Heroes",
      "Villagers & Heroes"
    ],
    "note": "Official Mad Otter PC setup — finish the wizard, then Play. Steam not required.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Android",
      "iOS"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T19:24:02.466Z"
  },
  {
    "slug": "warframe",
    "title": "Warframe",
    "blurb": "Space-ninja co-op shooter — free to play, live-service shop included.",
    "kind": "direct-installer",
    "art": [
      "#1e1b4b",
      "#22d3ee"
    ],
    "approxSize": "~50.0 GB",
    "genres": [
      "Shooter",
      "Action",
      "MMO"
    ],
    "tags": [
      "Free to Play",
      "Co-op",
      "Looter Shooter",
      "Sci-Fi"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/warframe/cover-d06b94056c690105.webp",
    "exeHint": "Warframe",
    "url": "https://content.warframe.com/dl/Warframe.msi",
    "fileName": "Warframe.msi",
    "knownExePaths": [
      "%PROGRAMFILES%\\Warframe\\Tools\\Launcher.exe",
      "%PROGRAMFILES%\\Warframe\\Downloaded\\Public\\Warframe.x64.exe",
      "%PROGRAMFILES(X86)%\\Steam\\steamapps\\common\\Warframe\\Tools\\Launcher.exe",
      "%PROGRAMFILES(X86)%\\Steam\\steamapps\\common\\Warframe\\Warframe.x64.exe"
    ],
    "registryTitles": [
      "Warframe"
    ],
    "note": "Official Warframe.msi from Digital Extremes. Steam app 230410 is an alternative.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-27T22:42:00.383Z"
  },
  {
    "slug": "warzone-2100",
    "title": "Warzone 2100",
    "blurb": "Design your own tanks. Then design better ones.",
    "kind": "github-zip",
    "art": [
      "#422006",
      "#fbbf24"
    ],
    "approxSize": "~550 MB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Unit Design",
      "Campaign",
      "Post-Apocalyptic",
      "Classic"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/warzone-2100/cover-61995bbfdc394f18.webp",
    "repo": "Warzone2100/warzone2100",
    "assetPattern": "win_x64_archive\\.zip$",
    "exeHint": "warzone2100",
    "connectArgs": [
      "--join={host}:{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.846Z"
  },
  {
    "slug": "xonotic",
    "title": "Xonotic",
    "blurb": "The fastest arena shooter on the planet. Completely free.",
    "kind": "direct-zip",
    "art": [
      "#0c4a6e",
      "#22d3ee"
    ],
    "approxSize": "~1.1 GB",
    "genres": [
      "FPS",
      "Arcade"
    ],
    "tags": [
      "Arena Shooter",
      "Competitive",
      "Movement",
      "Duels"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/xonotic/cover-4c9c2779448a8598.webp",
    "exeHint": "xonotic.*x64|xonotic",
    "url": "https://dl.xonotic.org/xonotic-0.8.6.zip",
    "connectArgs": [
      "+connect",
      "{host}:{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.618Z"
  },
  {
    "slug": "zero-k",
    "title": "Zero-K",
    "blurb": "Physics-driven RTS where terrain is a weapon.",
    "kind": "direct-exe",
    "art": [
      "#111827",
      "#94a3b8"
    ],
    "approxSize": "~1.3 GB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Physics",
      "Terraforming",
      "Co-op",
      "Competitive"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/zero-k/cover-ae7a710dcadabbe7.webp",
    "url": "https://zero-k.info/lobby/Zero-K.exe",
    "note": "Downloads the Zero-K lobby, which fetches the game on first run.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-25T19:46:51.887Z"
  },
  {
    "slug": "holocure",
    "title": "HoloCure - Save the Fans!",
    "blurb": "Top-down bullet-heaven roguelite with 47 unique idols, deep buildcrafting, and zero MTX.",
    "kind": "itch-zip",
    "art": [
      "#0284c7",
      "#38bdf8"
    ],
    "approxSize": "~250 MB",
    "genres": [
      "Action",
      "Roguelike",
      "Arcade"
    ],
    "tags": [
      "Bullet Heaven",
      "Roguelite",
      "Bullet Hell",
      "Pixel Art",
      "Controller Support",
      "Steam Deck",
      "Anime",
      "Zero MTX",
      "Singleplayer",
      "Minigames"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/holocure/cover-52f5d52ed77e6af1.webp",
    "exeHint": "HoloCure|holocure",
    "url": "https://kay-yu.itch.io/holocure",
    "fileName": "HoloCure.zip",
    "versionLabel": "latest",
    "knownExePaths": [
      "%LOCALAPPDATA%\\HoloCure\\HoloCure.exe",
      "%PROGRAMFILES%\\HoloCure\\HoloCure.exe",
      "%PROGRAMFILES(X86)%\\Steam\\steamapps\\common\\HoloCure\\HoloCure.exe",
      "~/PlayBound/Games/holocure/HoloCure.exe",
      "~/.local/share/HoloCure/HoloCure.exe",
      "~/.steam/steam/steamapps/common/HoloCure/HoloCure.exe"
    ],
    "note": "Downloads and extracts the official standalone HoloCure build from itch.io. Runs on Windows and Linux (via Wine/Proton/Steam Deck).",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T10:54:55.837Z"
  },
  {
    "slug": "asherons-call",
    "title": "Asheron's Call",
    "blurb": "The legendary 1999 seamless open-world MMORPG, preserved by ACEmulator.",
    "kind": "github-zip",
    "art": [
      "#1e1b4b",
      "#818cf8"
    ],
    "approxSize": "~2.0 GB",
    "genres": [
      "RPG",
      "MMO"
    ],
    "tags": [
      "MMORPG",
      "Classic",
      "Fantasy",
      "Open World",
      "Community Servers",
      "Emulator"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/asherons-call/shot-1786799468368.webp",
    "repo": "ACEmulator/ACE",
    "assetPattern": ".*\\.zip$",
    "exeHint": "acclient.exe",
    "versionLabel": "v1.0.0",
    "knownExePaths": [
      "acclient.exe",
      "ThwargLauncher.exe"
    ],
    "note": "Installs the full Asheron's Call client and ThwargLauncher for connecting to public ACE community servers.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-14T19:29:04.034Z"
  },
  {
    "slug": "brawlhalla",
    "title": "Brawlhalla",
    "blurb": "Fight your way to the top",
    "kind": "external",
    "art": [
      "#312e81",
      "#facc15"
    ],
    "approxSize": "~800 MB",
    "genres": [
      "Fighting"
    ],
    "tags": [
      "Platform Fighter",
      "Cross-Platform",
      "Competitive"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/brawlhalla/shot-1786843679939.webp",
    "url": "https://store.steampowered.com/app/291550/",
    "note": "Free to play on Steam — Steam handles the download and install. Also available on Google Play and the App Store.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Android",
      "iOS"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T19:24:02.434Z"
  },
  {
    "slug": "counter-strike-2",
    "title": "Counter-Strike 2",
    "blurb": "Valve's free competitive FPS with Workshop maps and skins.",
    "kind": "external",
    "art": [
      "#422006",
      "#fbbf24"
    ],
    "approxSize": "~40.0 GB",
    "genres": [
      "FPS"
    ],
    "tags": [
      "Competitive",
      "Free to Play",
      "Esports",
      "Tactical"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/counter-strike-2/cover-d43c4390ebd8629d.webp",
    "url": "https://store.steampowered.com/app/730/CounterStrike_2/",
    "note": "Free on Steam.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.990Z"
  },
  {
    "slug": "dota-2",
    "title": "Dota 2",
    "blurb": "No two matches play the same.",
    "kind": "external",
    "art": [
      "#1e3a5f",
      "#93c5fd"
    ],
    "approxSize": "~60.0 GB",
    "genres": [
      "Strategy"
    ],
    "tags": [
      "MOBA",
      "Free to Play",
      "Esports",
      "Workshop"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg",
    "url": "https://store.steampowered.com/app/570/Dota_2/",
    "note": "Free on Steam.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.856Z"
  },
  {
    "slug": "freedoom",
    "title": "Freedoom",
    "blurb": "Classic 90s FPS action, completely free and powered by GZDoom.",
    "kind": "github-zip",
    "art": [
      "#991b1b",
      "#f87171"
    ],
    "approxSize": "~95 MB",
    "genres": [
      "FPS",
      "Arcade"
    ],
    "tags": [
      "Classic",
      "Doom Engine",
      "Fast Paced",
      "Singleplayer",
      "Deathmatch",
      "Mod Support",
      "Retro FPS"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/freedoom/cover-1786800861187.webp",
    "repo": "ZDoom/gzdoom",
    "assetPattern": "gzdoom-.*-windows\\.zip$",
    "exeHint": "gzdoom",
    "note": "Bundles the GZDoom source port with Freedoom Phase 1 & 2 IWADs for one-click play.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:04:23.561Z"
  },
  {
    "slug": "gamebuddies-io",
    "title": "GameBuddies.io",
    "blurb": "Party games in the browser with friends.",
    "kind": "external",
    "url": "https://gamebuddies.io",
    "art": [
      "#be123c",
      "#fda4af"
    ],
    "approxSize": "Browser",
    "genres": [
      "Arcade",
      "Puzzle"
    ],
    "tags": [
      "Browser",
      "Party",
      "Multiplayer",
      "Casual"
    ],
    "launchMethods": [
      "browser"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web",
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-08-07T08:04:23.735Z",
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/gamebuddies-io/cover-6e5337bc30bd289c.webp"
  },
  {
    "slug": "genshin-impact",
    "title": "Genshin Impact",
    "blurb": "Step into a world of wonder, adventure, and elemental chaos.",
    "kind": "external",
    "art": [
      "#0e7490",
      "#67e8f9"
    ],
    "approxSize": "~80.0 GB",
    "genres": [
      "RPG",
      "Sandbox"
    ],
    "tags": [
      "Open World",
      "Free to Play",
      "Anime",
      "Gacha"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/genshin-impact/shot-1786838245940.webp",
    "url": "https://genshin.hoyoverse.com",
    "note": "Official Hoyoverse launcher only.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "PlayStation",
      "iOS",
      "Android"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T08:49:19.824Z"
  },
  {
    "slug": "gradius-remake",
    "title": "Gradius Remake",
    "blurb": "Remake of the game Gradius (NES - 1986)",
    "kind": "external",
    "art": [
      "#0f172a",
      "#6366f1"
    ],
    "approxSize": "~25 MB",
    "genres": [
      "Action",
      "Arcade"
    ],
    "tags": [
      "GDScript"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/gradius-remake/cover-1786836545147.webp",
    "url": "https://github.com/luisfae/GradiusRemake",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-14T18:46:32.407Z"
  },
  {
    "slug": "keeperfx",
    "title": "KeeperFX",
    "blurb": "Build the dungeon. Break the rules. Rule the Underworld.",
    "kind": "external",
    "art": [
      "#312e81",
      "#a78bfa"
    ],
    "approxSize": "~700 MB",
    "genres": [
      "Strategy",
      "Simulation"
    ],
    "tags": [
      "TypeScript"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/keeperfx/shot-1786823966900.webp",
    "url": "https://github.com/joko1977-ui/DungeonKeeperReborn",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-14T20:55:11.090Z"
  },
  {
    "slug": "league-of-legends",
    "title": "League of Legends",
    "blurb": "Master your champion. Outplay the competition.",
    "kind": "external",
    "art": [
      "#1e1b4b",
      "#c4b5fd"
    ],
    "approxSize": "~22.0 GB",
    "genres": [
      "Strategy"
    ],
    "tags": [
      "MOBA",
      "Free to Play",
      "Esports",
      "Competitive"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/league-of-legends/shot-1786835322548.webp",
    "url": "https://www.leagueoflegends.com",
    "note": "Riot Client only — do not use unofficial clients.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T08:49:19.922Z"
  },
  {
    "slug": "marathon-2",
    "title": "Marathon 2",
    "blurb": "Aleph One is the open source continuation of Bungie’s Marathon 2 game engine.",
    "kind": "external",
    "art": [
      "#3b0764",
      "#e879f9"
    ],
    "approxSize": "~25 MB",
    "genres": [
      "FPS",
      "Shooter",
      "Action"
    ],
    "tags": [
      "C++"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/marathon-2/cover-1786823223609.webp",
    "url": "https://alephone.lhowon.org/",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-14T18:55:18.622Z"
  },
  {
    "slug": "microsoft-allegiance",
    "title": "Microsoft Allegiance",
    "blurb": "A forgotten multiplayer space game that still feels like a glimpse into the future.",
    "kind": "external",
    "art": [
      "#4c1d95",
      "#c084fc"
    ],
    "approxSize": "~2.0 GB",
    "genres": [
      "Action",
      "Simulation",
      "Strategy"
    ],
    "tags": [
      "Free To Play"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/700480/header.jpg?t=1719293526",
    "url": "http://www.freeallegiance.org",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-14T19:03:58.855Z"
  },
  {
    "slug": "mrboom",
    "title": "Mrboom",
    "blurb": "Four players. One screen. Absolute chaos.",
    "kind": "external",
    "url": "https://mrboom.mumblecore.org/",
    "art": [
      "#831843",
      "#f472b6"
    ],
    "approxSize": "~50 MB",
    "genres": [
      "Arcade"
    ],
    "tags": [
      "Browser",
      "Indie"
    ],
    "launchMethods": [
      "browser"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-08-14T18:47:56.610Z",
    "coverImage": "https://mrboom.mumblecore.org/mrb0.png"
  },
  {
    "slug": "old-school-runescape",
    "title": "Old School RuneScape",
    "blurb": "The 2007-era build of RuneScape, shaped ever since by player votes.",
    "kind": "direct-installer",
    "art": [
      "#713f12",
      "#eab308"
    ],
    "approxSize": "~2.0 GB",
    "genres": [
      "MMO",
      "RPG"
    ],
    "tags": [
      "Classic",
      "Fantasy",
      "Open World"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/old-school-runescape/cover-6b8a18c30b9f0f1a.webp",
    "exeHint": "OldSchool|JagexLauncher",
    "url": "https://www.runescape.com/downloads/oldschool.msi",
    "fileName": "OldSchool.msi",
    "knownExePaths": [
      "%PROGRAMFILES(X86)%\\Jagex\\Old School RuneScape\\OldSchool.exe",
      "%PROGRAMFILES%\\Jagex\\Old School RuneScape\\OldSchool.exe",
      "%PROGRAMFILES(X86)%\\Jagex Launcher\\JagexLauncher.exe",
      "%LOCALAPPDATA%\\Jagex Launcher\\JagexLauncher.exe"
    ],
    "registryTitles": [
      "Old School RuneScape",
      "Jagex Launcher"
    ],
    "note": "Small client — the game itself streams, so there is no large download.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T18:29:49.962Z"
  },
  {
    "slug": "openarena",
    "title": "OpenArena",
    "blurb": "Rocket jumps, railgun duels, and nothing to buy.",
    "kind": "direct-zip",
    "art": [
      "#7c2d12",
      "#fdba74"
    ],
    "approxSize": "~405 MB",
    "genres": [
      "FPS",
      "Arcade",
      "Action"
    ],
    "tags": [
      "Arena Shooter",
      "Competitive",
      "Classic",
      "Open Source",
      "Deathmatch",
      "CTF",
      "LAN"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/openarena/shot-1786831985947.webp",
    "exeHint": "openarena",
    "url": "https://sourceforge.net/projects/oarena/files/openarena-0.8.8.zip/download",
    "fileName": "openarena-0.8.8.zip",
    "versionLabel": "0.8.8",
    "knownExePaths": [
      "openarena-0.8.8/openarena.exe",
      "openarena-0.8.8/oa_ded.exe",
      "openarena.exe"
    ],
    "installRoot": "openarena-0.8.8",
    "connectArgs": [
      "+connect {host}:{port}"
    ],
    "note": "0.8.8 is the last stable release (2012) and is what every public server runs. It is a complete game — no original Quake III files needed.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:04:23.666Z"
  },
  {
    "slug": "openlara",
    "title": "OpenLara",
    "blurb": "The open-source modern engine reimplementation of classic Tomb Raider.",
    "kind": "github-zip",
    "art": [
      "#065f46",
      "#34d399"
    ],
    "approxSize": "~50 MB",
    "genres": [
      "Action",
      "Adventure",
      "Platformer"
    ],
    "tags": [
      "Classic",
      "Tomb Raider",
      "Open Source",
      "Browser Playable",
      "Action-Adventure",
      "Retro"
    ],
    "launchMethods": [
      "browser",
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/openlara/cover-bafd4de1cc761562.webp",
    "repo": "XProger/OpenLara",
    "assetPattern": ".*\\.zip$",
    "exeHint": "OpenLara.exe",
    "versionLabel": "latest",
    "knownExePaths": [
      "OpenLara.exe",
      "openlara"
    ],
    "note": "Installs native desktop OpenLara with 4K widescreen, VR support, and split-screen co-op.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Browser"
    ],
    "browserPlayable": true,
    "steamDeck": true,
    "createdAt": "2026-08-14T18:26:35.960Z"
  },
  {
    "slug": "pixreveal",
    "title": "PixReveal",
    "blurb": "Guess The Pixel Art",
    "kind": "external",
    "url": "https://pixreveal.com",
    "art": [
      "#4c1d95",
      "#e9d5ff"
    ],
    "approxSize": "Browser",
    "genres": [
      "Puzzle",
      "Arcade",
      "Party Game"
    ],
    "tags": [
      "Browser",
      "Casual",
      "Indie",
      "Family Friendly"
    ],
    "launchMethods": [
      "browser"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web",
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-08-07T08:04:23.701Z",
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/pixreveal/shot-1786828398865.webp"
  },
  {
    "slug": "privateer-gemini-gold",
    "title": "Privateer Gemini Gold",
    "blurb": "Wing Commander's open-ended space sim, rebuilt and free.",
    "kind": "direct-installer",
    "art": [
      "#0b1120",
      "#f59e0b"
    ],
    "approxSize": "~320 MB",
    "genres": [
      "Space",
      "Simulation",
      "Action",
      "RPG"
    ],
    "tags": [
      "Space Sim",
      "Open World",
      "Trading",
      "Dogfighting",
      "Remake",
      "Classic"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/privateer-gemini-gold/cover-1786834113679.webp",
    "exeHint": "privateer|vegastrike",
    "url": "https://downloads.sourceforge.net/project/privateer/Wing%20Commander%20Privateer/Privateer%20Gemini%20Gold%201.03/PrivateerGold1.03.exe",
    "fileName": "PrivateerGold1.03.exe",
    "versionLabel": "1.03",
    "knownExePaths": [
      "%PROGRAMFILES%\\Privateer Gemini Gold\\privateer.exe",
      "%PROGRAMFILES(X86)%\\Privateer Gemini Gold\\privateer.exe",
      "%LOCALAPPDATA%\\Programs\\Privateer Gemini Gold\\privateer.exe"
    ],
    "registryTitles": [
      "Privateer Gemini Gold",
      "Privateer"
    ],
    "note": "Opens the official Privateer Gemini Gold setup — finish the wizard, then Play.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-15T12:11:49.413Z"
  },
  {
    "slug": "quake-champions",
    "title": "Quake Champions",
    "blurb": "id's free arena shooter with champion abilities.",
    "kind": "external",
    "art": [
      "#431407",
      "#fb923c"
    ],
    "approxSize": "~45.0 GB",
    "genres": [
      "FPS",
      "Arcade"
    ],
    "tags": [
      "Arena Shooter",
      "Free to Play",
      "Competitive"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/quake-champions/cover-1786834851502.webp",
    "url": "https://store.steampowered.com/app/611500/Quake_Champions/",
    "note": "Steam or Bethesda.net.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:20.036Z"
  },
  {
    "slug": "space-station-14",
    "title": "Space Station 14",
    "blurb": "A multiplayer game about paranoia and disaster, remaking the classic Space Station 13",
    "kind": "external",
    "url": "https://spacestation14.com/",
    "art": [
      "#831843",
      "#f472b6"
    ],
    "approxSize": "~50 MB",
    "genres": [
      "Arcade"
    ],
    "tags": [
      "Browser",
      "Indie"
    ],
    "launchMethods": [
      "browser"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-08-14T19:38:16.012Z",
    "coverImage": "https://cdn.cloudflare.steamstatic.com/steam/apps/1255460/header.jpg"
  },
  {
    "slug": "star-wars-galaxies",
    "title": "Star Wars Galaxies",
    "blurb": "The MMO galaxy lives on through community editions.",
    "kind": "external",
    "art": [
      "#1e293b",
      "#facc15"
    ],
    "approxSize": "~3.5 GB",
    "genres": [
      "RPG",
      "Sandbox",
      "MMO"
    ],
    "tags": [
      "Star Wars",
      "MMORPG",
      "Emulator",
      "Sandbox"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/star-wars-galaxies/shot-1786828986010.webp",
    "exeHint": "SWGR|swg",
    "url": "https://swgr.org/play/",
    "knownExePaths": [
      "%LOCALAPPDATA%\\SWG Restoration\\SWGRestoration.exe",
      "%PROGRAMFILES%\\SWG Restoration\\SWGRestoration.exe",
      "~/PlayBound/Games/star-wars-galaxies/SWGRestoration.exe"
    ],
    "note": "Star Wars Galaxies restoration MMO client with Windows and Linux launcher support.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.521Z"
  },
  {
    "slug": "star-wars-the-old-republic",
    "title": "Star Wars: The Old Republic",
    "blurb": "A story-driven, free-to-play Star Wars MMO set millennia before the films.",
    "kind": "direct-installer",
    "art": [
      "#450a0a",
      "#ef4444"
    ],
    "approxSize": "~75.0 GB",
    "genres": [
      "MMO",
      "RPG"
    ],
    "tags": [
      "Sci-Fi",
      "Story Driven",
      "Multiplayer"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/star-wars-the-old-republic/cover-4e6d903734f46bdc.webp",
    "exeHint": "launcher|swtor",
    "url": "https://cdn-d6patch.swtor.com/swtor/setup/SWTOR_setup.exe",
    "fileName": "SWTOR_setup.exe",
    "knownExePaths": [
      "%PROGRAMFILES(X86)%\\EA\\BioWare\\Star Wars-The Old Republic\\launcher.exe",
      "%PROGRAMFILES(X86)%\\Electronic Arts\\BioWare\\Star Wars-The Old Republic\\launcher.exe",
      "%PROGRAMFILES%\\EA\\BioWare\\Star Wars-The Old Republic\\launcher.exe"
    ],
    "registryTitles": [
      "Star Wars",
      "Star Wars™: The Old Republic",
      "Star Wars: The Old Republic"
    ],
    "note": "Installs the SWTOR launcher, which then downloads the game.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T18:29:49.865Z"
  },
  {
    "slug": "starcraft",
    "title": "StarCraft",
    "blurb": "The RTS that defined competitive play, given away free by Blizzard.",
    "kind": "external",
    "art": [
      "#172554",
      "#60a5fa"
    ],
    "approxSize": "~8.0 GB",
    "genres": [
      "Strategy"
    ],
    "tags": [
      "RTS",
      "Competitive",
      "Classic",
      "Esports"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/starcraft/cover-1786799854106.webp",
    "url": "https://us.shop.battle.net/en-us/product/starcraft",
    "note": "Free through the Battle.net app. Install Battle.net, then pick StarCraft — the Anthology (StarCraft + Brood War) costs nothing. Remastered is a separate paid upgrade you do not need.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux",
      "macOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.554Z"
  },
  {
    "slug": "strikers-club",
    "title": "Strikers Club",
    "blurb": "Every touch matters. Every player counts.",
    "kind": "external",
    "art": [
      "#14532d",
      "#4ade80"
    ],
    "approxSize": "~2.0 GB",
    "genres": [
      "Sports"
    ],
    "tags": [
      "Physics Based",
      "Multiplayer",
      "Competitive"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/strikers-club/shot-1786840698553.webp",
    "url": "https://store.steampowered.com/app/1952920/",
    "note": "Free to play on Steam — Steam handles the download and install.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T18:29:50.037Z"
  },
  {
    "slug": "team-fortress-2",
    "title": "Team Fortress 2",
    "blurb": "The landmark class-based shooter with 9 iconic classes and endless community creativity.",
    "kind": "external",
    "art": [
      "#9a3412",
      "#fdba74"
    ],
    "approxSize": "~25.0 GB",
    "genres": [
      "FPS",
      "Action",
      "Shooter"
    ],
    "tags": [
      "Class Shooter",
      "Hero Shooter",
      "Multiplayer",
      "Co-op",
      "PvE",
      "FPS",
      "Competitive",
      "Classic",
      "Free to Play"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/team-fortress-2/cover-26ed139ddde4bedf.webp",
    "exeHint": "hl2.exe",
    "url": "steam://run/440",
    "knownExePaths": [
      "tf_win64.exe",
      "hl2.exe"
    ],
    "note": "Free to play on Steam. Launches TF2 with custom HUD, mastercomfig, and community server support.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.791Z"
  },
  {
    "slug": "daggerfall",
    "title": "The Elder Scrolls II: Daggerfall",
    "blurb": "An enormous classic RPG — play the original data with modern remasters.",
    "kind": "github-zip",
    "art": [
      "#1e1b4b",
      "#a78bfa"
    ],
    "approxSize": "~500 MB",
    "genres": [
      "RPG",
      "Sandbox"
    ],
    "tags": [
      "Open World",
      "Classic",
      "Fantasy",
      "Mods",
      "Singleplayer"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/daggerfall/cover-3df9e7053f4f76fb.webp",
    "repo": "Interkarma/daggerfall-unity",
    "assetPattern": "DaggerfallUnity.*Windows.*\\.zip$|dfu_windows.*\\.zip$|\\.zip$",
    "exeHint": "DaggerfallUnity.exe",
    "versionLabel": "v1.1.1",
    "knownExePaths": [
      "DaggerfallUnity.exe"
    ],
    "note": "Installs Daggerfall Unity with full widescreen, controller support, and modern modding. Bethesda released the original Daggerfall game data 100% free.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux",
      "macOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.355Z"
  },
  {
    "slug": "tes-arena",
    "title": "The Elder Scrolls: Arena",
    "blurb": "Where Tamriel began — Bethesda's freeware classic RPG.",
    "kind": "direct-zip",
    "art": [
      "#422006",
      "#fbbf24"
    ],
    "approxSize": "~40 MB",
    "genres": [
      "RPG"
    ],
    "tags": [
      "Classic",
      "Freeware",
      "Fantasy",
      "Open World"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/tes-arena/cover-27bb70dd655a0afe.webp",
    "exeHint": "ARENA.EXE",
    "url": "https://cdnstatic.bethsoft.com/elderscrolls.com/assets/files/tes/extras/Arena106Setup.zip",
    "fileName": "Arena106Setup.zip",
    "versionLabel": "1.06 (Bethesda freeware release)",
    "knownExePaths": [
      "ARENA.EXE",
      "Arena/ARENA.EXE"
    ],
    "note": "Bethesda's official freeware release, free since 2004. A DOS game — run it through DOSBox for sane speed and windowing. OpenTESArena is a modern open-source engine for it, still in development.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux",
      "macOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.392Z"
  },
  {
    "slug": "tinywind",
    "title": "TinyWind",
    "blurb": "Pixel pirate voyages with real wind — play in the browser.",
    "kind": "external",
    "url": "https://tinywind.io",
    "art": [
      "#0c4a6e",
      "#f59e0b"
    ],
    "approxSize": "Browser",
    "genres": [
      "Adventure",
      "Pirate",
      "Roguelike"
    ],
    "tags": [
      "Sailing",
      "Pixel Art",
      "Browser",
      "Roguelite",
      "Early Access"
    ],
    "launchMethods": [
      "browser"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web",
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-07-25T20:06:07.464Z",
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/tinywind-pixel-pirate-sailing-game/cover-216ae471a4189e8e.webp"
  },
  {
    "slug": "trigger-rally",
    "title": "Trigger Rally",
    "blurb": "Rally the hard way",
    "kind": "direct-zip",
    "art": [
      "#78350f",
      "#f59e0b"
    ],
    "approxSize": "~130 MB",
    "genres": [
      "Sports",
      "Simulation",
      "Action"
    ],
    "tags": [
      "Racing",
      "Rally",
      "Driving",
      "Off-Road",
      "Arcade",
      "Open Source",
      "Physics",
      "Retro",
      "Time Attack",
      "Singleplayer"
    ],
    "launchMethods": [
      "install",
      "browser"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/trigger-rally/cover-1786841896150.webp",
    "exeHint": "trigger-rally|trigger",
    "url": "https://sourceforge.net/projects/trigger-rally/files/trigger-0.6.6.1/trigger-rally-0.6.6.1-win64.zip/download",
    "fileName": "trigger-rally-0.6.6.1-win64.zip",
    "versionLabel": "v0.6.6.1",
    "note": "Standalone 64-bit Windows portable package with bundled assets and tracks.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-08-16T01:04:52.935Z"
  },
  {
    "slug": "triplea",
    "title": "TripleA",
    "blurb": "The classic board game of global conquest, rebuilt for modern strategy.",
    "kind": "external",
    "url": "https://triplea-game.org/",
    "art": [
      "#831843",
      "#f472b6"
    ],
    "approxSize": "~150 MB",
    "genres": [
      "Arcade"
    ],
    "tags": [
      "Browser",
      "Indie"
    ],
    "launchMethods": [
      "browser"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-08-14T21:30:34.430Z",
    "coverImage": "https://triplea-game.org/images/triplea_promo.png"
  },
  {
    "slug": "valorant",
    "title": "VALORANT",
    "blurb": "Precision gunplay meets game-changing abilities.",
    "kind": "external",
    "art": [
      "#881337",
      "#fda4af"
    ],
    "approxSize": "~30.0 GB",
    "genres": [
      "FPS"
    ],
    "tags": [
      "Tactical",
      "Free to Play",
      "Esports",
      "Hero Shooter"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/valorant/cover-1786824080444.webp",
    "url": "https://playvalorant.com",
    "note": "Riot Client + Vanguard required.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "PlayStation",
      "Xbox"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T08:49:19.958Z"
  },
  {
    "slug": "war-thunder",
    "title": "War Thunder",
    "blurb": "Free-to-play combined-arms combat across air, land, and sea.",
    "kind": "external",
    "art": [
      "#0c4a6e",
      "#7dd3fc"
    ],
    "approxSize": "~45.0 GB",
    "genres": [
      "Simulation",
      "Arcade"
    ],
    "tags": [
      "Vehicles",
      "Free to Play",
      "PvP",
      "Historical",
      "MMO"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/war-thunder/cover-e9ffc19c6dd1be75.webp",
    "url": "https://store.steampowered.com/app/236390/War_Thunder/",
    "note": "Steam or Gaijin launcher.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux",
      "PlayStation",
      "Xbox"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-07T08:49:19.656Z"
  },
  {
    "slug": "wolfenstein-enemy-territory",
    "title": "Wolfenstein: Enemy Territory",
    "blurb": "The definitive objective-based team shooter — 100% free since 2003.",
    "kind": "github-zip",
    "art": [
      "#450a0a",
      "#f87171"
    ],
    "approxSize": "~300 MB",
    "genres": [
      "FPS",
      "Action",
      "Strategy"
    ],
    "tags": [
      "Class-Based",
      "Objective",
      "Multiplayer",
      "Classic",
      "World War II",
      "Open Source"
    ],
    "launchMethods": [
      "install",
      "server"
    ],
    "multiplayer": true,
    "hasServerBrowser": true,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/wolfenstein-enemy-territory/cover-d4717022a54b3082.webp",
    "repo": "etlegacy/etlegacy",
    "assetPattern": "etlegacy-.*-x86_64\\.zip$|etlegacy-.*-win32\\.zip$|\\.zip$",
    "exeHint": "etl.exe",
    "versionLabel": "v2.82.1",
    "knownExePaths": [
      "etl.exe",
      "ETL.exe"
    ],
    "note": "Installs the modern ET: Legacy client with 64-bit performance, widescreen rendering, and automatic server mod/map downloading.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-15T10:45:26.904Z"
  },
  {
    "slug": "world-of-sea-battle",
    "title": "World of Sea Battle",
    "blurb": "An open-world naval MMO set in the Golden Age of Sail.",
    "kind": "direct-installer",
    "art": [
      "#0c4a6e",
      "#facc15"
    ],
    "approxSize": "~1.0 GB",
    "genres": [
      "MMO",
      "Pirate"
    ],
    "tags": [
      "Naval Combat",
      "Pirates",
      "PvP"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/world-of-sea-battle/cover-95f915e64ed5f13a.webp",
    "exeHint": "World.?of.?Sea.?Battle|xlauncher",
    "url": "https://installer.launcher.xsolla.com/xlauncher-builds/xsolla-launcher-update/786ad960-bdf8-464a-94ff-1c326c963292/bin/installer.exe",
    "fileName": "WorldOfSeaBattle-Setup.exe",
    "knownExePaths": [
      "%LOCALAPPDATA%\\Programs\\World of Sea Battle\\World of Sea Battle.exe",
      "%LOCALAPPDATA%\\XsollaLauncher\\xlauncher.exe",
      "%PROGRAMFILES%\\World of Sea Battle\\World of Sea Battle.exe"
    ],
    "registryTitles": [
      "World of Sea Battle",
      "Xsolla Launcher"
    ],
    "note": "Installs the Xsolla launcher used by World of Sea Battle.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T18:29:49.700Z"
  },
  {
    "slug": "ysoccer",
    "title": "YSoccer",
    "blurb": "Sensible Soccer spirit, made for today.",
    "kind": "direct-zip",
    "art": [
      "#15803d",
      "#84cc16"
    ],
    "approxSize": "~80 MB",
    "genres": [
      "Sports",
      "Action",
      "Simulation"
    ],
    "tags": [
      "Sports",
      "Soccer",
      "Football",
      "Retro",
      "Pixel Art",
      "Arcade",
      "Top-Down",
      "2D",
      "Open Source",
      "Controller Support",
      "Local Multiplayer"
    ],
    "launchMethods": [
      "install"
    ],
    "multiplayer": false,
    "hasServerBrowser": false,
    "isMultiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/ysoccer/shot-1786843964449.webp",
    "exeHint": "ysoccer|ysoccer19",
    "url": "https://sourceforge.net/projects/ysoccer/files/YSoccer19/ysoccer19_windows64.zip/download",
    "fileName": "ysoccer19_windows64.zip",
    "versionLabel": "v19",
    "note": "Standalone portable Windows 64-bit package with bundled runtime and team databases.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux",
      "macOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-08-16T01:34:48.461Z"
  }
];
