// Auto-generated by scripts/sync-catalog.js — do not edit by hand.
// Synced from https://playbound.club at 2026-08-09T21:44:22.543Z
// 23 game(s)

module.exports = [
  {
    "slug": "0ad",
    "title": "0 A.D.",
    "blurb": "Ancient warfare, stunningly rendered, forever free.",
    "kind": "direct-installer",
    "art": [
      "#713f12",
      "#eab308"
    ],
    "approxSize": "~3.0 GB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Historical",
      "Base Building",
      "Empire",
      "Skirmish"
    ],
    "multiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/0ad/shot-1786226577208.webp",
    "url": "https://releases.wildfiregames.com/0ad-0.28.0-win64.exe",
    "fileName": "0ad-0.28.0-win64.exe",
    "versionLabel": "0.28.0",
    "knownExePaths": [
      "%PROGRAMFILES%\\0 A.D. alpha\\binaries\\system\\pyrogenesis.exe",
      "%PROGRAMFILES(X86)%\\0 A.D. alpha\\binaries\\system\\pyrogenesis.exe",
      "%LOCALAPPDATA%\\Programs\\0 A.D. alpha\\binaries\\system\\pyrogenesis.exe",
      "%LOCALAPPDATA%\\0 A.D. alpha\\binaries\\system\\pyrogenesis.exe"
    ],
    "installRoot": "%PROGRAMFILES%\\0 A.D. alpha",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-25T19:46:51.681Z"
  },
  {
    "slug": "beyond-all-reason",
    "title": "Beyond All Reason",
    "blurb": "Thousand-unit RTS battles that melt GPUs and minds.",
    "kind": "github-installer",
    "art": [
      "#450a0a",
      "#f87171"
    ],
    "approxSize": "~2.2 GB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Large Scale",
      "Team Games",
      "Economy",
      "Competitive"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/beyond-all-reason/cover.webp",
    "repo": "beyond-all-reason/BYAR-Chobby",
    "assetPattern": "Beyond-All-Reason-.*\\.exe$",
    "knownExePaths": [
      "%LOCALAPPDATA%\\Programs\\Beyond-All-Reason\\Beyond-All-Reason.exe",
      "%LOCALAPPDATA%\\Programs\\Beyond-All-Reason\\Beyond All Reason.exe",
      "%LOCALAPPDATA%\\Programs\\Beyond All Reason\\Beyond-All-Reason.exe",
      "%LOCALAPPDATA%\\Programs\\Beyond All Reason\\Beyond All Reason.exe",
      "%PROGRAMFILES%\\Beyond-All-Reason\\Beyond-All-Reason.exe",
      "%PROGRAMFILES%\\Beyond All Reason\\Beyond All Reason.exe",
      "%PROGRAMFILES(X86)%\\Beyond-All-Reason\\Beyond-All-Reason.exe"
    ],
    "note": "Opens the BAR launcher — click Update, then Start.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-25T19:46:51.806Z"
  },
  {
    "slug": "endless-sky",
    "title": "Endless Sky",
    "blurb": "Trade, explore, and fight across a living galaxy.",
    "kind": "github-zip",
    "art": [
      "#1e1b4b",
      "#818cf8"
    ],
    "approxSize": "~450 MB",
    "genres": [
      "Space",
      "RPG",
      "Simulation"
    ],
    "tags": [
      "Space Trading",
      "Open World",
      "Story",
      "Exploration"
    ],
    "multiplayer": false,
    "coverImage": "https://playbound.club/games/endless-sky/cover.webp",
    "repo": "endless-sky/endless-sky",
    "assetPattern": "^EndlessSky-win64-.*\\.zip$",
    "exeHint": "EndlessSky",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.764Z"
  },
  {
    "slug": "everquest",
    "title": "EverQuest",
    "blurb": "Classic MMORPG — official progression and legendary private eras.",
    "kind": "external",
    "art": [
      "#0f172a",
      "#38bdf8"
    ],
    "approxSize": "~12.0 GB",
    "genres": [
      "RPG",
      "MMO"
    ],
    "tags": [
      "MMORPG",
      "Classic",
      "Fantasy",
      "PvE"
    ],
    "multiplayer": false,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/everquest/cover-1786153671785.webp",
    "url": "https://www.everquest.com",
    "note": "Prefer an edition: EverQuest Live (Daybreak LaunchPad), Project Quarm, or Project 1999.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-07T08:49:19.487Z"
  },
  {
    "slug": "hedgewars",
    "title": "Hedgewars",
    "blurb": "Turn-based hedgehog warfare. Yes, really.",
    "kind": "direct-installer",
    "art": [
      "#3f2d0c",
      "#fde047"
    ],
    "approxSize": "~180 MB",
    "genres": [
      "Strategy",
      "Arcade"
    ],
    "tags": [
      "Artillery",
      "Party",
      "Turn-Based",
      "Couch Co-op"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/hedgewars/cover.webp",
    "url": "https://www.hedgewars.org/download/releases/Hedgewars-1.0.0.exe",
    "knownExePaths": [
      "%PROGRAMFILES%\\Hedgewars\\hedgewars.exe",
      "%PROGRAMFILES(X86)%\\Hedgewars\\hedgewars.exe",
      "%LOCALAPPDATA%\\Programs\\Hedgewars\\hedgewars.exe"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.927Z"
  },
  {
    "slug": "luanti",
    "title": "Luanti",
    "blurb": "An infinite voxel sandbox — and an engine for a thousand games.",
    "kind": "github-zip",
    "art": [
      "#14532d",
      "#a3e635"
    ],
    "approxSize": "~150 MB",
    "genres": [
      "Sandbox",
      "Simulation"
    ],
    "tags": [
      "Voxel",
      "Building",
      "Survival",
      "Game Platform"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/luanti/cover.webp",
    "repo": "luanti-org/luanti",
    "assetPattern": "-win64\\.zip$",
    "exeHint": "luanti|minetest",
    "connectArgs": [
      "--go",
      "--address",
      "{host}",
      "--port",
      "{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Android"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.826Z"
  },
  {
    "slug": "mega-man-unlimited",
    "title": "Mega Man Unlimited",
    "blurb": "A fan-made Mega Man in the spirit of the NES originals.",
    "kind": "direct-zip",
    "art": [
      "#0c4a6e",
      "#38bdf8"
    ],
    "approxSize": "~98 MB",
    "genres": [
      "Platformer"
    ],
    "tags": [
      "Fan Game",
      "Retro",
      "Precision Platformer",
      "Single Player"
    ],
    "multiplayer": false,
    "coverImage": "https://megaphilx.com/wp-content/uploads/2018/08/MMUTitle.png",
    "url": "https://megaphilx.com/Game/MegaManUnlimitedV131.zip",
    "fileName": "MegaManUnlimitedV131.zip",
    "versionLabel": "1.3.1",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-08-06T20:27:47.260Z"
  },
  {
    "slug": "mindustry",
    "title": "Mindustry",
    "blurb": "Factory-building tower defense with serious depth.",
    "kind": "github-jar",
    "art": [
      "#3f1d0b",
      "#fb923c"
    ],
    "approxSize": "~250 MB",
    "genres": [
      "Tower Defense",
      "Strategy",
      "Sandbox"
    ],
    "tags": [
      "Automation",
      "Factory",
      "Co-op",
      "Waves"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/mindustry/cover.webp",
    "repo": "Anuken/Mindustry",
    "assetPattern": "^Mindustry\\.jar$",
    "note": "Requires Java 17+ (Adoptium Temurin).",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Android",
      "iOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.723Z"
  },
  {
    "slug": "naev",
    "title": "Naev",
    "blurb": "A 2D galaxy of freedom, factions, and consequences.",
    "kind": "github-installer",
    "art": [
      "#0f172a",
      "#38bdf8"
    ],
    "approxSize": "~400 MB",
    "genres": [
      "Space",
      "RPG"
    ],
    "tags": [
      "Open World",
      "Factions",
      "Trading",
      "Story"
    ],
    "multiplayer": false,
    "coverImage": "https://playbound.club/games/naev/cover.webp",
    "repo": "naev/naev",
    "assetPattern": "win64\\.exe$",
    "knownExePaths": [
      "%PROGRAMFILES%\\Naev\\naev.exe",
      "%PROGRAMFILES(X86)%\\Naev\\naev.exe",
      "%PROGRAMFILES%\\naev\\naev.exe",
      "%LOCALAPPDATA%\\Programs\\naev\\naev.exe",
      "%LOCALAPPDATA%\\Programs\\Naev\\naev.exe"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.907Z"
  },
  {
    "slug": "next-gen-chess",
    "title": "Next-Gen Chess",
    "blurb": "Chess that teaches you while you play.",
    "kind": "external",
    "url": "https://ngchess.com",
    "art": [
      "#831843",
      "#f472b6"
    ],
    "approxSize": "Browser",
    "genres": [
      "Strategy"
    ],
    "tags": [
      "Browser",
      "Indie"
    ],
    "multiplayer": false,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-08-03T17:05:12.686Z",
    "coverImage": "https://ngchess.com/img/og-card.png?v=2026-06-28"
  },
  {
    "slug": "openra",
    "title": "OpenRA",
    "blurb": "Classic real-time strategy, rebuilt for the modern age.",
    "kind": "github-zip",
    "art": [
      "#7f1d1d",
      "#f59e0b"
    ],
    "approxSize": "~350 MB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Classic",
      "Base Building",
      "Ranked",
      "Mods",
      "LAN"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/openra/cover.webp",
    "repo": "OpenRA/OpenRA",
    "assetPattern": "x64-winportable\\.zip$",
    "exeHint": "RedAlert|OpenRA",
    "connectArgs": [
      "Game.Connect={host}:{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.588Z"
  },
  {
    "slug": "openttd",
    "title": "OpenTTD",
    "blurb": "Build a transport empire, one rail at a time.",
    "kind": "openttd-zip",
    "art": [
      "#164e63",
      "#67e8f9"
    ],
    "approxSize": "~200 MB",
    "genres": [
      "Simulation",
      "Strategy"
    ],
    "tags": [
      "Trains",
      "Logistics",
      "Management",
      "Sandbox"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/openttd/cover.webp",
    "exeHint": "openttd",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.744Z"
  },
  {
    "slug": "shattered-pixel-dungeon",
    "title": "Shattered Pixel Dungeon",
    "blurb": "The roguelike that respects your time and ruins your evening.",
    "kind": "github-zip",
    "art": [
      "#3b0764",
      "#e879f9"
    ],
    "approxSize": "~60 MB",
    "genres": [
      "Roguelike",
      "RPG"
    ],
    "tags": [
      "Permadeath",
      "Turn-Based",
      "Pixel Art",
      "Runs"
    ],
    "multiplayer": false,
    "coverImage": "https://playbound.club/games/shattered-pixel-dungeon/cover.webp",
    "repo": "00-Evan/shattered-pixel-dungeon",
    "assetPattern": "Windows\\.zip$",
    "exeHint": "ShatteredPD|Shattered",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Android",
      "iOS"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.785Z"
  },
  {
    "slug": "supertux",
    "title": "SuperTux",
    "blurb": "Run, jump, and slide through a frosty platforming classic.",
    "kind": "github-zip",
    "art": [
      "#0c4a6e",
      "#e0f2fe"
    ],
    "approxSize": "~250 MB",
    "genres": [
      "Platformer",
      "Arcade"
    ],
    "tags": [
      "2D",
      "Family Friendly",
      "Level Editor",
      "Classic"
    ],
    "multiplayer": false,
    "coverImage": "https://playbound.club/games/supertux/cover.webp",
    "repo": "SuperTux/supertux",
    "assetPattern": "win64-portable\\.zip$",
    "exeHint": "supertux",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.866Z"
  },
  {
    "slug": "supertuxkart",
    "title": "SuperTuxKart",
    "blurb": "Kart racing chaos for the whole couch.",
    "kind": "github-zip",
    "art": [
      "#14532d",
      "#4ade80"
    ],
    "approxSize": "~900 MB",
    "genres": [
      "Racing",
      "Arcade"
    ],
    "tags": [
      "Kart Racing",
      "Split-Screen",
      "Family Friendly",
      "Party"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/supertuxkart/cover.webp",
    "repo": "supertuxkart/stk-code",
    "assetPattern": "-win\\.zip$",
    "exeHint": "supertuxkart",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux",
      "Android"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.660Z"
  },
  {
    "slug": "battle-for-wesnoth",
    "title": "The Battle for Wesnoth",
    "blurb": "A legendary open-source fantasy strategy epic.",
    "kind": "direct-installer",
    "art": [
      "#312e81",
      "#a78bfa"
    ],
    "approxSize": "~700 MB",
    "genres": [
      "Strategy",
      "RPG"
    ],
    "tags": [
      "Turn-Based",
      "Fantasy",
      "Campaigns",
      "Hotseat"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/battle-for-wesnoth/cover.webp",
    "url": "https://sourceforge.net/projects/wesnoth/files/wesnoth-1.18/wesnoth-1.18.7/wesnoth-1.18.7-win64.exe/download",
    "fileName": "wesnoth-1.18.7-win64.exe",
    "versionLabel": "1.18.7",
    "knownExePaths": [
      "%PROGRAMFILES%\\Battle for Wesnoth 1.18\\wesnoth.exe",
      "%PROGRAMFILES(X86)%\\Battle for Wesnoth 1.18\\wesnoth.exe",
      "%LOCALAPPDATA%\\Programs\\Battle for Wesnoth 1.18\\wesnoth.exe",
      "%LOCALAPPDATA%\\Programs\\Battle for Wesnoth\\wesnoth.exe"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.639Z"
  },
  {
    "slug": "tinywind-pixel-pirate-sailing-game",
    "title": "Tinywind — Pixel Pirate Sailing Game",
    "blurb": "Outsail the Royal Navy in your browser. Real sailing physics, 5-minute voyages, 30 historical treasures to recover. Free to play.",
    "kind": "external",
    "url": "https://tinywind.io/",
    "art": [
      "#831843",
      "#f472b6"
    ],
    "approxSize": "Browser",
    "genres": [],
    "tags": [
      "Browser",
      "Indie"
    ],
    "multiplayer": false,
    "status": "published",
    "testing": false,
    "platforms": [
      "Web"
    ],
    "browserPlayable": true,
    "steamDeck": false,
    "createdAt": "2026-07-25T20:06:07.464Z",
    "coverImage": "https://tinywind.io/opengraph-image?ca63dcafdaa67b1f"
  },
  {
    "slug": "unvanquished",
    "title": "Unvanquished",
    "blurb": "Aliens vs humans in asymmetric FPS-strategy warfare.",
    "kind": "github-zip",
    "art": [
      "#052e16",
      "#86efac"
    ],
    "approxSize": "~850 MB",
    "genres": [
      "FPS",
      "Strategy"
    ],
    "tags": [
      "Asymmetric",
      "Team-Based",
      "Base Building",
      "Sci-Fi"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/unvanquished/cover.webp",
    "repo": "Unvanquished/updater",
    "assetPattern": "UnvUpdaterWin\\.zip$",
    "exeHint": "UnvanquishedUpdater|updater",
    "connectArgs": [
      "+connect",
      "{host}:{port}"
    ],
    "note": "Installs the Unvanquished updater, which downloads the game.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-25T19:46:51.947Z"
  },
  {
    "slug": "veloren",
    "title": "Veloren",
    "blurb": "A voxel world of dragons, dungeons, and endless horizons.",
    "kind": "direct-installer",
    "art": [
      "#1e3a5f",
      "#34d399"
    ],
    "approxSize": "~1.6 GB",
    "genres": [
      "RPG",
      "Sandbox"
    ],
    "tags": [
      "Voxel",
      "Open World",
      "Co-op",
      "Exploration"
    ],
    "multiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/veloren/shot-1786223625836.webp",
    "exeHint": "airshipper",
    "url": "https://gitlab.com/veloren/airshipper/-/releases/v0.17.0/downloads/binaries/windows-installer-x86_64",
    "fileName": "airshipper-installer.exe",
    "versionLabel": "0.17.0",
    "knownExePaths": [
      "%LOCALAPPDATA%\\Programs\\Airshipper\\airshipper.exe",
      "%LOCALAPPDATA%\\airshipper\\airshipper.exe",
      "%PROGRAMFILES%\\Airshipper\\airshipper.exe",
      "%PROGRAMFILES(X86)%\\Airshipper\\airshipper.exe"
    ],
    "registryTitles": [
      "Airshipper",
      "Veloren"
    ],
    "note": "Installs Airshipper, which downloads and updates Veloren.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.703Z"
  },
  {
    "slug": "warframe",
    "title": "Warframe",
    "blurb": "Awaken as an unstoppable warrior and battle alongside your friends in this story-driven free-to-play online action game",
    "kind": "direct-installer",
    "art": [
      "#3b0764",
      "#e879f9"
    ],
    "approxSize": "~101 MB",
    "genres": [
      "FPS"
    ],
    "tags": [
      "Action",
      "RPG",
      "Free To Play"
    ],
    "multiplayer": false,
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/230410/a000b4bf98dde5d51cd44206f1ac21d04841017e/header.jpg?t=1785169127",
    "url": "https://content.warframe.com/dl/Warframe.msi",
    "fileName": "Warframe.msi",
    "note": "Auto-discovered installer download",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-27T22:42:00.383Z"
  },
  {
    "slug": "warzone-2100",
    "title": "Warzone 2100",
    "blurb": "Design your own tanks. Then design better ones.",
    "kind": "github-zip",
    "art": [
      "#422006",
      "#fbbf24"
    ],
    "approxSize": "~550 MB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Unit Design",
      "Campaign",
      "Post-Apocalyptic",
      "Classic"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/warzone-2100/cover.webp",
    "repo": "Warzone2100/warzone2100",
    "assetPattern": "win_x64_archive\\.zip$",
    "exeHint": "warzone2100",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.846Z"
  },
  {
    "slug": "xonotic",
    "title": "Xonotic",
    "blurb": "The fastest arena shooter on the planet. Completely free.",
    "kind": "direct-zip",
    "art": [
      "#0c4a6e",
      "#22d3ee"
    ],
    "approxSize": "~1.1 GB",
    "genres": [
      "FPS",
      "Arcade"
    ],
    "tags": [
      "Arena Shooter",
      "Competitive",
      "Movement",
      "Duels"
    ],
    "multiplayer": true,
    "coverImage": "https://playbound.club/games/xonotic/cover.webp",
    "exeHint": "xonotic.*x64|xonotic",
    "url": "https://dl.xonotic.org/xonotic-0.8.6.zip",
    "connectArgs": [
      "+connect",
      "{host}:{port}"
    ],
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": true,
    "createdAt": "2026-07-25T19:46:51.618Z"
  },
  {
    "slug": "zero-k",
    "title": "Zero-K",
    "blurb": "Physics-driven RTS where terrain is a weapon.",
    "kind": "direct-exe",
    "art": [
      "#111827",
      "#94a3b8"
    ],
    "approxSize": "~1.3 GB",
    "genres": [
      "RTS",
      "Strategy"
    ],
    "tags": [
      "Physics",
      "Terraforming",
      "Co-op",
      "Competitive"
    ],
    "multiplayer": true,
    "coverImage": "https://mt8u2b96lweefbpb.public.blob.vercel-storage.com/games/zero-k/cover-ae7a710dcadabbe7.webp",
    "url": "https://zero-k.info/lobby/Zero-K.exe",
    "note": "Downloads the Zero-K lobby, which fetches the game on first run.",
    "status": "published",
    "testing": false,
    "platforms": [
      "Windows",
      "Linux"
    ],
    "browserPlayable": false,
    "steamDeck": false,
    "createdAt": "2026-07-25T19:46:51.887Z"
  }
];
