const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("playbound", {
  platform: {
    getOS: () => (process.platform === "win32" ? "windows" : process.platform === "darwin" ? "macos" : "linux"),
    getOSVersion: () => process.getSystemVersion(),
    getArchitecture: () => process.arch,
    supportsDesktopShortcuts: () => process.platform === "win32",
    supportsDock: () => process.platform === "darwin",
  },
  // Existing
  getContext: () => ipcRenderer.invoke("get-context"),
  chooseDirectory: (defaultPath) => ipcRenderer.invoke("choose-directory", defaultPath),
  install: (slug, targetDir, editionSlug, addons) =>
    ipcRenderer.invoke("install", slug, targetDir, editionSlug || null, addons),
  installMod: (slug, baseDir) => ipcRenderer.invoke("install-mod", slug, baseDir || null),
  locateExe: (slug) => ipcRenderer.invoke("locate-exe", slug),
  dismissPendingInstall: (slug) => ipcRenderer.invoke("dismiss-pending-install", slug),
  play: (slug, join, editionSlug) =>
    ipcRenderer.invoke("play", slug, join || null, editionSlug || null),
  playMod: (slug) => ipcRenderer.invoke("play-mod", slug),
  postTelemetry: (payload) => ipcRenderer.invoke("post-telemetry", payload),
  uninstall: (slug, editionSlug) => ipcRenderer.invoke("uninstall", slug, editionSlug || null),
  getInstalled: () => ipcRenderer.invoke("get-installed"),
  getInstalledMods: () => ipcRenderer.invoke("get-installed-mods"),
  uninstallMod: (slug) => ipcRenderer.invoke("uninstall-mod", slug),
  createShortcut: (slug) => ipcRenderer.invoke("create-shortcut", slug),
  openFolder: (dir) => ipcRenderer.invoke("open-folder", dir),
  clearContext: () => ipcRenderer.invoke("clear-context"),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  openDeepLink: (url) => ipcRenderer.invoke("open-deep-link", url),
  closeWindow: () => ipcRenderer.invoke("close-window"),
  clipboardWrite: (text) => ipcRenderer.invoke("clipboard-write", text),
  getAccount: () => ipcRenderer.invoke("get-account"),
  setLauncherToken: (token) => ipcRenderer.invoke("set-launcher-token", token),
  clearLauncherToken: () => ipcRenderer.invoke("clear-launcher-token"),
  signIn: () => ipcRenderer.invoke("sign-in"),
  syncLibraryNow: () => ipcRenderer.invoke("sync-library-now"),
  reportBug: (payload) => ipcRenderer.invoke("report-bug", payload || {}),

  // Friends API
  getFriends: () => ipcRenderer.invoke("get-friends"),
  getFriendRequests: () => ipcRenderer.invoke("get-friend-requests"),
  acceptFriendRequest: (requestId) => ipcRenderer.invoke("accept-friend-request", requestId),
  declineFriendRequest: (requestId) => ipcRenderer.invoke("decline-friend-request", requestId),
  removeFriend: (friendId) => ipcRenderer.invoke("remove-friend", friendId),
  searchUsers: (query) => ipcRenderer.invoke("search-users", query),
  discoverPlayers: (params) => ipcRenderer.invoke("discover-players", params),
  sendFriendRequest: (targetUserId) => ipcRenderer.invoke("send-friend-request", targetUserId),
  // Catalog / servers / mods
  getCatalog: () => ipcRenderer.invoke("get-catalog"),
  getServers: (slug) => ipcRenderer.invoke("get-servers", slug),
  getAllServers: () => ipcRenderer.invoke("get-all-servers"),
  getServerIndex: () => ipcRenderer.invoke("get-server-index"),
  getModsCatalog: () => ipcRenderer.invoke("get-mods-catalog"),
  getEvents: () => ipcRenderer.invoke("get-events"),
  pingHosts: (hosts) => ipcRenderer.invoke("ping-hosts", hosts),
  getSettings: () => ipcRenderer.invoke("get-settings"),
  saveSettings: (patch) => ipcRenderer.invoke("save-settings", patch),
  getRecentlyPlayed: () => ipcRenderer.invoke("get-recently-played"),
  getGameDetail: (slug) => ipcRenderer.invoke("get-game-detail", slug),
  getModDetail: (slug) => ipcRenderer.invoke("get-mod-detail", slug),
  getLiveStats: (opts) => ipcRenderer.invoke("get-live-stats", opts || {}),
  getEditions: (gameSlug) => ipcRenderer.invoke("get-editions", gameSlug || null),
  getGameGuides: (slug) => ipcRenderer.invoke("get-game-guides", slug),
  getModGuides: (slug) => ipcRenderer.invoke("get-mod-guides", slug),
  getGameReleases: (slug) => ipcRenderer.invoke("get-game-releases", slug),
  getAppVersion: () => ipcRenderer.invoke("get-app-version"),
  checkForUpdates: () => ipcRenderer.invoke("check-for-updates"),
  installUpdate: () => ipcRenderer.invoke("install-update"),

  // Events
  onContext: (cb) => ipcRenderer.on("context", (_event, data) => cb(data)),
  onProgress: (cb) => ipcRenderer.on("progress", (_event, data) => cb(data)),
  onAccount: (cb) => ipcRenderer.on("account", (_event, data) => cb(data || {})),
  onInstallDetected: (cb) => ipcRenderer.on("install-detected", (_event, data) => cb(data || {})),
  onInstallDetectFailed: (cb) =>
    ipcRenderer.on("install-detect-failed", (_event, data) => cb(data || {})),
  onInstallScan: (cb) => ipcRenderer.on("install-scan", (_event, data) => cb(data || {})),
  onModInstallFinished: (cb) =>
    ipcRenderer.on("mod-install-finished", (_event, data) => cb(data || {})),
  onUpdateStatus: (cb) => ipcRenderer.on("update-status", (_event, data) => cb(data || {})),
  onGameExited: (cb) => ipcRenderer.on("game-exited", (_event, data) => cb(data || {})),
});
