import { NextResponse } from "next/server";
import dbConnect from "@/lib/db";
import { requireAdminSession } from "@/lib/requireAdmin";
import CommunityHostingConfig from "@/lib/models/CommunityHostingConfig";
import CommunityServer from "@/lib/models/CommunityServer";
import CommunityHostingLease from "@/lib/models/CommunityHostingLease";
import BugReport from "@/lib/models/BugReport";
import Edition from "@/lib/models/Edition";
import { editions as seedEditions } from "@/lib/data/editions";
import { fetchGameHostMetrics, listManagedHostRooms } from "@/lib/gameHost/client";
import { reconcileCommunityHosting } from "@/lib/communityHosting/reconcile";

export type CommunityServerAlert = {
  id: string;
  level: "critical" | "warning" | "info";
  title: string;
  detail: string;
  serverSlug?: string;
  serverName?: string;
  gameSlug?: string;
  editionSlug?: string | null;
  code?: string;
  actionable?: "reconcile" | "retry" | "vps" | "config" | "bugs";
};

export async function GET() {
  const { error } = await requireAdminSession();
  if (error) return error;

  await dbConnect();

  const [configDoc, serversDoc, metricsRes, agentRes, bugsDoc, leaseDoc, dbEditions] = await Promise.all([
    CommunityHostingConfig.findOne({ key: "global" }).lean(),
    CommunityServer.find({}).sort({ updatedAt: -1 }).limit(100).lean(),
    fetchGameHostMetrics(),
    listManagedHostRooms(),
    BugReport.find({
      status: { $in: ["open", "reviewing"] },
      autoGenerated: true,
      $or: [
        { errorCode: { $regex: /^community_server_/ } },
        { title: { $regex: /\[community_server_/ } },
        { fingerprint: { $regex: /^community_server_/ } },
        { phase: "reconcile" },
        { phase: "reconcile_cron" },
      ],
    })
      .select({ _id: 1, title: 1, errorCode: 1, gameSlug: 1, editionSlug: 1, occurrenceCount: 1, lastSeenAt: 1, status: 1 })
      .sort({ lastSeenAt: -1 })
      .limit(50)
      .lean(),
    CommunityHostingLease.findOne({ key: "fleet" }).lean(),
    Edition.find({
      status: { $ne: "archived" },
      visibility: { $ne: "hidden" },
    }).select({ gameSlug: 1, slug: 1, name: 1, suppressesSeed: 1 }).lean(),
  ]);

  const config = configDoc || new CommunityHostingConfig({ key: "global" }).toObject();

  // Build edition display names map
  const editionNames: Record<string, string> = {};
  const suppressedSeedSlugs = new Set(
    dbEditions.filter((e) => (e as unknown as { suppressesSeed?: boolean }).suppressesSeed).map((e) => `${e.gameSlug}:${e.slug}`)
  );
  for (const e of dbEditions) {
    if (!(e as unknown as { suppressesSeed?: boolean }).suppressesSeed) {
      editionNames[`${e.gameSlug}:${e.slug}`] = e.name;
    }
  }
  for (const s of seedEditions) {
    const k = `${s.gameSlug}:${s.slug}`;
    if (!editionNames[k] && !suppressedSeedSlugs.has(k)) {
      editionNames[k] = s.name;
    }
  }

  const alerts: CommunityServerAlert[] = [];

  // 1. VPS Agent and Host Reachability
  if (!metricsRes.ok) {
    if ("outdatedAgent" in metricsRes && metricsRes.outdatedAgent) {
      alerts.push({
        id: "agent-outdated",
        level: "critical",
        title: "Game-Host Agent Outdated",
        detail: metricsRes.error,
        actionable: "vps",
      });
    } else {
      alerts.push({
        id: "agent-unreachable",
        level: "critical",
        title: "Game-Host Agent Unreachable",
        detail: metricsRes.error || "Unable to reach VPS daemon for community hosting.",
        actionable: "vps",
      });
    }
  } else {
    // 2. Resource threshold checks (CPU, RAM, Disk, Metrics freshness)
    const metrics = metricsRes.metrics;
    if (metrics.cpu?.usagePercent != null) {
      const maxCpu = config.safety?.maxCpuPercent ?? 80;
      if (metrics.cpu.usagePercent >= maxCpu) {
        alerts.push({
          id: "cpu-critical",
          level: "critical",
          title: `VPS CPU Usage Critical (${metrics.cpu.usagePercent}%)`,
          detail: `CPU load exceeds the ${maxCpu}% safety limit. Automated provisioning will be blocked until load decreases.`,
          actionable: "vps",
        });
      } else if (metrics.cpu.usagePercent >= maxCpu - 10) {
        alerts.push({
          id: "cpu-warning",
          level: "warning",
          title: `VPS CPU Usage Elevated (${metrics.cpu.usagePercent}%)`,
          detail: `CPU load is approaching the ${maxCpu}% safety ceiling.`,
          actionable: "vps",
        });
      }
    }

    if (metrics.memory?.freeBytes != null) {
      const minFreeRam = config.safety?.minFreeRamBytes ?? (2 * 1024 ** 3);
      if (metrics.memory.freeBytes < minFreeRam) {
        const freeGb = (metrics.memory.freeBytes / (1024 ** 3)).toFixed(2);
        const minGb = (minFreeRam / (1024 ** 3)).toFixed(2);
        alerts.push({
          id: "ram-critical",
          level: "critical",
          title: `VPS Free RAM Below Safety Floor (${freeGb} GB)`,
          detail: `Free RAM is below the minimum required limit (${minGb} GB). Automatic server launches are paused to protect running games.`,
          actionable: "vps",
        });
      }
    }

    if (metrics.collectedAt) {
      const ageSec = Math.round((Date.now() - new Date(metrics.collectedAt).getTime()) / 1000);
      const maxAge = config.safety?.maxMetricsAgeSeconds ?? 120;
      if (ageSec > maxAge) {
        alerts.push({
          id: "metrics-stale",
          level: "warning",
          title: `VPS Telemetry Stale (${ageSec}s old)`,
          detail: `Last metric report is older than safety threshold (${maxAge}s). Reconciliation will wait for fresh metrics before starting rooms.`,
          actionable: "vps",
        });
      }
    }

    if (metrics.storage && Array.isArray(metrics.storage)) {
      const diskCrit = config.monitoring?.diskCriticalPercent ?? 90;
      const diskWarn = config.monitoring?.diskWarningPercent ?? 75;
      for (const disk of metrics.storage) {
        if (disk.usedPercent >= diskCrit) {
          alerts.push({
            id: `disk-critical-${disk.path}`,
            level: "critical",
            title: `VPS Disk Critical: ${disk.path} (${disk.usedPercent}%)`,
            detail: `Disk usage on ${disk.path} is critically full. Server game installations or logs may fail.`,
            actionable: "vps",
          });
        } else if (disk.usedPercent >= diskWarn) {
          alerts.push({
            id: `disk-warning-${disk.path}`,
            level: "warning",
            title: `VPS Disk Warning: ${disk.path} (${disk.usedPercent}%)`,
            detail: `Disk usage on ${disk.path} has reached ${disk.usedPercent}%.`,
            actionable: "vps",
          });
        }
      }
    }
  }

  // 3. Node Configuration State
  if (!config.enabled) {
    alerts.push({
      id: "automation-disabled",
      level: "info",
      title: "Automated Community Hosting is Disabled",
      detail: "Automatic rotation and scheduled server starts are currently turned off in configuration.",
      actionable: "config",
    });
  } else if (!config.node?.enabled) {
    alerts.push({
      id: "node-disabled",
      level: "warning",
      title: `Node '${config.node?.regionLabel || config.node?.regionKey || "VPS"}' is Disabled`,
      detail: "Hosting node is disabled while automation is enabled.",
      actionable: "config",
    });
  } else if (config.node?.draining) {
    alerts.push({
      id: "node-draining",
      level: "warning",
      title: `Node '${config.node?.regionLabel || config.node?.regionKey || "VPS"}' is Draining`,
      detail: "Draining mode is active. Existing servers stay up, but no new community servers will rotate in.",
      actionable: "config",
    });
  }

  // 4. Server-level failures and problem states
  let runningCount = 0;
  let pendingCount = 0;
  let failedCount = 0;
  let exhaustedCount = 0;

  const formattedServers = serversDoc.map((s) => {
    const isFailed = s.runtimeState === "failed";
    const isUnhealthy = s.health === "unhealthy";
    const isExhausted = (s.recoveryAttempts ?? 0) >= 3;
    const isCapacityBlocked = s.decisionReason === "INSUFFICIENT_CAPACITY" || s.decisionReason === "NO_HEALTHY_NODE";

    if (s.runtimeState === "running") runningCount++;
    if (s.runtimeState === "pending") pendingCount++;
    if (isFailed) failedCount++;
    if (isExhausted) exhaustedCount++;

    const editionKey = s.editionSlug ? `${s.gameSlug}:${s.editionSlug}` : null;
    const editionName = editionKey ? editionNames[editionKey] || s.editionSlug : null;

    if (isExhausted) {
      alerts.push({
        id: `server-exhausted-${s._id}`,
        level: "critical",
        title: `Recovery Exhausted: ${s.name} (${editionName ? `${s.gameSlug} · ${editionName}` : s.gameSlug})`,
        detail: `Server failed ${s.recoveryAttempts}/3 recovery attempts (${s.decisionReason || "runtime crashed"}). Automatic retries stopped to prevent crash loops.`,
        serverSlug: s.slug,
        serverName: s.name,
        gameSlug: s.gameSlug,
        editionSlug: s.editionSlug,
        actionable: "retry",
      });
    } else if (isFailed) {
      alerts.push({
        id: `server-failed-${s._id}`,
        level: "critical",
        title: `Server Runtime Failed: ${s.name} (${editionName ? `${s.gameSlug} · ${editionName}` : s.gameSlug})`,
        detail: s.decisionReason || "Server reported failed runtime status on the host node.",
        serverSlug: s.slug,
        serverName: s.name,
        gameSlug: s.gameSlug,
        editionSlug: s.editionSlug,
        actionable: "reconcile",
      });
    } else if (isUnhealthy) {
      alerts.push({
        id: `server-unhealthy-${s._id}`,
        level: "warning",
        title: `Server Unhealthy: ${s.name} (${editionName ? `${s.gameSlug} · ${editionName}` : s.gameSlug})`,
        detail: `Process running on port ${s.port || "unknown"} is failing health queries.`,
        serverSlug: s.slug,
        serverName: s.name,
        gameSlug: s.gameSlug,
        editionSlug: s.editionSlug,
        actionable: "vps",
      });
    } else if (isCapacityBlocked) {
      alerts.push({
        id: `server-capacity-${s._id}`,
        level: "warning",
        title: `Server Capacity Deferred: ${s.name} (${editionName ? `${s.gameSlug} · ${editionName}` : s.gameSlug})`,
        detail: `Reconcile decision: ${s.decisionReason}. Waiting for available CPU/RAM budget.`,
        serverSlug: s.slug,
        serverName: s.name,
        gameSlug: s.gameSlug,
        editionSlug: s.editionSlug,
        actionable: "config",
      });
    }

    return {
      _id: String(s._id),
      slug: s.slug,
      name: s.name,
      gameSlug: s.gameSlug,
      editionSlug: s.editionSlug,
      editionName,
      desiredState: s.desiredState,
      runtimeState: s.runtimeState,
      health: s.health,
      host: s.host,
      port: s.port,
      playerCount: s.playerCount,
      recoveryAttempts: s.recoveryAttempts ?? 0,
      nextRecoveryAt: s.nextRecoveryAt ? s.nextRecoveryAt.toISOString() : null,
      decisionReason: s.decisionReason,
      lastReconciledAt: s.lastReconciledAt ? s.lastReconciledAt.toISOString() : null,
      updatedAt: s.updatedAt ? s.updatedAt.toISOString() : null,
    };
  });

  // 5. Bug report alert
  if (bugsDoc.length > 0) {
    alerts.push({
      id: "open-bugs-detected",
      level: "warning",
      title: `${bugsDoc.length} Open Community Server Bug Report(s)`,
      detail: "Automated server failure tickets exist in the Bugs tracker.",
      actionable: "bugs",
    });
  }

  // 6. Reconciliation freshness / lease check
  const leaseUntil = leaseDoc?.leaseUntil ? new Date(leaseDoc.leaseUntil).getTime() : 0;
  const isLeaseActive = leaseUntil > Date.now();

  return NextResponse.json({
    ok: true,
    alerts,
    stats: {
      total: serversDoc.length,
      running: runningCount,
      pending: pendingCount,
      failed: failedCount,
      exhausted: exhaustedCount,
      openBugsCount: bugsDoc.length,
    },
    node: {
      configured: true,
      agentReachable: metricsRes.ok,
      agentError: metricsRes.ok ? null : metricsRes.error,
      nodeEnabled: config.node?.enabled ?? false,
      draining: config.node?.draining ?? false,
      regionLabel: config.node?.regionLabel || config.node?.regionKey || "VPS",
      autoHostingEnabled: config.enabled ?? false,
      metrics: metricsRes.ok ? metricsRes.metrics : null,
      activeRoomsOnAgent: agentRes.ok && agentRes.rooms ? agentRes.rooms.length : 0,
    },
    safety: config.safety,
    budget: config.budget,
    servers: formattedServers,
    openBugs: bugsDoc.map((b) => ({
      _id: String(b._id),
      title: b.title,
      errorCode: b.errorCode,
      gameSlug: b.gameSlug,
      editionSlug: b.editionSlug,
      occurrenceCount: b.occurrenceCount || 1,
      lastSeenAt: b.lastSeenAt ? b.lastSeenAt.toISOString() : null,
    })),
    lease: {
      active: isLeaseActive,
      leaseUntil: leaseDoc?.leaseUntil ? leaseDoc.leaseUntil.toISOString() : null,
      updatedAt: leaseDoc?.updatedAt ? leaseDoc.updatedAt.toISOString() : null,
    },
  });
}

export async function POST(req: Request) {
  const { error } = await requireAdminSession();
  if (error) return error;

  await dbConnect();

  try {
    const body = (await req.json().catch(() => ({}))) as {
      action?: string;
      serverId?: string;
    };

    if (body.action === "reconcile") {
      const result = await reconcileCommunityHosting();
      return NextResponse.json({ ok: true, result });
    }

    if (body.action === "resetRecovery" && body.serverId) {
      await CommunityServer.updateOne(
        { _id: body.serverId },
        {
          $set: {
            recoveryAttempts: 0,
            nextRecoveryAt: null,
            decisionReason: "RECOVERY_RESET_BY_ADMIN",
            runtimeState: "stopped",
          },
        }
      );
      return NextResponse.json({ ok: true });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Action failed" },
      { status: 500 }
    );
  }
}
