// Auto-generated by scripts/sync-cadence.js — do not edit by hand.
// Canonical source: platform/src/lib/realtime/cadence.json
// Edit there; both the website and this launcher read the same numbers.

module.exports = {
  "notificationPollMs": 10000,
  "friendsPollMs": 5000,
  "livePartyPollMs": 3000,
  "partyChatPollMs": 2500,
  "discoverablePartiesMinMs": 8000,
  "upcomingEventsTtlMs": 60000,
  "couchSignalActiveMs": 500,
  "couchSignalIdleMs": 2000,
  "couchSignalIdleAfterEmptyPolls": 6
};
