import Link from "next/link";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth/next";
import { ArrowLeft, Bug } from "lucide-react";
import { authOptions } from "@/lib/auth";
import dbConnect from "@/lib/db";
import BugReport from "@/lib/models/BugReport";
import { BUG_REPORT_STATUS_LABELS, type BugReportStatus } from "@/lib/bugReports";
import { BugReportActions } from "@/components/admin/BugReportActions";
import { LocalTime } from "@/components/LocalTime";

export const metadata: Metadata = { title: "Bug reports" };

export default async function AdminBugsPage({
  searchParams,
}: {
  searchParams: Promise<{ filter?: string }>;
}) {
  const session = await getServerSession(authOptions);
  if (session?.user?.role !== "admin") redirect("/");

  const sp = await searchParams;
  const currentFilter = sp.filter === "resolved" ? "resolved" : sp.filter === "all" ? "all" : "active";

  let items: {
    _id: { toString(): string };
    title: string;
    description: string;
    source: "website" | "launcher";
    pageUrl?: string | null;
    contactEmail?: string | null;
    submitterName?: string | null;
    launcherVersion?: string | null;
    platform?: string | null;
    status: BugReportStatus;
    adminNotes?: string | null;
    createdAt: Date;
    autoGenerated?: boolean;
    errorCode?: string | null;
    gameSlug?: string | null;
    occurrenceCount?: number;
    lastSeenAt?: Date | null;
  }[] = [];

  let activeCount = 0;
  let resolvedCount = 0;
  let totalCount = 0;
  let autoCount = 0;

  try {
    await dbConnect();

    const [active, resolved, total, auto] = await Promise.all([
      BugReport.countDocuments({ status: { $ne: "resolved" } }),
      BugReport.countDocuments({ status: "resolved" }),
      BugReport.countDocuments(),
      BugReport.countDocuments({ autoGenerated: true, status: { $ne: "resolved" } }),
    ]);

    activeCount = active;
    resolvedCount = resolved;
    totalCount = total;
    autoCount = auto;

    const mongoFilter =
      currentFilter === "resolved"
        ? { status: "resolved" }
        : currentFilter === "all"
        ? {}
        : { status: { $ne: "resolved" } };

    items = await BugReport.find(mongoFilter)
      .sort({ lastSeenAt: -1, createdAt: -1 })
      .limit(200)
      .lean();
  } catch (err) {
    console.error("Failed to load bug reports:", err);
  }

  return (
    <div className="space-y-6 px-4 py-6 sm:px-6 lg:px-8">
      <div>
        <Link
          href="/admin"
          className="inline-flex items-center gap-1 text-sm font-semibold text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-4" /> Admin
        </Link>
        <h1 className="mt-2 flex items-center gap-2 text-3xl font-extrabold tracking-tight">
          <Bug className="size-7 text-primary" /> Bug reports
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          {activeCount} active · {autoCount} auto · {resolvedCount} resolved · {totalCount} total
        </p>
      </div>

      <div className="flex gap-2 border-b border-border pb-2">
        <Link
          href="/admin/bugs"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "active"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Active ({activeCount})
        </Link>
        <Link
          href="/admin/bugs?filter=resolved"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "resolved"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Resolved ({resolvedCount})
        </Link>
        <Link
          href="/admin/bugs?filter=all"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "all"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          All ({totalCount})
        </Link>
      </div>

      {items.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          {currentFilter === "resolved"
            ? "No resolved bug reports."
            : currentFilter === "active"
            ? "No active bug reports! All clean."
            : "No bug reports yet."}
        </p>
      ) : (
        <div className="space-y-3">
          {items.map((item) => {
            const count = item.occurrenceCount || 1;
            const seen = item.lastSeenAt || item.createdAt;
            return (
              <article key={String(item._id)} className="rounded-xl border border-border bg-card p-4">
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <div>
                    <h2 className="font-bold">{item.title}</h2>
                    <p className="mt-0.5 text-xs text-muted-foreground">
                      {item.source}
                      {item.autoGenerated ? (
                        <span className="ml-1.5 rounded-full bg-amber-500/15 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-amber-700 dark:text-amber-400">
                          Auto
                        </span>
                      ) : null}
                      {item.errorCode ? ` · ${item.errorCode}` : ""}
                      {item.gameSlug ? ` · ${item.gameSlug}` : ""}
                      {count > 1 ? ` · ×${count}` : ""}
                      {item.launcherVersion ? ` · app ${item.launcherVersion}` : ""}
                      {item.platform ? ` · ${item.platform}` : ""}
                      {item.pageUrl ? (
                        <>
                          {" · "}
                          <a
                            href={item.pageUrl}
                            target="_blank"
                            rel="noreferrer"
                            className="font-semibold text-primary hover:underline"
                          >
                            page
                          </a>
                        </>
                      ) : null}
                    </p>
                  </div>
                  <span className="rounded-full bg-secondary px-2.5 py-0.5 text-[11px] font-bold uppercase tracking-wide">
                    {BUG_REPORT_STATUS_LABELS[item.status]}
                  </span>
                </div>
                <p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{item.description}</p>
                <p className="mt-2 text-xs text-muted-foreground">
                  {item.submitterName ?? "Anonymous"}
                  {item.contactEmail ? ` · ${item.contactEmail}` : ""}
                  {" · first "}
                  <LocalTime value={new Date(item.createdAt).toISOString()} />
                  {item.autoGenerated || count > 1 ? (
                    <>
                      {" · last "}
                      <LocalTime value={new Date(seen).toISOString()} />
                    </>
                  ) : null}
                </p>
                <BugReportActions
                  item={{
                    _id: String(item._id),
                    status: item.status,
                    adminNotes: item.adminNotes,
                  }}
                />
              </article>
            );
          })}
        </div>
      )}
    </div>
  );
}
