/**
 * PlayBound Remote — Sunshine wrapper (host capture/encode).
 *
 * Follows the exact vendoring/spawn pattern already proven by
 * `couch/windowsVigem.js`: a binary under `resources/`, spawned with
 * `child_process.spawn`, never shown to the player. A human never opens
 * Sunshine's own web UI (normally localhost:47990) — PlayBound writes
 * `sunshine.conf` directly and drives pairing/app-registration through
 * Sunshine's local HTTPS API instead.
 *
 * NOT WIRED TO A REAL BINARY YET. `resolveSunshineDir()` looks for a
 * vendored copy the same way `resolveVigemDir()` does, but nothing in this
 * repo has actually downloaded/vendored Sunshine — that's a real binary
 * (GPL-3, must ship its LICENSE/NOTICE per Settings → About) that needs a
 * deliberate vendoring step, not something to fabricate here. The exact
 * `sunshine.conf` keys below are written from general knowledge of
 * Sunshine's config format, not verified against a pinned version's actual
 * docs — confirm before relying on them, per the plan this was built from.
 */

"use strict";

const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");

const HOST_EXE = "sunshine.exe";

function resolveSunshineDir() {
  const candidates = [];
  if (process.resourcesPath) {
    candidates.push(path.join(process.resourcesPath, "sunshine"));
  }
  candidates.push(path.join(__dirname, "..", "..", "resources", "sunshine"));
  try {
    const { app } = require("electron");
    if (app && !app.isPackaged) {
      candidates.push(path.join(app.getAppPath(), "resources", "sunshine"));
    }
  } catch {
    /* ignore — not running under Electron (e.g. a unit test) */
  }
  for (const dir of candidates) {
    if (dir && fs.existsSync(path.join(dir, HOST_EXE))) return dir;
    if (dir && fs.existsSync(path.join(dir, "Sunshine", HOST_EXE))) return path.join(dir, "Sunshine");
  }
  return null;
}

/**
 * Headless Sunshine config — no web UI a human ever needs to open. Port and
 * PIN are generated by PlayBound, not chosen by the player.
 * @param {{ port: number, pin: string, deviceName: string }} opts
 * @returns {string} the sunshine.conf file contents
 */
function generateSunshineConfig({ port, pin, deviceName }) {
  // TODO(verify): confirm these exact key names against the pinned
  // Sunshine release's own default sunshine.conf / documentation before
  // this is relied on to actually configure a running instance.
  return [
    `sunshine_name = ${deviceName}`,
    `port = ${port}`,
    `pin = ${pin}`,
    "origin_web_ui_allowed = lan",
    "channels = 1",
    "",
  ].join("\n");
}

/**
 * @param {object} deps
 * @param {typeof spawn} [deps.spawnFn] injected for testability
 * @param {() => string | null} [deps.resolveDir] injected for testability
 */
function createSunshineHost(deps = {}) {
  const spawnFn = deps.spawnFn || spawn;
  const resolveDir = deps.resolveDir || resolveSunshineDir;

  let child = null;

  function isRunning() {
    return Boolean(child && !child.killed);
  }

  function start({ port, pin, deviceName, configDir }) {
    if (isRunning()) return { ok: true, alreadyRunning: true };
    const dir = resolveDir();
    if (!dir) {
      return {
        ok: false,
        reason: "Remote Play host component is missing from this PlayBound build.",
      };
    }
    const confPath = path.join(configDir, "sunshine.conf");
    fs.writeFileSync(confPath, generateSunshineConfig({ port, pin, deviceName }), "utf8");

    child = spawnFn(path.join(dir, HOST_EXE), ["--config", confPath], {
      cwd: dir,
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });
    child.on("exit", () => {
      child = null;
    });
    return { ok: true };
  }

  function stop() {
    if (!child) return;
    try {
      child.kill();
    } catch {
      /* ignore */
    }
    child = null;
  }

  return { start, stop, isRunning, resolveSunshineDir: resolveDir };
}

module.exports = { HOST_EXE, resolveSunshineDir, generateSunshineConfig, createSunshineHost };
