/**
 * PlayBound Remote — Sunshine wrapper (host capture/encode).
 *
 * Follows the exact vendoring/spawn pattern already proven by
 * `couch/windowsVigem.js`: a binary under `resources/`, spawned with
 * `child_process.spawn`, never shown to the player. A human never opens
 * Sunshine's own web UI (normally localhost:47990) — PlayBound writes
 * `sunshine.conf` directly and drives pairing/app-registration through
 * Sunshine's local HTTPS API instead.
 *
 * NOT WIRED TO A REAL BINARY YET. `resolveSunshineDir()` looks for a
 * vendored copy the same way `resolveVigemDir()` does, but nothing in this
 * repo has actually downloaded/vendored Sunshine — that's a real binary
 * (GPL-3, must ship its LICENSE/NOTICE per Settings → About) that needs a
 * deliberate vendoring step, not something to fabricate here. The exact
 * `sunshine.conf` keys below are written from general knowledge of
 * Sunshine's config format, not verified against a pinned version's actual
 * docs — confirm before relying on them, per the plan this was built from.
 */

"use strict";

const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");

const HOST_EXE = "sunshine.exe";

function resolveSunshineDir() {
  const candidates = [];
  if (process.resourcesPath) {
    candidates.push(path.join(process.resourcesPath, "sunshine"));
  }
  candidates.push(path.join(__dirname, "..", "..", "resources", "sunshine"));
  try {
    const { app } = require("electron");
    if (app && !app.isPackaged) {
      candidates.push(path.join(app.getAppPath(), "resources", "sunshine"));
    }
  } catch {
    /* ignore — not running under Electron (e.g. a unit test) */
  }
  for (const dir of candidates) {
    if (dir && fs.existsSync(path.join(dir, HOST_EXE))) return dir;
    if (dir && fs.existsSync(path.join(dir, "Sunshine", HOST_EXE))) return path.join(dir, "Sunshine");
  }
  return null;
}

const https = require("https");

/**
 * Headless Sunshine config — no web UI a human ever needs to open. Port and
 * PIN are generated by PlayBound, not chosen by the player.
 * @param {{ port: number, pin: string, deviceName: string, statePath?: string, appsPath?: string }} opts
 * @returns {string} the sunshine.conf file contents
 */
function generateSunshineConfig({ port, pin, deviceName, statePath, appsPath }) {
  const lines = [
    `sunshine_name = ${deviceName}`,
    `port = ${port}`,
    `pin = ${pin}`,
    "origin_web_ui_allowed = lan",
    "channels = 1",
  ];
  if (statePath) lines.push(`file_state = ${statePath}`);
  if (appsPath) lines.push(`file_apps = ${appsPath}`);
  lines.push("");
  return lines.join("\n");
}

/**
 * Makes an authenticated request to Sunshine's local HTTPS management API.
 * Sunshine runs its web manager on port 47990 by default with self-signed TLS.
 */
function callSunshineApi({ method = "GET", path: reqPath = "/api/pin", body = null, port = 47990, timeoutMs = 4000 }) {
  return new Promise((resolve, reject) => {
    const auth = Buffer.from("admin:playbound123").toString("base64");
    const payload = body ? (typeof body === "string" ? body : JSON.stringify(body)) : null;
    const req = https.request(
      {
        hostname: "127.0.0.1",
        port,
        path: reqPath,
        method,
        rejectUnauthorized: false,
        headers: {
          Authorization: `Basic ${auth}`,
          ...(payload ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) } : {}),
        },
      },
      (res) => {
        let data = "";
        res.on("data", (chunk) => (data += chunk));
        res.on("end", () => {
          let parsed = data;
          try {
            parsed = JSON.parse(data);
          } catch {}
          resolve({ statusCode: res.statusCode, data: parsed });
        });
      }
    );
    req.on("error", reject);
    req.setTimeout(timeoutMs, () => {
      req.destroy();
      reject(new Error("Sunshine API request timed out"));
    });
    if (payload) {
      req.write(payload);
    }
    req.end();
  });
}

/**
 * @param {object} deps
 * @param {typeof spawn} [deps.spawnFn] injected for testability
 * @param {() => string | null} [deps.resolveDir] injected for testability
 * @param {typeof callSunshineApi} [deps.callApiFn] injected for testability
 */
function createSunshineHost(deps = {}) {
  const spawnFn = deps.spawnFn || spawn;
  const resolveDir = deps.resolveDir || resolveSunshineDir;
  const callApiFn = deps.callApiFn || callSunshineApi;

  let child = null;
  let activePairingCancel = null;

  function isRunning() {
    return Boolean(child && !child.killed);
  }

  function start({ port, pin, deviceName, configDir }) {
    if (isRunning()) return { ok: true, alreadyRunning: true };
    const dir = resolveDir();
    if (!dir) {
      return {
        ok: false,
        reason: "Remote Play host component is missing from this PlayBound build.",
      };
    }

    // Ensure config assets exist in configDir if available in vendored dir
    const srcConfig = path.join(dir, "config");
    let statePath = null;
    let appsPath = null;
    if (configDir && fs.existsSync(srcConfig)) {
      try {
        const destState = path.join(configDir, "sunshine_state.json");
        const srcState = path.join(srcConfig, "sunshine_state.json");
        if (!fs.existsSync(destState) && fs.existsSync(srcState)) {
          fs.copyFileSync(srcState, destState);
        }
        if (fs.existsSync(destState)) statePath = destState;

        const destApps = path.join(configDir, "apps.json");
        const srcApps = path.join(srcConfig, "apps.json");
        if (!fs.existsSync(destApps) && fs.existsSync(srcApps)) {
          fs.copyFileSync(srcApps, destApps);
        }
        if (fs.existsSync(destApps)) appsPath = destApps;
      } catch {
        /* best-effort copy */
      }
    }

    const confPath = path.join(configDir, "sunshine.conf");
    fs.writeFileSync(confPath, generateSunshineConfig({ port, pin, deviceName, statePath, appsPath }), "utf8");

    child = spawnFn(path.join(dir, HOST_EXE), [confPath], {
      cwd: dir,
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });
    child.on("exit", () => {
      child = null;
      if (activePairingCancel) {
        activePairingCancel();
        activePairingCancel = null;
      }
    });
    return { ok: true };
  }

  /**
   * Polls Sunshine's /api/pin endpoint and automatically approves incoming pairing requests
   * matching the expected PIN.
   */
  function autoApprovePairing({ pin, clientName = "PlayBound Client", clientAddress = null, port = 47990, timeoutMs = 60000 }) {
    if (activePairingCancel) {
      activePairingCancel();
      activePairingCancel = null;
    }

    let cancelled = false;
    let pollTimer = null;

    const cancel = () => {
      cancelled = true;
      if (pollTimer) clearTimeout(pollTimer);
    };
    activePairingCancel = cancel;

    const startMs = Date.now();

    const promise = new Promise((resolve) => {
      async function poll() {
        if (cancelled || !isRunning() || Date.now() - startMs >= timeoutMs) {
          return resolve({ ok: false, reason: "timeout" });
        }

        try {
          const res = await callApiFn({ method: "GET", path: "/api/pin", port });
          if (res.statusCode === 200 && res.data && Array.isArray(res.data.pairings) && res.data.pairings.length > 0) {
            let targetPairing = res.data.pairings[0];
            if (clientAddress) {
              const matched = res.data.pairings.find((p) => p.address === clientAddress);
              if (matched) targetPairing = matched;
            }

            const approveRes = await callApiFn({
              method: "POST",
              path: "/api/pin",
              body: {
                pairing_id: targetPairing.id,
                pin,
                name: clientName,
              },
              port,
              timeoutMs: 15000,
            });

            if (approveRes && approveRes.data && approveRes.data.status === true) {
              return resolve({ ok: true, pairingId: targetPairing.id });
            }
          }
        } catch {
          // Sunshine web server might be starting up or busy
        }

        if (!cancelled) {
          pollTimer = setTimeout(poll, 500);
        }
      }

      poll();
    });

    return { promise, cancel };
  }

  function waitForReady(port, host = "127.0.0.1", timeoutMs = 45000) {
    const net = require("net");
    const start = Date.now();
    return new Promise((resolve) => {
      let timer = null;
      function check() {
        if (!isRunning() || Date.now() - start >= timeoutMs) {
          clearTimeout(timer);
          return resolve(false);
        }
        const sock = net.createConnection(port, host);
        let finished = false;
        const done = (ok) => {
          if (finished) return;
          finished = true;
          sock.destroy();
          if (ok) {
            clearTimeout(timer);
            resolve(true);
          } else {
            timer = setTimeout(check, 1000);
          }
        };
        sock.once("connect", () => done(true));
        sock.once("error", () => done(false));
        sock.setTimeout(1000, () => done(false));
      }
      check();
    });
  }

  function stop() {
    if (activePairingCancel) {
      activePairingCancel();
      activePairingCancel = null;
    }
    if (!child) return;
    try {
      child.kill();
    } catch {
      /* ignore */
    }
    child = null;
  }

  return { start, stop, isRunning, waitForReady, autoApprovePairing, callSunshineApi: callApiFn, resolveSunshineDir: resolveDir };
}

module.exports = { HOST_EXE, resolveSunshineDir, generateSunshineConfig, callSunshineApi, createSunshineHost };
