/**
 * Title -> genres for deal/free-offer genre inference, generated from
 * src/lib/data/games.ts. Kept separate so client components that format
 * deals do not bundle the full seed catalog (~780 KB of client JS).
 * Regenerate with: npx tsx scripts/gen-catalog-genres.ts
 */
export const CATALOG_TITLE_GENRES: ReadonlyArray<readonly [string, readonly string[]]> = [["OpenRA",["RTS","Strategy"]],
  ["Xonotic",["FPS","Arcade"]],
  ["The Battle for Wesnoth",["Fantasy","Strategy","RPG"]],
  ["SuperTuxKart",["Racing","Arcade"]],
  ["0 A.D.",["RTS","Strategy"]],
  ["Veloren",["RPG","Sandbox"]],
  ["Mindustry",["Tower Defense","Strategy","Sandbox"]],
  ["OpenTTD",["Simulation","Strategy"]],
  ["Endless Sky",["Space","RPG","Simulation"]],
  ["Privateer Gemini Gold",["Space","Simulation","Action"]],
  ["Shattered Pixel Dungeon",["Roguelike","RPG"]],
  ["Beyond All Reason",["RTS","Strategy"]],
  ["Luanti",["Sandbox","Simulation"]],
  ["Warzone 2100",["RTS","Strategy"]],
  ["SuperTux",["Platformer","Arcade"]],
  ["Zero-K",["RTS","Strategy"]],
  ["Naev",["Space","RPG"]],
  ["Hedgewars",["Strategy","Arcade"]],
  ["Unvanquished",["FPS","Strategy"]],
  ["OpenCiv3",["Strategy","Simulation"]],
  ["Freeciv",["Strategy","Simulation"]],
  ["FlightGear",["Simulation"]],
  ["Freedoom",["FPS","Arcade"]],
  ["LinCity-NG",["Simulation","Strategy"]],
  ["The Elder Scrolls II: Daggerfall",["Fantasy","RPG","Sandbox"]],
  ["The Elder Scrolls: Arena",["Fantasy","RPG"]],
  ["OpenArena",["FPS","Arcade","Action"]],
  ["Pixreveal",["Puzzle","Strategy"]],
  ["GameBuddies.io",["Arcade","Puzzle"]],
  ["EverQuest",["Fantasy","RPG"]],
  ["Star Wars Galaxies: An Empire Divided",["RPG","Simulation"]],
  ["StarCraft",["Strategy"]],
  ["Diablo II",["RPG","Arcade"]],
  ["Asheron's Call",["Fantasy","RPG","MMO"]],
  ["Tomb Raider 1+2+3",["Action","Adventure","Platformer"]],
  ["Heroes of Might and Magic III: Complete",["Fantasy","Strategy"]],
  ["Ground Control Anthology",["Strategy","RTS"]],
  ["Ground Control 2: Operation Exodus",["Strategy","RTS"]],
  ["Stronghold Crusader HD",["Strategy","RTS","Simulation"]],
  ["S.T.A.L.K.E.R.: Shadow of Chornobyl",["FPS","RPG","Shooter"]],
  ["S.T.A.L.K.E.R.: Call of Pripyat",["FPS","RPG","Shooter"]],
  ["S.T.A.L.K.E.R.: Clear Sky",["FPS","RPG","Shooter"]],
  ["S.T.A.L.K.E.R. Anomaly",["FPS","RPG","Shooter"]],
  ["Star Wars: Knights of the Old Republic",["RPG","Strategy","Action"]],
  ["Star Wars: Knights of the Old Republic II: The Sith Lords",["RPG","Strategy","Action"]],
  ["Thief Gold",["Stealth","Immersive Sim","FPS"]],
  ["Thief II: The Metal Age",["Stealth","Immersive Sim","FPS"]],
  ["Wolfenstein: Enemy Territory",["FPS","Action","Strategy"]],
  ["War Thunder",["Simulation","Action","Strategy"]],
  ["Albion Online",["Fantasy","MMO","RPG"]],
  ["Guild Wars 2",["MMO","RPG","Action"]],
  ["The Lord of the Rings Online",["Fantasy","MMO","RPG"]],
  ["DC Universe Online",["MMO","RPG","Action"]],
  ["World of Tanks",["Arcade","Simulation"]],
  ["Apex Legends",["FPS","Arcade"]],
  ["Hearthstone",["Strategy"]],
  ["Team Fortress 2",["FPS","Action","Shooter"]],
  ["Genshin Impact",["Fantasy","RPG","Action"]],
  ["Dota 2",["MOBA","Strategy","Action"]],
  ["Marathon 2: Durandal",["FPS","Action","Shooter"]],
  ["Marathon",["FPS","Action","Shooter"]],
  ["Aleph One (Marathon Trilogy)",["FPS","Action","Shooter"]],
  ["League of Legends",["MOBA","Strategy","Action"]],
  ["VALORANT",["FPS","Action","Strategy"]],
  ["Counter-Strike 2",["FPS","Action","Strategy"]],
  ["Quake Champions",["FPS","Action","Arcade"]],
  ["Asphalt Legends",["Racing","Arcade"]],
  ["TinyWind",["Adventure","Roguelike"]],
  ["Warframe",["Shooter","Action","MMO"]],
  ["Mega Man Unlimited",["Platformer","Action"]],
  ["HoloCure - Save the Fans!",["Action","Roguelike","Arcade"]],
  ["Freelancer",["Space","Simulation","Action"]],
  ["The Ur-Quan Masters",["Space","RPG","Strategy"]],
  ["AirForce",["Arcade","Action","Shooter"]],
  ["BZFlag",["Action","Shooter","Arcade"]],
  ["Beneath a Steel Sky",["Adventure","Puzzle"]],
  ["Marathon 2: Durandal",["FPS","Shooter","Action"]],
  ["Dungeon Keeper Gold",["Fantasy","Strategy","Simulation"]],
  ["The Elder Scrolls III: Morrowind",["Fantasy","RPG","Adventure"]],
  ["Space Station 14",["Simulation","Sandbox","Social Deduction"]],
  ["World of Sea Battle",["Simulation","Action","Strategy"]],
  ["Old School RuneScape",["Fantasy","RPG","Adventure"]],
  ["Star Wars: The Old Republic",["RPG","Action","Adventure"]],
  ["Dune Legacy",["Strategy"]],
  ["Mr. Boom",["Action","Arcade"]],
  ["OpenMOHAA",["FPS","Action"]],
  ["Metal Slug: Community Remake",["Action","Arcade"]],
  ["Microsoft Allegiance",["Simulation","Strategy","Action"]],
  ["Gradius Remake",["Action","Arcade"]],
  ["BombSquad",["Action","Arcade","Party Game"]],
  ["Re-Volt (RVGL)",["Racing","Arcade","Action"]],
  ["wipEout Rewrite",["Racing","Action","Arcade"]],
  ["OpenHV",["RTS","Strategy"]],
  ["TripleA",["Strategy","Simulation"]],
  ["Strikers Club",["Sports","Action"]],
  ["Trigger Rally",["Sports","Simulation","Action"]],
  ["RollerCoaster Tycoon: Deluxe",["Simulation","Strategy","Sandbox"]],
  ["Brawlhalla",["Action","Fighting"]],
  ["YSoccer",["Sports","Action","Simulation"]],
  ["Hurry Curry!",["Action","Arcade","Party Game"]],
  ["Cataclysm: Dark Days Ahead",["Roguelike","RPG","Survival"]],
  ["YORG",["Racing","Arcade","Action"]],
  ["TORCS",["Racing","Simulation","Sports"]],
  ["Stunt Rally",["Racing","Arcade","Sports"]],
  ["Sonic Robo Blast 2",["Platformer","Action","Adventure"]],
  ["Shadow Warrior (JFSW)",["Shooter","Action"]],
  ["Trackmania",["Racing","Sports"]],
  ["The Spike Cross",["Sports","Action"]],
  ["Populous: The Beginning",["Strategy","Simulation"]],
  ["Earth 2140 Trilogy",["Strategy","RTS"]],
  ["Super Sidekicks",["Sports","Arcade"]],
  ["Baseball Stars 2",["Sports","Arcade"]],
  ["Soccer Brawl",["Sports","Arcade"]],
  ["X-Men Arcade Remake",["Action","Arcade"]],
  ["Teenage Mutant Ninja Turtles: Rescue-Palooza!",["Action","Arcade"]],
  ["Relic Hunters Zero: Remix",["Shooter","Action"]],
  ["SRB2Kart",["Racing","Arcade"]],
  ["Lovers in a Dangerous Spacetime",["Shooter","Action"]],
  ["FlatOut 2",["Racing","Arcade","Action"]],
  ["Pokémon Blaze Online",["MMO","RPG","Adventure"]],
  ["PokeMMO",["MMO","RPG","Adventure"]],
  ["Castlevania ReVamped",["Platformer","Action","Adventure"]],
  ["Hawken: Hawkening",["Shooter","Action","FPS"]],
  ["OpenTS",["RTS","Strategy"]],
  ["Star Wars: Galactic Battlegrounds Saga",["RTS","Strategy"]],
  ["Quake II",["FPS","Shooter","Action"]],
  ["OutRun (Fan Remake)",["Racing","Arcade","Action"]],
  ["Hypersomnia",["Shooter","Action","Arcade"]],
  ["Final Fantasy XI",["Fantasy","MMO","RPG"]]];
