/*
 * sync-cadence.js
 *
 * Copies the canonical polling cadences from
 * platform/src/lib/realtime/cadence.json into services/cadence.js so the
 * launcher and the website always agree about how often each live surface
 * re-reads.
 *
 * These numbers were previously hardcoded in both clients and drifted:
 * notifications polled every 6s here and every 45s on the web, for identical
 * data. Generating the launcher's copy — the same arrangement catalog.js
 * already uses — means one edit updates both.
 *
 * Runs from the repo checkout at build time. The generated file is committed,
 * so a build from a tarball without platform/ still packages the last known
 * good values instead of failing.
 *
 * Usage:  node scripts/sync-cadence.js
 */

"use strict";

const fs = require("fs");
const path = require("path");

const launcherDir = path.join(__dirname, "..");
const sourcePath = path.join(
  launcherDir,
  "..",
  "platform",
  "src",
  "lib",
  "realtime",
  "cadence.json"
);

/*
 * Written into renderer/ as an ES module, not services/ as CommonJS.
 *
 * The obvious home was preload.js bridging a require()d module, but a
 * sandboxed preload can only require Electron's small built-in set — pointing
 * it at a local file throws "module not found" before the bridge is created,
 * which leaves window.playbound undefined and the whole app dead on boot.
 * The renderer is already ESM and imports its own modules freely, so it reads
 * this one directly and preload stays out of it.
 */
const outPath = path.join(launcherDir, "renderer", "cadence.js");

function main() {
  if (!fs.existsSync(sourcePath)) {
    console.warn(`[sync-cadence] Source not found: ${sourcePath}`);
    console.warn("[sync-cadence] Keeping the existing services/cadence.js");
    return;
  }

  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(sourcePath, "utf-8"));
  } catch (err) {
    console.error(`[sync-cadence] Could not parse cadence.json: ${err.message}`);
    console.error("[sync-cadence] Keeping the existing services/cadence.js");
    return;
  }

  // `_comment` documents the source file; it is not a cadence.
  delete parsed._comment;

  const keys = Object.keys(parsed);
  if (keys.length === 0) {
    console.error("[sync-cadence] cadence.json has no values — refusing to write an empty module");
    return;
  }

  const bad = keys.filter((k) => !Number.isFinite(parsed[k]) || parsed[k] <= 0);
  if (bad.length > 0) {
    console.error(`[sync-cadence] Non-positive/non-numeric values: ${bad.join(", ")} — refusing to write`);
    return;
  }

  const header = [
    "// Auto-generated by scripts/sync-cadence.js — do not edit by hand.",
    "// Canonical source: platform/src/lib/realtime/cadence.json",
    "// Edit there; both the website and this launcher read the same numbers.",
    "",
    "export const CADENCE = ",
  ].join("\n");

  fs.writeFileSync(outPath, header + JSON.stringify(parsed, null, 2) + ";\n", "utf-8");
  console.log(`[sync-cadence] Wrote ${keys.length} cadence value(s) to renderer/cadence.js`);
}

main();
