/**
 * sync-catalog.js
 *
 * Fetches the full published game catalog from the PlayBound site API and
 * writes it to catalog.js so the bundled launcher has an up-to-date offline
 * fallback. Run automatically before `npm run dist` via the predist hook.
 *
 * Usage:  node scripts/sync-catalog.js [--api-base https://playbound.club]
 */

const fs = require("fs");
const path = require("path");

const DEFAULT_API_BASE = "https://playbound.club";

async function main() {
  const args = process.argv.slice(2);
  const baseIdx = args.indexOf("--api-base");
  const apiBase = baseIdx !== -1 && args[baseIdx + 1] ? args[baseIdx + 1] : DEFAULT_API_BASE;
  const url = `${apiBase}/api/launcher/catalog?_t=${Date.now()}`;

  console.log(`[sync-catalog] Fetching ${url} …`);

  try {
    const res = await fetch(url, {
      cache: "no-store",
      headers: { "user-agent": "playbound-sync-catalog", accept: "application/json", "cache-control": "no-cache" },
    });
    if (!res.ok) {
      throw new Error(`HTTP ${res.status} from ${url}`);
    }
    const data = await res.json();
    const games = Array.isArray(data.games) ? data.games : [];
    if (games.length === 0) {
      throw new Error("API returned 0 games — refusing to overwrite catalog.js with an empty list");
    }

    const catalogPath = path.join(__dirname, "..", "catalog.js");
    const previousCount = (() => {
      try {
        if (!fs.existsSync(catalogPath)) return 0;
        delete require.cache[require.resolve(catalogPath)];
        const existing = require(catalogPath);
        return Array.isArray(existing) ? existing.length : 0;
      } catch {
        return 0;
      }
    })();

    const header = [
      "// Auto-generated by scripts/sync-catalog.js — do not edit by hand.",
      `// Synced from ${apiBase} at ${new Date().toISOString()}`,
      `// ${games.length} game(s)`,
      "",
      "module.exports = ",
    ].join("\n");

    const json = JSON.stringify(games, null, 2);
    fs.writeFileSync(catalogPath, header + json + ";\n", "utf-8");

    const delta = games.length - previousCount;
    const note = delta === 0 ? "" : ` (${delta > 0 ? "+" : ""}${delta} vs previous ${previousCount})`;
    console.log(`[sync-catalog] Wrote ${games.length} game(s) to catalog.js${note}`);
  } catch (err) {
    console.error(`[sync-catalog] ERROR: ${err.message}`);
    console.error("[sync-catalog] Build will continue with the existing catalog.js");
  }
}

main();
