import Link from "next/link";
import { connection } from "next/server";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth/next";
import { ArrowLeft, Bug, Lightbulb, Megaphone } from "lucide-react";
import { authOptions } from "@/lib/auth";
import dbConnect from "@/lib/db";
import BugReport from "@/lib/models/BugReport";
import { BUG_REPORT_STATUS_LABELS, type BugReportKind, type BugReportStatus } from "@/lib/bugReports";
import { BugReportActions } from "@/components/admin/BugReportActions";
import { LocalTime } from "@/components/LocalTime";

const CLOSED_STATUSES: BugReportStatus[] = ["resolved", "dismissed"];

export const metadata: Metadata = { title: "Admin · Feedback" };

export default async function AdminFeedbackPage({
  searchParams,
}: {
  searchParams: Promise<{ filter?: string }>;
}) {
  await connection();
  const session = await getServerSession(authOptions);
  if (session?.user?.role !== "admin") redirect("/");

  const sp = await searchParams;
  const currentFilter =
    sp.filter === "resolved" || sp.filter === "closed"
      ? "closed"
      : sp.filter === "all"
      ? "all"
      : sp.filter === "suggestions"
      ? "suggestions"
      : sp.filter === "bugs"
      ? "bugs"
      : "active";

  let items: {
    _id: { toString(): string };
    title: string;
    description: string;
    kind?: BugReportKind;
    source: "website" | "launcher";
    pageUrl?: string | null;
    contactEmail?: string | null;
    submitterName?: string | null;
    launcherVersion?: string | null;
    platform?: string | null;
    osVersion?: string | null;
    architecture?: string | null;
    status: BugReportStatus;
    adminNotes?: string | null;
    createdAt: Date;
    autoGenerated?: boolean;
    errorCode?: string | null;
    gameSlug?: string | null;
    editionSlug?: string | null;
    phase?: string | null;
    exitCode?: number | null;
    messageSamples?: string[] | null;
    occurrenceCount?: number;
    lastSeenAt?: Date | null;
  }[] = [];

  let activeCount = 0;
  let resolvedCount = 0;
  let totalCount = 0;
  let suggestionsCount = 0;
  let bugsCount = 0;

  try {
    await dbConnect();

    // User feedback submitted through our forms (exclude auto-generated telemetry bugs)
    const baseFeedbackFilter = { autoGenerated: { $ne: true } };

    const mongoFilter =
      currentFilter === "closed"
        ? { ...baseFeedbackFilter, status: { $in: CLOSED_STATUSES } }
        : currentFilter === "all"
        ? baseFeedbackFilter
        : currentFilter === "suggestions"
        ? { ...baseFeedbackFilter, status: { $nin: CLOSED_STATUSES }, kind: "suggestion" }
        : currentFilter === "bugs"
        ? { ...baseFeedbackFilter, status: { $nin: CLOSED_STATUSES }, kind: { $ne: "suggestion" } }
        : { ...baseFeedbackFilter, status: { $nin: CLOSED_STATUSES } };

    const [active, resolved, total, suggestions, bugs, foundItems] =
      await Promise.all([
        BugReport.countDocuments({ ...baseFeedbackFilter, status: { $nin: CLOSED_STATUSES } }),
        BugReport.countDocuments({ ...baseFeedbackFilter, status: { $in: CLOSED_STATUSES } }),
        BugReport.countDocuments(baseFeedbackFilter),
        BugReport.countDocuments({ ...baseFeedbackFilter, status: { $nin: CLOSED_STATUSES }, kind: "suggestion" }),
        BugReport.countDocuments({ ...baseFeedbackFilter, status: { $nin: CLOSED_STATUSES }, kind: { $ne: "suggestion" } }),
        BugReport.find(mongoFilter)
          .sort({ lastSeenAt: -1, createdAt: -1 })
          .limit(200)
          .lean(),
      ]);

    activeCount = active;
    resolvedCount = resolved;
    totalCount = total;
    suggestionsCount = suggestions;
    bugsCount = bugs;
    items = foundItems as unknown as typeof items;
  } catch (err) {
    console.error("Failed to load feedback entries:", err);
  }

  return (
    <div className="space-y-6 px-4 py-6 sm:px-6 lg:px-8">
      <div>
        <Link
          href="/admin/users"
          className="inline-flex items-center gap-1 text-sm font-semibold text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-4" /> Users
        </Link>
        <h1 className="mt-2 flex items-center gap-2 text-3xl font-extrabold tracking-tight">
          <Megaphone className="size-7 text-primary" /> User feedback
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          {activeCount} active ({suggestionsCount} suggestions, {bugsCount} bugs) · {resolvedCount} closed · {totalCount} total
        </p>
      </div>

      <div className="flex flex-wrap gap-2 border-b border-border pb-2">
        <Link
          href="/admin/feedback"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "active"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Active ({activeCount})
        </Link>
        <Link
          href="/admin/feedback?filter=suggestions"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "suggestions"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Suggestions ({suggestionsCount})
        </Link>
        <Link
          href="/admin/feedback?filter=bugs"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "bugs"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Bugs ({bugsCount})
        </Link>
        <Link
          href="/admin/feedback?filter=closed"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "closed"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Closed ({resolvedCount})
        </Link>
        <Link
          href="/admin/feedback?filter=all"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "all"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          All ({totalCount})
        </Link>
      </div>

      {items.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          {currentFilter === "closed"
            ? "No closed feedback entries."
            : currentFilter === "suggestions"
            ? "No suggestions found."
            : currentFilter === "bugs"
            ? "No active bug reports found."
            : currentFilter === "active"
            ? "No active feedback! All clean."
            : "No feedback entries yet."}
        </p>
      ) : (
        <div className="space-y-3">
          {items.map((item) => {
            const seen = item.lastSeenAt || item.createdAt;
            return (
              <article key={String(item._id)} className="rounded-xl border border-border bg-card p-4">
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <h2 className="font-bold">{item.title}</h2>
                      {item.kind === "suggestion" ? (
                        <span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-emerald-700 dark:text-emerald-400">
                          <Lightbulb className="size-3" /> Suggestion
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 rounded-full bg-red-500/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-red-700 dark:text-red-400">
                          <Bug className="size-3" /> Bug
                        </span>
                      )}
                    </div>
                    <p className="mt-0.5 text-xs text-muted-foreground">
                      {item.source}
                      {item.gameSlug ? ` · ${item.gameSlug}` : ""}
                      {item.launcherVersion ? ` · app ${item.launcherVersion}` : ""}
                      {item.platform ? ` · ${item.platform}` : ""}
                      {item.pageUrl ? (
                        <>
                          {" · "}
                          <a
                            href={item.pageUrl}
                            target="_blank"
                            rel="noreferrer"
                            className="font-semibold text-primary hover:underline"
                          >
                            page
                          </a>
                        </>
                      ) : null}
                    </p>
                  </div>
                  <span className="rounded-full bg-secondary px-2.5 py-0.5 text-[11px] font-bold uppercase tracking-wide">
                    {BUG_REPORT_STATUS_LABELS[item.status]}
                  </span>
                </div>
                <p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{item.description}</p>
                <p className="mt-2 text-xs text-muted-foreground">
                  {item.submitterName ?? "Anonymous"}
                  {item.contactEmail ? ` · ${item.contactEmail}` : ""}
                  {" · "}
                  <LocalTime value={new Date(seen).toISOString()} />
                </p>
                <BugReportActions
                  item={{
                    _id: String(item._id),
                    status: item.status,
                    adminNotes: item.adminNotes,
                  }}
                />
              </article>
            );
          })}
        </div>
      )}
    </div>
  );
}
