import Link from "next/link";
import { connection } from "next/server";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth/next";
import { ArrowLeft, Bug, Lightbulb, Megaphone } from "lucide-react";
import { authOptions } from "@/lib/auth";
import dbConnect from "@/lib/db";
import BugReport from "@/lib/models/BugReport";
import { BUG_REPORT_STATUS_LABELS, type BugReportKind, type BugReportStatus } from "@/lib/bugReports";
import { BugReportActions } from "@/components/admin/BugReportActions";
import { LocalTime } from "@/components/LocalTime";

const CLOSED_STATUSES: BugReportStatus[] = ["resolved", "dismissed"];

export const metadata: Metadata = { title: "Admin · Feedback" };

function Chip({ children }: { children: ReactNode }) {
  return (
    <span className="rounded-md bg-secondary px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-secondary-foreground">
      {children}
    </span>
  );
}

export default async function AdminFeedbackPage({
  searchParams,
}: {
  searchParams: Promise<{ filter?: string }>;
}) {
  await connection();
  const session = await getServerSession(authOptions);
  if (session?.user?.role !== "admin") redirect("/");

  const sp = await searchParams;
  const currentFilter =
    sp.filter === "resolved" || sp.filter === "closed"
      ? "closed"
      : sp.filter === "all"
      ? "all"
      : sp.filter === "servers"
      ? "servers"
      : sp.filter === "suggestions"
      ? "suggestions"
      : sp.filter === "bugs"
      ? "bugs"
      : "active";

  let items: {
    _id: { toString(): string };
    title: string;
    description: string;
    kind?: BugReportKind;
    source: "website" | "launcher";
    pageUrl?: string | null;
    contactEmail?: string | null;
    submitterName?: string | null;
    launcherVersion?: string | null;
    platform?: string | null;
    osVersion?: string | null;
    architecture?: string | null;
    status: BugReportStatus;
    adminNotes?: string | null;
    createdAt: Date;
    autoGenerated?: boolean;
    errorCode?: string | null;
    gameSlug?: string | null;
    editionSlug?: string | null;
    phase?: string | null;
    exitCode?: number | null;
    messageSamples?: string[] | null;
    occurrenceCount?: number;
    lastSeenAt?: Date | null;
  }[] = [];

  let activeCount = 0;
  let resolvedCount = 0;
  let totalCount = 0;
  let autoCount = 0;
  let serversCount = 0;
  let suggestionsCount = 0;
  let bugsCount = 0;

  try {
    await dbConnect();

    const serversQuery = {
      $or: [
        { errorCode: { $regex: /^community_server_/ } },
        { title: { $regex: /\[community_server_/ } },
        { fingerprint: { $regex: /^community_server_/ } },
        { phase: "reconcile" },
        { phase: "reconcile_cron" },
        { phase: "hosting" },
      ],
    };

    const mongoFilter =
      currentFilter === "closed"
        ? { status: { $in: CLOSED_STATUSES } }
        : currentFilter === "all"
        ? {}
        : currentFilter === "servers"
        ? { status: { $nin: CLOSED_STATUSES }, ...serversQuery }
        : currentFilter === "suggestions"
        ? { status: { $nin: CLOSED_STATUSES }, kind: "suggestion" }
        : currentFilter === "bugs"
        ? { status: { $nin: CLOSED_STATUSES }, kind: { $ne: "suggestion" } }
        : { status: { $nin: CLOSED_STATUSES } };

    const [active, resolved, total, auto, servers, suggestions, bugs, foundItems] =
      await Promise.all([
        BugReport.countDocuments({ status: { $nin: CLOSED_STATUSES } }),
        BugReport.countDocuments({ status: { $in: CLOSED_STATUSES } }),
        BugReport.countDocuments(),
        BugReport.countDocuments({ autoGenerated: true, status: { $nin: CLOSED_STATUSES } }),
        BugReport.countDocuments({ status: { $nin: CLOSED_STATUSES }, ...serversQuery }),
        BugReport.countDocuments({ status: { $nin: CLOSED_STATUSES }, kind: "suggestion" }),
        BugReport.countDocuments({ status: { $nin: CLOSED_STATUSES }, kind: { $ne: "suggestion" } }),
        BugReport.find(mongoFilter)
          .sort({ lastSeenAt: -1, createdAt: -1 })
          .limit(200)
          .lean(),
      ]);

    activeCount = active;
    resolvedCount = resolved;
    totalCount = total;
    autoCount = auto;
    serversCount = servers;
    suggestionsCount = suggestions;
    bugsCount = bugs;
    items = foundItems as unknown as typeof items;
  } catch (err) {
    console.error("Failed to load feedback entries:", err);
  }

  return (
    <div className="space-y-6 px-4 py-6 sm:px-6 lg:px-8">
      <div>
        <Link
          href="/admin/users"
          className="inline-flex items-center gap-1 text-sm font-semibold text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-4" /> Users
        </Link>
        <h1 className="mt-2 flex items-center gap-2 text-3xl font-extrabold tracking-tight">
          <Megaphone className="size-7 text-primary" /> Provide feedback & bug reports
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          {activeCount} active ({suggestionsCount} suggestions, {bugsCount} bugs) · {serversCount} servers · {autoCount} auto · {resolvedCount} closed · {totalCount} total
        </p>
      </div>

      <div className="flex flex-wrap gap-2 border-b border-border pb-2">
        <Link
          href="/admin/feedback"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "active"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Active ({activeCount})
        </Link>
        <Link
          href="/admin/feedback?filter=suggestions"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "suggestions"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Suggestions ({suggestionsCount})
        </Link>
        <Link
          href="/admin/feedback?filter=bugs"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "bugs"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Bugs ({bugsCount})
        </Link>
        <Link
          href="/admin/feedback?filter=servers"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "servers"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Servers ({serversCount})
        </Link>
        <Link
          href="/admin/feedback?filter=closed"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "closed"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          Closed ({resolvedCount})
        </Link>
        <Link
          href="/admin/feedback?filter=all"
          className={`rounded-lg px-3 py-1.5 text-sm font-bold transition-colors ${
            currentFilter === "all"
              ? "bg-primary text-primary-foreground"
              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
          }`}
        >
          All ({totalCount})
        </Link>
      </div>

      {items.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          {currentFilter === "closed"
            ? "No closed feedback entries."
            : currentFilter === "suggestions"
            ? "No suggestions found."
            : currentFilter === "bugs"
            ? "No active bug reports found."
            : currentFilter === "active"
            ? "No active feedback! All clean."
            : "No feedback entries yet."}
        </p>
      ) : (
        <div className="space-y-3">
          {items.map((item) => {
            const streamKind = item.title.startsWith("[remote_play_failed]")
              ? "Remote Play"
              : item.title.startsWith("[couch_failed]")
                ? "Couch co-op"
                : null;
            const count = item.occurrenceCount || 1;
            const seen = item.lastSeenAt || item.createdAt;
            const samples = Array.isArray(item.messageSamples)
              ? item.messageSamples.filter(Boolean)
              : [];
            const isCommunityServer =
              item.title.startsWith("[community_server_") ||
              Boolean(item.errorCode && item.errorCode.startsWith("community_server_")) ||
              item.phase === "reconcile" ||
              item.phase === "reconcile_cron" ||
              item.phase === "hosting";
            const opsHref = isCommunityServer
              ? `/admin/ops?family=servers${item.gameSlug ? `&game=${encodeURIComponent(item.gameSlug)}` : ""}`
              : item.gameSlug
              ? `/admin/ops?family=launcher&game=${encodeURIComponent(item.gameSlug)}`
              : "/admin/ops?family=launcher";
            return (
              <article key={String(item._id)} className="rounded-xl border border-border bg-card p-4">
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <h2 className="font-bold">{item.title}</h2>
                      {item.kind === "suggestion" ? (
                        <span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-emerald-700 dark:text-emerald-400">
                          <Lightbulb className="size-3" /> Suggestion
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 rounded-full bg-red-500/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-red-700 dark:text-red-400">
                          <Bug className="size-3" /> Bug
                        </span>
                      )}
                    </div>
                    <p className="mt-0.5 text-xs text-muted-foreground">
                      {item.source}
                      {item.autoGenerated ? (
                        <span className="ml-1.5 rounded-full bg-amber-500/15 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-amber-700 dark:text-amber-400">
                          Auto
                        </span>
                      ) : null}
                      {isCommunityServer ? (
                        <span className="ml-1.5 rounded-full bg-purple-500/15 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-purple-700 dark:text-purple-400">
                          Community Server
                        </span>
                      ) : streamKind ? ` · ${streamKind}` : ""}
                      {item.errorCode ? ` · ${item.errorCode}` : ""}
                      {item.gameSlug ? ` · ${item.gameSlug}` : ""}
                      {count > 1 ? ` · ×${count}` : ""}
                      {item.launcherVersion ? ` · app ${item.launcherVersion}` : ""}
                      {item.platform ? ` · ${item.platform}` : ""}
                      {item.pageUrl ? (
                        <>
                          {" · "}
                          <a
                            href={item.pageUrl}
                            target="_blank"
                            rel="noreferrer"
                            className="font-semibold text-primary hover:underline"
                          >
                            page
                          </a>
                        </>
                      ) : null}
                      {item.autoGenerated && (item.gameSlug || isCommunityServer) ? (
                        <>
                          {" · "}
                          <Link
                            href={opsHref}
                            className="font-semibold text-primary hover:underline"
                          >
                            ops
                          </Link>
                        </>
                      ) : null}
                      {isCommunityServer ? (
                        <>
                          {" · "}
                          <Link
                            href="/admin/connect/game-servers"
                            className="font-semibold text-primary hover:underline"
                          >
                            servers
                          </Link>
                        </>
                      ) : null}
                    </p>
                    {(item.editionSlug ||
                      item.phase ||
                      item.osVersion ||
                      item.architecture ||
                      item.exitCode != null) && (
                      <div className="mt-2 flex flex-wrap gap-1.5">
                        {item.editionSlug ? <Chip>edition {item.editionSlug}</Chip> : null}
                        {item.phase ? <Chip>phase {item.phase}</Chip> : null}
                        {item.osVersion ? <Chip>os {item.osVersion}</Chip> : null}
                        {item.architecture ? <Chip>arch {item.architecture}</Chip> : null}
                        {item.exitCode != null ? <Chip>exit {item.exitCode}</Chip> : null}
                      </div>
                    )}
                  </div>
                  <span className="rounded-full bg-secondary px-2.5 py-0.5 text-[11px] font-bold uppercase tracking-wide">
                    {BUG_REPORT_STATUS_LABELS[item.status]}
                  </span>
                </div>
                <p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{item.description}</p>
                {samples.length > 1 ? (
                  <div className="mt-2 space-y-1">
                    <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                      Message samples
                    </p>
                    <ul className="space-y-1 text-xs text-muted-foreground">
                      {samples.map((sample, idx) => (
                        <li key={`${idx}-${sample.slice(0, 24)}`} className="rounded-md bg-muted/40 px-2 py-1">
                          {sample}
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : null}
                <p className="mt-2 text-xs text-muted-foreground">
                  {item.submitterName ?? "Anonymous"}
                  {item.contactEmail ? ` · ${item.contactEmail}` : ""}
                  {" · first "}
                  <LocalTime value={new Date(item.createdAt).toISOString()} />
                  {item.autoGenerated || count > 1 ? (
                    <>
                      {" · last "}
                      <LocalTime value={new Date(seen).toISOString()} />
                    </>
                  ) : null}
                </p>
                <BugReportActions
                  item={{
                    _id: String(item._id),
                    status: item.status,
                    adminNotes: item.adminNotes,
                  }}
                />
              </article>
            );
          })}
        </div>
      )}
    </div>
  );
}
