/**
 * Catalog additions — wave 2.
 *
 * Same contract as add-games-wave-1.ts: INSERT-ONLY (an existing slug is left
 * completely alone), games land as drafts, mods are published. See that file
 * for the full rationale — this one only notes what's different.
 *
 * Every game here is free-to-play and has a Steam listing, so licence and
 * steamAppId were easy. launcherInstall is "external" for all twenty-five,
 * even the handful where a live, unauthenticated installer URL was found
 * (Albion, GW2, LOTRO, DCUO, SWTOR, Goose Goose Duck, World of Sea Battle,
 * Old School RuneScape). Two things ruled out using those directly:
 *
 *   - The launcher's "direct-exe" kind treats the downloaded file AS the
 *     game (copies it into the game dir and marks it installed) — none of
 *     these are portable single-exe games, they're all installer wizards.
 *   - The launcher's "direct-installer" kind runs the installer, then needs
 *     knownExePaths or registryTitles to detect a finished install; its own
 *     self-test (`npm run test:resolve` in launcher/) fails an entry missing
 *     both. Guessing an install path or a registry DisplayName is exactly
 *     the kind of unverifiable field the accuracy bar rules out — wrong
 *     metadata here reproduces the enum-trap problem this wave is supposed
 *     to avoid, just one layer down (a game that reports "installed" when it
 *     isn't, or never resolves at all).
 *
 * So every entry deep-links to Steam instead, which deriveVirtualEdition()
 * in src/lib/editions.ts already prefers once launcherInstall.kind is
 * "external": it falls through to the steamAppId branch and the game page
 * shows "Open in Steam". Genuine one-click support for the installer-based
 * titles above is a real upgrade path, but it wants someone who can actually
 * run each installer on Windows and read back the real install path or
 * uninstall-registry title first.
 *
 * EVE Online and THE FINALS publish no storage figure on either their Steam
 * page or their own site's requirements section — sizeMB for both comes from
 * the requester directly (24 GB and 85 GB) rather than a public source.
 *
 * "Star Wars: Knights of the Old Republic" on the original list turned out to
 * mean Star Wars: The Old Republic (SWTOR), the free-to-play BioWare MMO —
 * confirmed with the requester. The 2003 single-player KOTOR is a $9.99
 * premium title with no free tier, a different game from everything else in
 * this wave.
 *
 * Usage:
 *   npx tsx scripts/add-games-wave-2.ts                       # dry run
 *   npx tsx scripts/add-games-wave-2.ts --apply
 *   npx tsx scripts/add-games-wave-2.ts --apply --soft-fail   # the build
 */
import { loadEnvConfig } from "@next/env";

loadEnvConfig(process.cwd());

type DeveloperSeed = {
  slug: string;
  name: string;
  tagline: string;
  about: string;
  founded: number;
  location: string;
  website: string;
  artHue: number;
  published: boolean;
};

const DEVELOPERS: DeveloperSeed[] = [
  {
    slug: "thatgamecompany",
    name: "thatgamecompany",
    tagline: "Studio behind Sky: Children of the Light and Journey.",
    about: "Independent studio known for emotionally driven, wordless multiplayer games.",
    founded: 0,
    location: "Santa Monica, California",
    website: "https://thatgamecompany.com",
    artHue: 200,
    published: true,
  },
  {
    slug: "sandbox-interactive",
    name: "Sandbox Interactive",
    tagline: "Developer of the player-driven sandbox MMO Albion Online.",
    about: "Berlin studio built around a single long-running project: a classless, full-loot sandbox MMO.",
    founded: 0,
    location: "Berlin, Germany",
    website: "https://albiononline.com",
    artHue: 40,
    published: true,
  },
  {
    slug: "darkflow-software",
    name: "Darkflow Software",
    tagline: "Developer of Enlisted, published by Gaijin.",
    about: "Studio behind Enlisted's large-scale WWII squad combat, part of the Gaijin family of titles.",
    founded: 0,
    location: "Russia",
    website: "https://enlisted.net",
    artHue: 25,
    published: true,
  },
  {
    slug: "ubisoft-montreal",
    name: "Ubisoft Montreal",
    tagline: "Developer of Tom Clancy's Rainbow Six Siege.",
    about: "Ubisoft's flagship Montreal studio, running Siege as a live tactical shooter for a decade-plus.",
    founded: 0,
    location: "Montreal, Canada",
    website: "https://www.ubisoft.com",
    artHue: 210,
    published: true,
  },
  {
    slug: "everstone-studio",
    name: "Everstone Studio",
    tagline: "Developer of the wuxia open world Where Winds Meet.",
    about: "Studio behind Where Winds Meet, an open-world martial-arts RPG set in ancient China.",
    founded: 0,
    location: "China",
    website: "https://www.wherewindsmeetgame.com",
    artHue: 350,
    published: true,
  },
  {
    slug: "starry-studio",
    name: "Starry Studio",
    tagline: "Developer of the survival MMO Once Human.",
    about: "Studio behind Once Human, a multiplayer survival game set after a reality-warping apocalypse.",
    founded: 0,
    location: "China",
    website: "https://www.oncehuman.game",
    artHue: 160,
    published: true,
  },
  {
    slug: "grinding-gear-games",
    name: "Grinding Gear Games",
    tagline: "Developer of the free action RPG Path of Exile.",
    about: "New Zealand studio behind Path of Exile, an online action RPG built on deep, player-driven itemization.",
    founded: 0,
    location: "Auckland, New Zealand",
    website: "https://www.pathofexile.com",
    artHue: 275,
    published: true,
  },
  {
    slug: "singularity-6",
    name: "Singularity 6 Corporation",
    tagline: "Developer of the cozy life-sim MMO Palia.",
    about: "Studio behind Palia, a free-to-play community life simulator with light MMO systems.",
    founded: 0,
    location: "Los Angeles, California",
    website: "https://www.palia.com",
    artHue: 140,
    published: true,
  },
  {
    slug: "arenanet",
    name: "ArenaNet",
    tagline: "Developer of Guild Wars and Guild Wars 2.",
    about: "Long-running studio behind the Guild Wars franchise, known for buy-to-play MMOs with no subscription.",
    founded: 0,
    location: "Bellevue, Washington",
    website: "https://www.guildwars2.com",
    artHue: 15,
    published: true,
  },
  {
    slug: "fishing-planet-llc",
    name: "Fishing Planet LLC",
    tagline: "Developer of the realistic fishing sim Fishing Planet.",
    about: "Studio dedicated to a single title: a first-person multiplayer fishing simulator built by anglers.",
    founded: 0,
    location: "United States",
    website: "https://www.fishingplanet.com",
    artHue: 195,
    published: true,
  },
  {
    slug: "cryptic-studios",
    name: "Cryptic Studios",
    tagline: "Developer of Star Trek Online, published by Arc Games.",
    about: "Studio behind Star Trek Online, a long-running MMO built on Cryptic's own engine and mission tools.",
    founded: 0,
    location: "Los Gatos, California",
    website: "https://www.playstartrekonline.com",
    artHue: 230,
    published: true,
  },
  {
    slug: "thera-interactive",
    name: "Thera Interactive",
    tagline: "Developer of the naval MMO World of Sea Battle.",
    about: "Studio behind World of Sea Battle, an open-world naval combat MMO set in the age of sail.",
    founded: 0,
    location: "Unknown",
    website: "https://www.worldofseabattle.com",
    artHue: 205,
    published: true,
  },
  {
    slug: "mob-entertainment",
    name: "Mob Entertainment",
    tagline: "Developer of the Poppy Playtime series.",
    about: "Studio behind the Poppy Playtime horror-puzzle series, released chapter by chapter.",
    founded: 0,
    location: "United States",
    website: "https://www.mobentertainment.com",
    artHue: 350,
    published: true,
  },
  {
    slug: "nadeo",
    name: "Nadeo",
    tagline: "Developer of the Trackmania series, part of Ubisoft.",
    about: "French studio behind Trackmania, focused on precision stunt racing and player-made tracks.",
    founded: 0,
    location: "Paris, France",
    website: "https://www.trackmania.com",
    artHue: 95,
    published: true,
  },
  {
    slug: "dimensional-ink-games",
    name: "Dimensional Ink Games",
    tagline: "Developer of DC Universe Online, published by Daybreak.",
    about: "Studio behind DC Universe Online, a superhero action MMO set in the DC universe.",
    founded: 0,
    location: "Austin, Texas",
    website: "https://www.dcuniverseonline.com",
    artHue: 50,
    published: true,
  },
  {
    slug: "standing-stone-games",
    name: "Standing Stone Games",
    tagline: "Developer of The Lord of the Rings Online.",
    about: "Studio behind LOTRO, an MMO built around a direct recreation of Tolkien's Middle-earth.",
    founded: 0,
    location: "Boston, Massachusetts",
    website: "https://www.lotro.com",
    artHue: 45,
    published: true,
  },
  {
    slug: "broadsword",
    name: "Broadsword",
    tagline: "Developer of Star Wars: The Old Republic, published by EA.",
    about: "Studio that took over development of SWTOR from BioWare, continuing its story-driven MMO seasons.",
    founded: 0,
    location: "Austin, Texas",
    website: "https://www.swtor.com",
    artHue: 0,
    published: true,
  },
  {
    slug: "gaggle-studios",
    name: "Gaggle Studios, Inc.",
    tagline: "Developer of the social deduction game Goose Goose Duck.",
    about: "Studio behind Goose Goose Duck, a large-lobby social deduction game with rotating game modes.",
    founded: 0,
    location: "United States",
    website: "https://gaggle.fun",
    artHue: 55,
    published: true,
  },
  {
    slug: "gameloft",
    name: "Gameloft",
    tagline: "Developer of the Asphalt racing series.",
    about: "Long-running mobile and PC studio behind the Asphalt arcade racing franchise.",
    founded: 0,
    location: "Paris, France",
    website: "https://www.gameloft.com",
    artHue: 15,
    published: true,
  },
  {
    slug: "jagex",
    name: "Jagex Ltd",
    tagline: "Developer of RuneScape and Old School RuneScape.",
    about: "Cambridge studio behind RuneScape, running Old School RuneScape as a community-voted 2007-era build.",
    founded: 0,
    location: "Cambridge, United Kingdom",
    website: "https://oldschool.runescape.com",
    artHue: 40,
    published: true,
  },
  {
    slug: "pablo-leban",
    name: "Pablo Leban",
    tagline: "Solo developer of the idle RPG Idle Slayer.",
    about: "Independent developer behind Idle Slayer, an idle game with active combat layered on top of the numbers.",
    founded: 0,
    location: "Unknown",
    website: "https://idleslayer.com",
    artHue: 265,
    published: true,
  },
  {
    slug: "oddshot-games",
    name: "Oddshot Games",
    tagline: "Developer of the multiplayer football game Strikers Club.",
    about: "Studio behind Strikers Club, a physics-based one-player-per-team football game in Early Access.",
    founded: 0,
    location: "Unknown",
    website: "https://strikersclub.gg",
    artHue: 130,
    published: true,
  },
  {
    slug: "suncyan",
    name: "SUNCYAN Inc.",
    tagline: "Developer of the volleyball game The Spike Cross.",
    about: "Studio dedicated to volleyball games, built around the feel of a well-timed spike.",
    founded: 0,
    location: "South Korea",
    website: "https://www.suncyan.com",
    artHue: 200,
    published: true,
  },
  {
    slug: "whalefall",
    name: "Whalefall",
    tagline: "Developer of the point-and-click adventure Poco.",
    about: "Studio behind Poco, a 2D/3D hybrid point-and-click adventure about the world's smallest clown.",
    founded: 0,
    location: "Unknown",
    website: "https://store.steampowered.com/app/3454610/Poco/",
    artHue: 300,
    published: true,
  },
  {
    slug: "devclerk",
    name: "Devclerk",
    tagline: "Small team behind the guild-management sim Ye Guild Clerk!",
    about: "Small team behind Ye Guild Clerk!, a guild-counter management sim about outfitting animal adventurers.",
    founded: 0,
    location: "Unknown",
    website: "https://linktr.ee/yeguildclerk",
    artHue: 35,
    published: true,
  },
  {
    slug: "fenris-creations",
    // Steam and eveonline.com's own footer both list "Fenris Creations" as
    // the current EVE Online developer/publisher entity, not CCP Games.
    name: "Fenris Creations",
    tagline: "Developer of EVE Online.",
    about: "The entity behind EVE Online, a player-driven space MMO running continuously since 2003.",
    founded: 0,
    location: "Iceland",
    website: "https://www.eveonline.com",
    artHue: 220,
    published: true,
  },
  {
    slug: "embark-studios",
    name: "Embark Studios",
    tagline: "Developer of THE FINALS.",
    about: "Stockholm studio behind THE FINALS, a physics-driven, fully-destructible arena shooter.",
    founded: 0,
    location: "Stockholm, Sweden",
    website: "https://www.embark-studios.com",
    artHue: 15,
    published: true,
  },
];

const GAMES = [
  {
    slug: "sky-children-of-the-light",
    title: "Sky: Children of the Light",
    tagline: "A wordless multiplayer adventure about flight, light, and quiet kindness.",
    description:
      "An open-world adventure from the makers of Journey. Fly, glide and explore floating realms as a small cloaked spirit, meeting strangers who become companions through gesture and shared candlelight rather than chat. Seasonal events and cosmetic quests keep the world changing, but the core loop stays gentle: restore the light, help who you meet, ask for nothing back.",
    developerSlug: "thatgamecompany",
    developerName: "thatgamecompany",
    genres: ["Adventure", "MMO"],
    tags: ["Open World", "Multiplayer", "Family Friendly"],
    aliases: ["Sky CotL", "Sky"],
    license: "Free to Play",
    releaseYear: 2024,
    sizeMB: 3000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Cross-play", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.thatskygame.com/",
    steamAppId: "2325290",
    art: { from: "#0c4a6e", to: "#fde68a", icon: "Sparkles" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2325290/ddbf1ae47d8a782280a99c97e2e4cfe882d1adaa/header_alt_assets_2.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2325290/8c78bdadb6a0fd9b77a3754831165708d153aa64/ss_8c78bdadb6a0fd9b77a3754831165708d153aa64.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/2325290/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "albion-online",
    title: "Albion Online",
    tagline: "A classless sandbox MMO with full-loot PvP and a player-run economy.",
    description:
      "A cross-platform sandbox MMORPG with no fixed classes — every piece of gear you equip determines what you can do, so build identity comes entirely from choice. Nearly everything usable is player-crafted, and the economy runs on resources fought over in a world where losing a fight can mean losing your gear. Territory control and guild warfare sit on top of a deep, patient crafting game.",
    developerSlug: "sandbox-interactive",
    developerName: "Sandbox Interactive",
    genres: ["MMO", "RPG"],
    tags: ["Sandbox", "PvP", "Open World", "Fantasy"],
    aliases: ["Albion"],
    license: "Free to Play",
    releaseYear: 2018,
    sizeMB: 2000,
    platforms: ["Windows", "macOS", "Linux"],
    features: ["Multiplayer", "Cross-play"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://albiononline.com",
    steamAppId: "761890",
    art: { from: "#78350f", to: "#fbbf24", icon: "Swords" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/761890/ea5ce1793872e23cc9ce82ac1f317869c67469b6/header_alt_assets_2.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/761890/ss_5a6a5a67bd8dc8661374b825521411f00912e4c7.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows, macOS or Linux. See Steam page for full specification.",
      recommended: "64-bit Windows, macOS or Linux. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/761890/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "enlisted",
    title: "Enlisted",
    tagline: "A World War II MMO shooter where you command a whole squad, not just yourself.",
    description:
      "A squad-based WWII shooter from the Gaijin family of titles: instead of controlling one soldier, you command an AI squad alongside your own character across historically staged battles with hundreds of players, tanks and aircraft per match. Campaigns cover Moscow, Normandy, Berlin and the Pacific, each with its own weapon and vehicle roster.",
    developerSlug: "darkflow-software",
    developerName: "Darkflow Software",
    genres: ["FPS", "MMO"],
    tags: ["World War II", "Squad Based", "Multiplayer"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2024,
    sizeMB: 49000,
    platforms: ["Windows", "Linux"],
    features: ["Multiplayer", "Co-op", "Cross-play", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://enlisted.net",
    steamAppId: "2051620",
    art: { from: "#292524", to: "#a16207", icon: "Crosshair" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2051620/60ad41a592c49b3ccc298380b5d7ea4f28158af8/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2051620/ss_3af5885c5d82652d7c7f2d2dd471a5b291b68dbe.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows or Linux. See Steam page for full specification.",
      recommended: "64-bit Windows or Linux. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/2051620/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "rainbow-six-siege",
    title: "Tom Clancy's Rainbow Six Siege",
    tagline: "A tactical, destruction-driven team shooter built around planning and execution.",
    description:
      "A five-versus-five tactical shooter where every operator brings a distinct gadget and every wall, floor and ceiling can be breached, reinforced or turned into a firing line. Rounds are short and unforgiving — one life per round, information and positioning matter more than reflexes — which has kept it a fixture of competitive shooter play for a decade-plus of seasonal content.",
    developerSlug: "ubisoft-montreal",
    developerName: "Ubisoft Montreal",
    genres: ["FPS"],
    tags: ["Tactical", "Competitive", "Multiplayer", "Destruction"],
    aliases: ["R6", "Siege", "R6S"],
    license: "Free to Play",
    releaseYear: 2015,
    sizeMB: 65000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "http://rainbow6.ubi.com/",
    steamAppId: "359550",
    art: { from: "#1c1917", to: "#f97316", icon: "Crosshair" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/359550/cd31c5a197317624687ad580af592e6404d13581/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/359550/ef9bc694ff724b3d64ac37968f35f9a6ec4c766a/ss_ef9bc694ff724b3d64ac37968f35f9a6ec4c766a.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/359550/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "where-winds-meet",
    title: "Where Winds Meet",
    tagline: "An open-world wuxia RPG about rising from wanderer to sword master.",
    description:
      "An open-world action RPG set in a martial-arts vision of ancient China. You start as a nobody drifting into a war-torn capital and work up through fighting styles, faction politics and a large, densely detailed world — free to play the hero, the villain, or something messier in between. Combat is fast and stance-based, built around chaining martial arts schools rather than a single weapon kit.",
    developerSlug: "everstone-studio",
    developerName: "Everstone Studio",
    genres: ["Action", "RPG"],
    tags: ["Open World", "Martial Arts", "Fantasy"],
    aliases: ["WWM"],
    license: "Free to Play",
    releaseYear: 2025,
    sizeMB: 130000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Cross-play", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.wherewindsmeetgame.com/",
    steamAppId: "3564740",
    art: { from: "#7f1d1d", to: "#fca5a5", icon: "Swords" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3564740/e78afb6db40bf0c0d4ed31df8f6ce65fa89f741d/header_alt_assets_8.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3564740/8e15fb0595c13e25e221f58ee49823e77551b277/ss_8e15fb0595c13e25e221f58ee49823e77551b277.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/3564740/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "once-human",
    title: "Once Human",
    tagline: "A survival MMO where reality itself has started to break down.",
    description:
      "An open-world survival game set after an event that let human will physically reshape reality, spawning monstrous Deviants out of everyday objects and warped land. You build and defend territory, gather and craft against escalating threats, and take on story-driven factions alongside other players in a world that keeps mutating around you.",
    developerSlug: "starry-studio",
    developerName: "Starry Studio",
    genres: ["Survival", "MMO"],
    tags: ["Survival", "Crafting", "Open World", "Co-op"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2024,
    sizeMB: 100000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.oncehuman.game/",
    steamAppId: "2139460",
    art: { from: "#164e63", to: "#a3e635", icon: "Skull" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2139460/c18b08a2f93dec32fcc5fa71bc2da44ee42de1f0/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2139460/d4a1bcb2b2ce32e46fed9f6b0d5024762bfa5cc2/ss_d4a1bcb2b2ce32e46fed9f6b0d5024762bfa5cc2.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/2139460/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "path-of-exile",
    title: "Path of Exile",
    tagline: "A free, deep action RPG built around player-driven itemization.",
    description:
      "An online action RPG set on the grim continent of Wraeclast, where a sprawling passive skill tree and a gem-socket skill system let a single class play as radically different builds. It's genuinely free — cosmetics and stash space are the only purchases — and leans hard into seasonal leagues that rework mechanics every few months rather than sitting still.",
    developerSlug: "grinding-gear-games",
    developerName: "Grinding Gear Games",
    genres: ["RPG", "MMO"],
    tags: ["Dark Fantasy", "Loot", "Multiplayer"],
    aliases: ["PoE"],
    license: "Free to Play",
    releaseYear: 2013,
    sizeMB: 40000,
    platforms: ["Windows", "macOS"],
    features: ["Multiplayer", "Co-op", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.pathofexile.com",
    steamAppId: "238960",
    art: { from: "#1c1917", to: "#b91c1c", icon: "Skull" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/238960/177c953b362c5a6221f9c15d340a0b1e2b8bfab8/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/238960/b8ed545404b1d53fb7db4866beb3eddbfe9fa707/ss_b8ed545404b1d53fb7db4866beb3eddbfe9fa707.1920x1080.jpg"],
    systemRequirements: {
      min: "Windows 10, quad-core 2.6GHz, 8 GB RAM, GeForce GTX 650 Ti / Radeon HD 7850, DirectX 11, 40 GB storage.",
      recommended: "Windows 10, quad-core 3.2GHz, 16 GB RAM, GeForce GTX 1050 Ti / Radeon RX560, DirectX 11, 40 GB SSD storage.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/238960/",
      note: "The standalone client requires a Grinding Gear Games account and login before it will download — free to play on Steam is the more reliable route.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "palia",
    title: "Palia",
    tagline: "A cozy community life sim about building the home you actually want.",
    description:
      "A free-to-play life simulator with light MMO trappings: farm, fish, forage, decorate and befriend a cast of villagers in a low-stakes, cooperative shared world. There's crafting depth and progression under the coziness, but no combat pressure — Palia is built for players who want a community sim they can drop into for twenty minutes or two hours.",
    developerSlug: "singularity-6",
    developerName: "Singularity 6 Corporation",
    genres: ["Simulation", "MMO"],
    tags: ["Cozy", "Life Sim", "Co-op", "Crafting"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2024,
    sizeMB: 22000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Cross-play"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.palia.com/",
    steamAppId: "2707930",
    art: { from: "#166534", to: "#fef08a", icon: "Sparkles" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2707930/9684b2812591bfafc0085adfd1e7128e9203385e/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2707930/6752d60d70558b1635e4c4e20bc78f949a93a53d/ss_6752d60d70558b1635e4c4e20bc78f949a93a53d.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/2707930/",
      note: "Free to play on Steam (also available on Epic Games) — the storefront handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "guild-wars-2",
    title: "Guild Wars 2",
    tagline: "A buy-to-play MMO with no subscription and fast, active combat.",
    description:
      "A long-running fantasy MMORPG praised for dropping the genre's usual subscription fee and tab-target combat alike: fights are mobile and reaction-based, and the base game and its first expansion are free to start. A huge, event-driven open world sits alongside competitive PvP and large-scale WvW warfare, with over a decade of expansions layered on top.",
    developerSlug: "arenanet",
    developerName: "ArenaNet",
    genres: ["MMO", "RPG"],
    tags: ["Open World", "Fantasy", "Action Combat"],
    aliases: ["GW2"],
    license: "Free to Play",
    releaseYear: 2022,
    sizeMB: 70000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.guildwars2.com/en/",
    steamAppId: "1284210",
    art: { from: "#312e81", to: "#f43f5e", icon: "Swords" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1284210/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1284210/ss_7f65b15609337bc9572dca6e8d8581b68eda5cc9.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows 7+, Intel i3 3.4GHz / AMD Athlon x4 3.8GHz, 8 GB RAM, GeForce GTX 680 / Radeon HD 7970, DirectX 11, 70 GB storage.",
      recommended: "See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/1284210/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "fishing-planet",
    title: "Fishing Planet",
    tagline: "A realistic, free-to-play first-person fishing simulator.",
    description:
      "A first-person multiplayer fishing sim built by anglers, aiming for real tackle physics, real fish behaviour and real bodies of water rather than an arcade minigame. Progress unlocks new lakes, rivers and species, and gear choice genuinely changes what you can catch — it's a slow, technical hobby game rather than a quick-session one.",
    developerSlug: "fishing-planet-llc",
    developerName: "Fishing Planet LLC",
    genres: ["Simulation", "Sports"],
    tags: ["Realistic", "Fishing", "Multiplayer"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2017,
    sizeMB: 14000,
    platforms: ["Windows", "macOS", "Linux"],
    features: ["Multiplayer", "Co-op", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.fishingplanet.com/",
    steamAppId: "380600",
    art: { from: "#0c4a6e", to: "#38bdf8", icon: "Cog" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/380600/893d67a3798c2483503a9a6ed758046f39ac0b57/header_alt_assets_16.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/380600/179ef6a59705abd3a97766e2d05f03eab5845714/ss_179ef6a59705abd3a97766e2d05f03eab5845714.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows, macOS or Linux. See Steam page for full specification.",
      recommended: "64-bit Windows, macOS or Linux. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/380600/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "star-trek-online",
    title: "Star Trek Online",
    tagline: "Command your own starship and crew across the Star Trek universe.",
    description:
      "A free-to-play MMORPG that puts you in the captain's chair of your own ship, mixing space combat with away-team missions on foot across a huge span of Star Trek canon — Federation, Klingon, Romulan and beyond. Over a decade of story seasons have accumulated, so there's a genuinely large campaign to work through alongside the usual endgame grind.",
    developerSlug: "cryptic-studios",
    developerName: "Cryptic Studios",
    genres: ["MMO", "RPG"],
    tags: ["Space", "Sci-Fi", "Multiplayer"],
    aliases: ["STO"],
    license: "Free to Play",
    releaseYear: 2012,
    sizeMB: 21000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.playstartrekonline.com/",
    steamAppId: "9900",
    art: { from: "#0f172a", to: "#6366f1", icon: "Rocket" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/9900/fa8e746fb3ca2075692935252ffed5d99aa9a518/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/9900/ss_94779a79b0f847ef9fe8c10349041e5c55a510ed.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows 10/11, Core 2 Duo 2.2GHz, 4 GB RAM, GeForce GTX 4xx / Radeon HD 5xxx, DirectX 11, 21 GB storage.",
      recommended: "64-bit Windows 10/11, Core i5-6xxx quad-core, 6 GB RAM, GeForce GTX 9xx / Radeon RX 4xx, DirectX 11, 21 GB storage.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/9900/",
      note: "The Arc Games client requires an account and login before it will download — free to play on Steam is the more reliable route.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "world-of-sea-battle",
    title: "World of Sea Battle",
    tagline: "An open-world naval MMO set in the Golden Age of Sail.",
    description:
      "An Early Access MMO about commanding historic sailing ships across an open ocean map, mixing PvP and PvE naval combat with an economy and guild-versus-guild territory control. It's a small studio's take on the naval-MMO niche, still filling out content while in Early Access.",
    developerSlug: "thera-interactive",
    developerName: "Thera Interactive",
    genres: ["MMO", "Pirate"],
    tags: ["Naval Combat", "Pirates", "PvP"],
    aliases: ["WoSB"],
    license: "Free to Play (Early Access)",
    releaseYear: 2025,
    sizeMB: 1000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.worldofseabattle.com/en",
    steamAppId: "2948190",
    art: { from: "#0c4a6e", to: "#facc15", icon: "Flag" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2948190/00cedbfad862733ac331538547cfbfc2a977cd38/header_alt_assets_1.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2948190/6dc8f189a082c2909e94dcb5086615446c27950b/ss_6dc8f189a082c2909e94dcb5086615446c27950b.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/2948190/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "poppy-playtime",
    title: "Poppy Playtime",
    tagline: "A horror-puzzle survival game set in an abandoned toy factory.",
    description:
      "A single-player horror-puzzle series set in the derelict Playtime Co. toy factory, where the mascots that used to sell toys are now hunting whoever's left. A wrist-mounted GrabPack for reaching, pulling and rewiring stands in for combat — this is a game about problem-solving under pressure, not fighting back. Steam's base listing covers the first chapter, with later chapters sold separately.",
    developerSlug: "mob-entertainment",
    developerName: "Mob Entertainment",
    genres: ["Horror", "Adventure"],
    tags: ["Horror", "Puzzle", "Singleplayer"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2021,
    sizeMB: 20000,
    platforms: ["Windows"],
    features: ["Singleplayer"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.mobentertainment.com/poppy-playtime",
    steamAppId: "1721470",
    art: { from: "#1c1917", to: "#dc2626", icon: "Skull" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1721470/00ca34a0c863a8d86c6582904249216d6aa263bd/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1721470/0f4e536a4d9b73e4038b7c7a4d3db88ae9433605/ss_0f4e536a4d9b73e4038b7c7a4d3db88ae9433605.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/1721470/",
      note: "Free on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "trackmania",
    title: "Trackmania",
    tagline: "Precision stunt racing across weekly, player-made tracks.",
    description:
      "A free-to-play arcade racer built for restarting instantly and shaving tenths of a second off a lap. Five distinct environments, an enormous back catalogue of player-made tracks, and weekly competitive campaigns keep it a live game rather than a fixed one — the appeal is entirely in mastering a track's exact rhythm, not in a story or a garage of cars.",
    developerSlug: "nadeo",
    developerName: "Nadeo",
    genres: ["Racing"],
    tags: ["Arcade Racing", "Competitive", "Multiplayer"],
    aliases: ["TM"],
    license: "Free to Play",
    releaseYear: 2023,
    sizeMB: 3000,
    platforms: ["Windows"],
    features: ["Multiplayer", "LAN Support", "Split-Screen Co-op"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.trackmania.com",
    steamAppId: "2225070",
    art: { from: "#14532d", to: "#84cc16", icon: "Flag" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2225070/7f7b095f71d8e3b54612927c0bb4b9f0713eac21/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2225070/9dfacbe2b15eb1526a757b59ecbbda9108bd4a5e/ss_9dfacbe2b15eb1526a757b59ecbbda9108bd4a5e.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/2225070/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "dc-universe-online",
    title: "DC Universe Online",
    tagline: "A free-to-play superhero action MMO set in the DC universe.",
    description:
      "An action-combat MMORPG where you build an original hero or villain, choose a power set inspired by Batman, Superman or the rest of the DC roster, and fight alongside — or against — them across Gotham, Metropolis and beyond. Combat is fast and mobile rather than tab-target, and over a decade of episodic content has piled up on top of the base game.",
    developerSlug: "dimensional-ink-games",
    developerName: "Dimensional Ink Games",
    genres: ["MMO", "RPG"],
    tags: ["Superhero", "Action Combat", "Multiplayer"],
    aliases: ["DCUO"],
    license: "Free to Play",
    releaseYear: 2011,
    sizeMB: 30000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Cross-play"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.dcuniverseonline.com/",
    steamAppId: "24200",
    art: { from: "#1e3a8a", to: "#facc15", icon: "Zap" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/24200/4341fdcb5f72c77c6fb4e0b169e9f52f47cdff9e/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/24200/ss_99116ecfec2858f6f24fcc33ae12ee731bccef60.1920x1080.jpg"],
    systemRequirements: {
      min: "Windows 7+, P4 3.0GHz or AMD equivalent, 1 GB RAM, GeForce 7800GTX+ / Radeon 1950+, 30 GB storage.",
      recommended: "See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/24200/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "lord-of-the-rings-online",
    title: "The Lord of the Rings Online",
    tagline: "A free-to-play MMO built as a direct recreation of Tolkien's Middle-earth.",
    description:
      "A long-running MMORPG that walks you through Middle-earth region by region, from the Shire to Mordor, with quest lines that closely track the events of the books rather than an original story bolted onto familiar geography. It's a slower, more traditional MMO than most on this list — deep class trees, housing, and a music system are as much a draw as combat.",
    developerSlug: "standing-stone-games",
    developerName: "Standing Stone Games",
    genres: ["MMO", "RPG"],
    tags: ["Fantasy", "Open World", "Story Driven"],
    aliases: ["LOTRO"],
    license: "Free to Play",
    releaseYear: 2012,
    sizeMB: 32000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.lotro.com/",
    steamAppId: "212500",
    art: { from: "#365314", to: "#facc15", icon: "Swords" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/212500/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/212500/14cb88d7e83bb005fff04e066932bc1e38d90d7d/ss_14cb88d7e83bb005fff04e066932bc1e38d90d7d.1920x1080.jpg"],
    systemRequirements: {
      min: "Windows 7 (64-bit recommended), Core 2 Duo / Athlon II, 2 GB RAM, GeForce 7XXX / Radeon HD 3000 with 512 MB VRAM, DirectX 9.0c, 32 GB storage.",
      recommended: "Windows 10, Core i7 / FX-8100, 4 GB RAM, GeForce 8XXX / Radeon HD 6### with 1 GB VRAM, DirectX 9.0c, 32 GB storage.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/212500/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "star-wars-the-old-republic",
    title: "Star Wars: The Old Republic",
    tagline: "A story-driven, free-to-play Star Wars MMO set millennia before the films.",
    description:
      "A BioWare-built MMORPG set three thousand years before the movies, where each of eight classes gets its own fully voiced story campaign — Jedi Knight, Sith Warrior, Bounty Hunter and more — before folding into shared endgame content. It's a free-to-play MMO that still plays like a BioWare RPG at its core: companions, dialogue choices, and light-side/dark-side consequences throughout.",
    developerSlug: "broadsword",
    developerName: "Broadsword",
    genres: ["MMO", "RPG"],
    tags: ["Sci-Fi", "Story Driven", "Multiplayer"],
    aliases: ["SWTOR", "TOR"],
    license: "Free to Play",
    releaseYear: 2020,
    sizeMB: 75000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.swtor.com/",
    steamAppId: "1286830",
    art: { from: "#450a0a", to: "#ef4444", icon: "Rocket" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1286830/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1286830/ss_582b40b9dea8273368826afd425f541aa859bbe6.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows 10+, AMD Athlon 64 X2 4000+ / Core 2 Duo 2.0GHz, 6 GB RAM, 1 GB VRAM with Shader 3.0 (Intel HD 3000 / Radeon HD 7450 / GeForce 610 or better), 75 GB storage.",
      recommended: "See swtor.com for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/1286830/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "goose-goose-duck",
    title: "Goose Goose Duck",
    tagline: "A large-lobby social deduction game with rotating modes and disguises.",
    description:
      "A social deduction game for up to sixteen players, in the lineage of Among Us but built around a bigger roster of roles, disguises and side objectives layered on top of the classic find-the-impostor loop. Frequent rotating game modes keep matches from settling into a single solved strategy.",
    developerSlug: "gaggle-studios",
    developerName: "Gaggle Studios, Inc.",
    genres: ["Social Deduction"],
    tags: ["Social Deduction", "Party", "Multiplayer"],
    aliases: ["GGD"],
    license: "Free to Play",
    releaseYear: 2021,
    sizeMB: 400,
    platforms: ["Windows", "macOS"],
    features: ["Multiplayer", "Co-op", "Cross-play", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://gaggle.fun/goose-goose-duck",
    steamAppId: "1568590",
    art: { from: "#facc15", to: "#fef9c3", icon: "Target" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1568590/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1568590/414b9c3c2873d25c9c91ed355d01f8688eeb43d7/ss_414b9c3c2873d25c9c91ed355d01f8688eeb43d7.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows or macOS. See Steam page for full specification.",
      recommended: "64-bit Windows or macOS. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/1568590/",
      note: "Free to play on Steam — Steam handles the download and install. A direct .exe is also published at gaggle.fun/goose-goose-duck for players who prefer not to use Steam.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "asphalt-legends",
    title: "Asphalt Legends",
    tagline: "An arcade racer built for hypercars, stunts, and short, intense races.",
    description:
      "The current entry in Gameloft's long-running arcade racing series, built around short races full of nitro boosts, mid-air stunts and a large roster of licensed hypercars rather than simulation handling. Cross-play with the mobile version keeps the player base merged across platforms.",
    developerSlug: "gameloft",
    developerName: "Gameloft",
    genres: ["Racing", "Arcade"],
    tags: ["Arcade Racing", "Mobile Friendly", "Multiplayer"],
    aliases: ["Asphalt 9", "Asphalt Legends Unite"],
    license: "Free to Play",
    releaseYear: 2022,
    sizeMB: 10000,
    platforms: ["Windows", "macOS"],
    features: ["Multiplayer", "Co-op", "Cross-play", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://asphaltlegends.com/",
    steamAppId: "1815780",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA9HM",
    art: { from: "#7c2d12", to: "#fb923c", icon: "Flag" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1815780/62d97fdca8328c041820e8dfa3cf4997d68881ab/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1815780/8c8b7d36598774eb2658757467ec24ec3c52b489/ss_8c8b7d36598774eb2658757467ec24ec3c52b489.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows or macOS. See Steam page for full specification.",
      recommended: "64-bit Windows or macOS. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/1815780/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "old-school-runescape",
    title: "Old School RuneScape",
    tagline: "The 2007-era build of RuneScape, shaped ever since by player votes.",
    description:
      "A preserved, community-governed build of RuneScape as it was in 2007, kept alive by Jagex and steered ever since by player polls that decide what content actually ships. It's the same open, quest-and-skill-driven fantasy world longtime players remember, still receiving regular updates that have to clear a supermajority vote first.",
    developerSlug: "jagex",
    developerName: "Jagex Ltd",
    genres: ["MMO", "RPG"],
    tags: ["Classic", "Fantasy", "Open World"],
    aliases: ["OSRS"],
    license: "Free to Play",
    releaseYear: 2021,
    sizeMB: 2000,
    platforms: ["Windows", "macOS"],
    features: ["Multiplayer", "Cross-play"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://oldschool.runescape.com/",
    steamAppId: "1343370",
    art: { from: "#713f12", to: "#eab308", icon: "Landmark" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1343370/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1343370/ss_fab277591d7bc78c3f1839fbe4e79b02a506add9.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows 10+. See Steam page for full specification.",
      recommended: "Windows 10+, Intel i3-6100 or AMD Ryzen, 8 GB RAM, GeForce GTX 600 series / Radeon R7 260, 2 GB storage.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/1343370/",
      note: "Free to play on Steam — Steam handles the download and install. A direct installer is also published at runescape.com/downloads.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "idle-slayer",
    title: "Idle Slayer",
    tagline: "An idle RPG with real combat layered under the number-go-up loop.",
    description:
      "An idle game that doesn't stop at leaving numbers to grow offline — you actively dash, dodge and swing through dungeons on top of the usual upgrade tree, collecting souls and gear that keep paying off whether you're playing or not. Cross-progression with the mobile version means one save follows you between platforms.",
    developerSlug: "pablo-leban",
    developerName: "Pablo Leban",
    genres: ["Idle"],
    tags: ["Idle", "Clicker", "Singleplayer"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2020,
    sizeMB: 100,
    platforms: ["Windows"],
    features: ["Singleplayer"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://idleslayer.com",
    steamAppId: "1353300",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.pabloleban.IdleSlayer",
    iosStoreUrl: "https://apps.apple.com/us/app/idle-slayer/id1526599527",
    art: { from: "#4c1d95", to: "#a78bfa", icon: "Zap" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1353300/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1353300/d20a28895c4e86a3182bedecc1ca72bc615bef52/ss_d20a28895c4e86a3182bedecc1ca72bc615bef52.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/1353300/",
      note: "Free to play on Steam, iOS and Android — the storefront handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "strikers-club",
    title: "Strikers Club",
    tagline: "A physics-based multiplayer football game, one player per team member.",
    description:
      "A multiplayer football game in Early Access where each player controls exactly one athlete rather than a whole team, so dribbling, passing and shooting all come down to individual physics-based control instead of AI-assisted formations. Matches lean on real coordination between teammates rather than a single star carrying the team.",
    developerSlug: "oddshot-games",
    developerName: "Oddshot Games",
    genres: ["Sports"],
    tags: ["Physics Based", "Multiplayer", "Competitive"],
    aliases: [],
    license: "Free to Play (Early Access)",
    releaseYear: 2026,
    sizeMB: 2000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://strikersclub.gg",
    steamAppId: "1952920",
    art: { from: "#14532d", to: "#4ade80", icon: "Target" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1952920/134cf5a567b4ee04a70712a786b5a5a4bf536647/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1952920/4a3127635014cb5a9f740a6ca712c5b6dc04ad5c/ss_4a3127635014cb5a9f740a6ca712c5b6dc04ad5c.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/1952920/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "the-spike-cross",
    title: "The Spike Cross",
    tagline: "A volleyball game built entirely around the thrill of the spike.",
    description:
      "An indie volleyball game from a developer who, by their own account, just loves volleyball — built around getting the timing and power of a spike to actually feel good, with local and online matches on top.",
    developerSlug: "suncyan",
    developerName: "SUNCYAN Inc.",
    genres: ["Sports"],
    tags: ["Volleyball", "Arcade", "Multiplayer"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2025,
    sizeMB: 1000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Split-Screen Co-op"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://store.steampowered.com/app/3983810/The_Spike_Cross/",
    steamAppId: "3983810",
    art: { from: "#0369a1", to: "#fbbf24", icon: "Target" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3983810/8c3b601b67c3cd20f1c63bf9a042ed16622fbc29/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3983810/ae8572db5ca31fe0e994d95cd16b00279ae21b1b/ss_ae8572db5ca31fe0e994d95cd16b00279ae21b1b.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/3983810/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "poco",
    title: "Poco",
    tagline: "A 2D/3D point-and-click adventure about the world's smallest clown.",
    description:
      "A charming point-and-click adventure about Poco, a two-inch-tall clown banished from a travelling circus into a cluttered, overgrown Below World. You explore, solve environmental puzzles and befriend the local homunculi while working out how to get back to the circus — a hybrid of 2D backgrounds and 3D characters gives it a distinct, storybook look.",
    developerSlug: "whalefall",
    developerName: "Whalefall",
    genres: ["Adventure"],
    tags: ["Point And Click", "2D", "Singleplayer"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2025,
    sizeMB: 1000,
    platforms: ["Windows", "macOS"],
    features: ["Singleplayer"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://store.steampowered.com/app/3454610/Poco/",
    steamAppId: "3454610",
    art: { from: "#581c87", to: "#f0abfc", icon: "Sparkles" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3454610/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3454610/ss_1fea85e63af8a7e120a22b48b857929f58aebdb5.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows or macOS. See Steam page for full specification.",
      recommended: "64-bit Windows or macOS. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/3454610/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "ye-guild-clerk",
    title: "Ye Guild Clerk!",
    tagline: "Run the counter at an Adventurer's Guild, one animal client at a time.",
    description:
      "A management sim where you're not the hero — you're the clerk behind the counter, handing out quests, gold and equipment to a cast of animal adventurers. Every counter decision nudges their stories one way or another, for better or worse, in a small, cozy loop about being the person who keeps the guild running.",
    developerSlug: "devclerk",
    developerName: "Devclerk",
    genres: ["Simulation"],
    tags: ["Management", "Cozy", "Singleplayer"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2025,
    sizeMB: 1000,
    platforms: ["Windows"],
    features: ["Singleplayer"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://store.steampowered.com/app/3715020/Ye_Guild_Clerk/",
    steamAppId: "3715020",
    art: { from: "#78350f", to: "#fde047", icon: "Cog" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3715020/4a9ba3838aa3e7ff4bd39e89736f911b7e2755cd/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3715020/536936925b32732cc0927eeef401a5a142408567/ss_536936925b32732cc0927eeef401a5a142408567.1920x1080.jpg"],
    systemRequirements: {
      min: "64-bit Windows. See Steam page for full specification.",
      recommended: "64-bit Windows. See Steam page for full specification.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/3715020/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "eve-online",
    title: "EVE Online",
    tagline: "A player-driven space MMO of trade, war and economy across 7,000 star systems.",
    description:
      "A single-shard space MMO running continuously since 2003, where nearly everything — ships, stations, the market, the wars — is built and fought over by players rather than scripted content. Explore, mine, trade, manufacture, or fly with a corporation into massive fleet battles; the same economy and the same consequences apply to everyone in the universe at once.",
    developerSlug: "fenris-creations",
    developerName: "Fenris Creations",
    genres: ["MMO", "Space"],
    tags: ["Space", "Sci-Fi", "Sandbox"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2010,
    sizeMB: 24000,
    platforms: ["Windows", "macOS"],
    features: ["Multiplayer", "Co-op"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.eveonline.com/",
    steamAppId: "8500",
    art: { from: "#0f172a", to: "#6366f1", icon: "Rocket" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/8500/fed1ea9b01dd6564101518a5201740fb44929fb4/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/8500/ca5a6945b485a33386789bb535ee275ebab3d275/ss_ca5a6945b485a33386789bb535ee275ebab3d275.1920x1080.jpg"],
    systemRequirements: {
      min: "Windows 10 64-bit, Intel or AMD Dual Core @ 2.0 GHz, 4 GB RAM, AMD Radeon 5450 / NVIDIA GeForce 420 with 1024 MB VRAM, 24 GB storage.",
      recommended: "Windows 11, Intel i7-7700 or AMD Ryzen 7 1700 @ 3.6 GHz, 16 GB RAM, GeForce GTX 1060 / Radeon RX 580 with 4 GB VRAM, 24 GB storage.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/8500/",
      note: "Free to play on Steam — Steam handles the download and install. A direct launcher download is also published at eveonline.com/download.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
  {
    slug: "the-finals",
    title: "THE FINALS",
    tagline: "A physics-driven, fully-destructible arena shooter staged as a gameshow.",
    description:
      "A free-to-play first-person shooter built on total environmental destruction — walls, floors and whole buildings come apart mid-fight, so no two rounds play out on the same map twice. Small squads compete for cash on a future gameshow stage, with a class-and-gadget loadout system that rewards using the arena itself as a weapon.",
    developerSlug: "embark-studios",
    developerName: "Embark Studios",
    genres: ["FPS"],
    tags: ["Arena Shooter", "Destruction", "Competitive"],
    aliases: [],
    license: "Free to Play",
    releaseYear: 2023,
    sizeMB: 85000,
    platforms: ["Windows"],
    features: ["Multiplayer", "Co-op", "Cross-play", "Controller Support"],
    launchMethods: ["install"],
    browserPlayable: false,
    steamDeck: false,
    website: "https://www.reachthefinals.com/",
    steamAppId: "2073850",
    art: { from: "#7c2d12", to: "#fbbf24", icon: "Crosshair" },
    coverImage: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2073850/61f55ef49a74c76bf9fda9ec35bc3101eeee2b3e/header.jpg",
    screenshots: ["https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2073850/320437621741c7be66de4b42d7633b9b0a60fd49/ss_320437621741c7be66de4b42d7633b9b0a60fd49.1920x1080.jpg"],
    systemRequirements: {
      min: "Windows 10 64-bit, Intel Core i5-6600K or AMD Ryzen 5 1600, 12 GB RAM, GeForce GTX 1050 Ti / Radeon RX 580, DirectX 12, 85 GB storage.",
      recommended: "Windows 10 64-bit, Intel Core i5-9600K or AMD Ryzen 5 3600, 16 GB RAM, GeForce RTX 2070 / Radeon RX 5700 XT, DirectX 12, 85 GB storage.",
    },
    launcherInstall: {
      enabled: true,
      kind: "external",
      url: "https://store.steampowered.com/app/2073850/",
      note: "Free to play on Steam — Steam handles the download and install.",
    },
    status: "draft",
    published: false,
    managedBy: "admin",
  },
];

/** No verified mods for this wave — every title here is a live-service game with no mod support to speak of. */
const MODS: Record<string, unknown>[] = [];

async function main() {
  const apply = process.argv.includes("--apply");

  if (!process.env.MONGODB_URI) {
    console.warn("add:games-wave-2 skipped — MONGODB_URI is not set.");
    process.exit(0);
  }

  const dbConnect = (await import("../src/lib/db")).default;
  const CatalogGame = (await import("../src/lib/models/CatalogGame")).default;
  const CatalogMod = (await import("../src/lib/models/CatalogMod")).default;
  const Developer = (await import("../src/lib/models/Developer")).default;

  await dbConnect();

  let created = 0;
  const plan: string[] = [];

  for (const dev of DEVELOPERS) {
    const exists = await Developer.findOne({ slug: dev.slug }).lean();
    plan.push(`${exists ? "SKIP (exists)" : "create"} developer  ${dev.slug}`);
    if (!exists && apply) {
      await Developer.create(dev);
      created++;
    }
  }

  for (const game of GAMES) {
    const exists = await CatalogGame.findOne({ slug: game.slug }).lean();
    plan.push(`${exists ? "SKIP (exists)" : "create"} game       ${game.slug} (${game.sizeMB} MB)`);
    if (!exists && apply) {
      await CatalogGame.create(game);
      created++;
    }
  }

  for (const mod of MODS) {
    const slug = String(mod.slug);
    const exists = await CatalogMod.findOne({ slug }).lean();
    plan.push(`${exists ? "SKIP (exists)" : "create"} mod        ${slug}`);
    if (!exists && apply) {
      await CatalogMod.create(mod);
      created++;
    }
  }

  console.log(apply ? "add:games-wave-2 —" : "add:games-wave-2 — DRY RUN (pass --apply to write):");
  for (const line of plan) console.log(`  ${line}`);

  if (apply) {
    console.log(
      created === 0
        ? "  Nothing to do — everything already exists."
        : `\nCreated ${created} record(s). Games are drafts — publish from the admin once reviewed.`
    );
  }

  process.exit(0);
}

main().catch((err) => {
  console.error("add:games-wave-2 failed:", err);

  // The deploy passes --soft-fail so a database blip cannot block a release
  // over a catalog addition. Insert-only, so the next deploy simply retries.
  if (process.argv.includes("--soft-fail")) {
    console.error("add:games-wave-2: continuing anyway (--soft-fail).");
    process.exit(0);
  }
  process.exit(1);
});
