/**
 * Allowlists for `scripts/insert-catalog-wave.ts` (deploy catalog wave).
 * Kept in a separate module so tests can import without connecting to Mongo.
 *
 * Insert lists create rows only when absent.
 * Patch maps $set ONLY the named fields on existing rows — never other games,
 * never other fields, never upsert.
 * Retire lists hide+archive existing editions — never delete, never upsert.
 */

/** Parent games to create only when absent. Draft until a human publishes. */
export const NEW_GAME_SLUGS: readonly string[] = [
  "trackmania",
  "the-spike-cross",
  "populous-the-beginning",
  "earth-2140-trilogy",
  "super-sidekicks",
  "baseball-stars-2",
  "soccer-brawl",
  "x-men-arcade-remake",
  "tmnt-rescue-palooza",
  "relic-hunters-zero-remix",
  "srb2kart",
  "lovers-in-a-dangerous-spacetime",
  "flatout-2",
  "stalker-anomaly",
  "s-t-a-l-k-e-r-clear-sky",
  "pokemon-blaze-online",
  "pokemmo",
  "castlevania-revamped",
  "hawken-hawkening",
  /*
   * 2026-09-22 wave. Quake II is a paid GOG listing, like the other commercial
   * masters in the catalog; the rest are free. All four land as drafts and need
   * hands-on testing before anyone ticks Tested by PlayBound.
   */
  "quake-ii",
  "outrun",
  "hypersomnia",
  "final-fantasy-xi",
];

/** `gameSlug/editionSlug` pairs to create only when absent. */
export const NEW_EDITION_KEYS: readonly string[] = [
  "stalker-anomaly/official",
  "stalker-anomaly/gamma",
  "s-t-a-l-k-e-r-clear-sky/official",
  "s-t-a-l-k-e-r-shadow-of-chernobyl/official",
  "s-t-a-l-k-e-r-shadow-of-chernobyl/lost-alpha",
  "s-t-a-l-k-e-r-shadow-of-chernobyl/true-stalker",
  "populous-the-beginning/official",
  "populous-the-beginning/populous-reincarnated",
  "earth-2140-trilogy/official",
  "earth-2140-trilogy/opene2140",
  "pokemon-blaze-online/official",
  "pokemon-blaze-online/windows-32",
  "pokemmo/official",
  "castlevania-revamped/official",
  "hawken-hawkening/official",
  /*
   * No `final-fantasy-xi/official` row: the parent carries installSteps, so
   * `listedEditionsFromStored` synthesizes the base edition on its own, and
   * writing one by hand is the duplicate-edition mistake. Horizon is a
   * genuinely different client, which is why it gets a row.
   */
  "final-fantasy-xi/horizon",
];

/**
 * Mod slugs to create only when absent. Empty this wave — OpenE2140 ships as
 * an edition of earth-2140-trilogy, not a free OpenRA mod row.
 */
export const NEW_MOD_SLUGS: readonly string[] = [];

/**
 * Existing catalog games: $set ONLY these fields.
 */
export const PATCH_GAME_FIELDS: Readonly<Record<string, readonly string[]>> = {
  /*
   * releaseYear audit, 2026-09-22.
   *
   * Sixteen published games claimed a 2026 release. The stored year was the
   * year the game was added to PlayBound, not the year it shipped — the
   * "added" dates line up exactly. Thief Gold did not come out in 2026.
   *
   * The first eight take their value from games.ts, which already held the
   * correct year; only the live row was wrong. red-eclipse, openclonk and
   * renegade-x have no seed row and are sourced from catalogCorrections.ts,
   * each with a citation. teeworlds, space-station-14 and
   * pokemon-blaze-online already had patch entries and are merged below.
   * next-gen-chess, opents and strikers-club are genuinely 2026.
   */
  "thief-gold": ["releaseYear", "features"],
  mrboom: ["releaseYear"],
  "rollercoaster-tycoon": ["releaseYear", "features"],
  "thief-2-the-metal-age": ["releaseYear", "features"],
  "stronghold-crusader-hd": ["releaseYear", "features"],
  triplea: ["releaseYear", "features"],
  "star-wars-knights-of-the-old-republic": ["releaseYear"],
  "star-wars-knights-of-the-old-republic-ii-the-sith-lords": ["releaseYear"],
  // Stored 2019 was the 2.0 "Elara" release, not the original.
  "red-eclipse": ["releaseYear"],
  openclonk: ["releaseYear"],
  "renegade-x": ["releaseYear"],

  // Gaps found in the same audit: the only published game with no genres,
  // and the only one with no thatOneThing.
  "c-dogs-sdl": ["genres"],
  "next-gen-chess": ["thatOneThing"],

  "alien-swarm": [
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "faq",
    "installSteps",
    "systemRequirements",
    "hardwareRequirements",
  ],
  freetrain: [
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "faq",
    "installSteps",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
  ],
  "hurry-curry": ["platforms", "features", "launcherInstall"],
  "idle-slayer": [
    "platforms",
    "androidStoreUrl",
    "iosStoreUrl",
    "launchMethods",
    "steamDeck",
    "steamAppId",
    "browserPlayable",
    "launcherInstall",
    "website",
  ],
  "seven-kingdoms-ancient-adversaries": ["launcherInstall"],
  "s-t-a-l-k-e-r-shadow-of-chernobyl": [
    "description",
    "aliases",
    "installSteps",
    "faq",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
  ],
  "stalker-anomaly": [
    "description",
    "aliases",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "faq",
    "installSteps",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
  ],
  "s-t-a-l-k-e-r-clear-sky": [
    "description",
    "aliases",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "faq",
    "installSteps",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
  ],
  "sky-children-of-the-light": [
    "platforms",
    "androidStoreUrl",
    "iosStoreUrl",
    "launchMethods",
    "steamDeck",
    "steamAppId",
    "browserPlayable",
    "launcherInstall",
    "website",
    "installSteps",
  ],
  "slapshot-rebound": [
    "features",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
  ],
  "space-station-14": ["launcherInstall", "installSteps", "releaseYear"],
  teeworlds: [
    "platforms",
    "features",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
    "releaseYear",
  ],
  "super-nova-strike": [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "developerName",
    "genres",
    "tags",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "androidStoreUrl",
    "iosStoreUrl",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
    "art",
    "coverImage",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
  "the-dark-mod": [
    "platforms",
    "features",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
  ],
  "the-spike-cross": [
    "platforms",
    "androidStoreUrl",
    "iosStoreUrl",
    "features",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
    "installSteps",
  ],
  "unknown-horizons": [
    "platforms",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
  ],
  "x-men-arcade-remake": ["launcherInstall", "firstPlaySteps", "multiplayerGamingSteps"],
  "tmnt-rescue-palooza": [
    "title",
    "aliases",
    "status",
    "maxPlayers",
    "launcherInstall",
    "firstPlaySteps",
    "multiplayerGamingSteps",
  ],
  morrowind: ["launcherInstall"],
  "dune-legacy": ["launcherInstall", "features"],
  "pokemon-blaze-online": [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "genres",
    "tags",
    "aliases",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "maxPlayers",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "art",
    "coverImage",
    "screenshots",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
    "multiplayerGamingSteps",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
  "relic-hunters-zero-remix": [
    "launcherInstall",
    "longDescription",
    "whyWePickedIt",
    "installSteps",
  ],
  pokemmo: [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "genres",
    "tags",
    "aliases",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "maxPlayers",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "art",
    "coverImage",
    "screenshots",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
    "multiplayerGamingSteps",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
  "castlevania-revamped": [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "genres",
    "tags",
    "aliases",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "githubRepo",
    "art",
    "coverImage",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
  "hawken-hawkening": [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "genres",
    "tags",
    "aliases",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "maxPlayers",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "art",
    "coverImage",
    "screenshots",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
    "multiplayerGamingSteps",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],

  /*
   * PlayBound Controls wave-1, 2026-09-23. Tags each game whose keyboard
   * controls PlayBound now translates for a controller — see
   * platform/scripts/control-profiles/wave-1.ts and
   * launcher/services/inputEngine/profiles/outrun.json for the actual
   * profiles. Also corrects "Controller Support" on shattered-pixel-dungeon
   * and dungeon-keeper-gold, which had no native controller support despite
   * carrying that tag — their own "controller" scheme in games.ts already
   * says `supported: false`, so the tag was simply wrong, not a judgment
   * call this wave is overriding.
   */
  "openttd": ["features"],
  "shattered-pixel-dungeon": ["features", "launcherInstall"],
  "lincity-ng": ["features"],
  "heroes-of-might-and-magic-3-complete": ["features"],
  "dungeon-keeper-gold": ["features"],
  outrun: ["features"],

  /*
   * PlayBound Controls wave-2, 2026-09-23 — see
   * platform/scripts/control-profiles/wave-2.ts. Also corrects
   * "Controller Support" on wolfenstein-enemy-territory, same reasoning as
   * the wave-1 correction above.
   */
  "old-school-runescape": ["features"],
  "wolfenstein-enemy-territory": ["features"],
  openciv3: ["features"],
  "tes-arena": ["features"],
  "star-wars-galaxies": ["features"],
  freeciv: ["features"],
  "warzone-2100": ["features"],
  "0ad": ["features"],
  "battle-for-wesnoth": ["features"],
  openra: ["features"],
  bzflag: ["features"],
};

/** Existing editions: $set ONLY these fields. */
export const PATCH_EDITION_FIELDS: Readonly<Record<string, readonly string[]>> = {
  // The Windows ZIP includes app/shatteredNews-*.jar (no Main-Class) beside
  // its real root launcher; the old broad hint picked that dependency.
  "shattered-pixel-dungeon/official": ["installConfig"],
  "stalker-anomaly/official": [
    "name",
    "description",
    "shortDescription",
    "aliases",
    "requirements",
    "hardwareRequirements",
    "installConfig",
  ],
  "stalker-anomaly/gamma": [
    "name",
    "description",
    "shortDescription",
    "aliases",
    "links",
    "installMethod",
    "installConfig",
    "requirements",
    "hardwareRequirements",
  ],
  // OpenMW 0.51 ships Windows-x64.exe; live recipe still pointed at win64.zip.
  "morrowind/openmw": ["installConfig"],
  // Keep TES3MP desktop zip pattern in sync (VR-latest miss).
  "morrowind/tes3mp": ["installConfig"],
  // Lost Alpha / True Stalker: Standalone labeling (+ Lost Alpha XR_3DA launch).
  "s-t-a-l-k-e-r-shadow-of-chernobyl/lost-alpha": [
    "name",
    "description",
    "shortDescription",
    "aliases",
    "requirements",
    "hardwareRequirements",
    "installMethod",
    "installConfig",
  ],
  "s-t-a-l-k-e-r-shadow-of-chernobyl/true-stalker": [
    "name",
    "description",
    "shortDescription",
    "aliases",
    "requirements",
    "hardwareRequirements",
    "installConfig",
  ],
  "s-t-a-l-k-e-r-shadow-of-chernobyl/official": [
    "name",
    "description",
    "shortDescription",
  ],
  "s-t-a-l-k-e-r-clear-sky/official": [
    "name",
    "description",
    "shortDescription",
  ],
  // Dune Legacy: SourceForge 0.99.4 path 404s; use 0.98.0aplpha/0.99.5 with PAKs.
  "dune-legacy/modern-engine": ["installConfig"],
  "dune-legacy/playbound-edition": ["installConfig"],
  "pokemon-blaze-online/official": ["features", "tags", "installConfig"],
  "pokemon-blaze-online/windows-32": ["features", "tags", "installConfig"],
  "pokemmo/official": ["features", "tags", "installConfig"],
  "castlevania-revamped/official": ["features", "tags", "installConfig"],
  "hawken-hawkening/official": ["features", "tags", "installConfig"],
};

/**
 * Existing editions to retire (hide from public listings). $set only
 * visibility + status — never delete, never upsert.
 * CoP/anomaly → game stalker-anomaly; CoP/gamma → stalker-anomaly/gamma (new insert).
 */
export const RETIRE_EDITION_KEYS: readonly string[] = [
  "super-sidekicks/official",
  "baseball-stars-2/official",
  "soccer-brawl/official",
];

/**
 * Existing catalog mods: $set ONLY these fields. No upsert.
 * holocure-rich-presence stays draft so seed cannot resurrect a public page.
 */
export const PATCH_MOD_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "holocure-rich-presence": ["status", "published", "developerSlug", "developerName"],

  /*
   * Mod attribution audit, 2026-09-22.
   *
   * 210 of 473 mods were credited to `indie-web`, which is a placeholder
   * rather than an author, and three pointed at a `community` slug absent
   * from the registry, so they rendered with no credit at all. Values come
   * from modAttributions.ts, each read off the upstream host — GitHub repo
   * owner, the BaNaNaS package API, or the author segment of a Luanti /
   * Codeberg / GitLab URL.
   *
   * Nineteen mods are deliberately not listed: ten on mod.io, eight on ModDB
   * and one on SourceForge could not be verified, so they keep `indie-web`.
   */
  "0ad-aristeia": ["developerSlug", "developerName"],
  "0ad-community-maps-2": ["developerSlug", "developerName"],
  "0ad-deathmatch": ["developerSlug", "developerName"],
  "0ad-han-china": ["developerSlug", "developerName"],
  "0ad-millennium-ad": ["developerSlug", "developerName"],
  "0ad-no-blood": ["developerSlug", "developerName"],
  "0ad-ponies": ["developerSlug", "developerName"],
  "0ad-pre-colonial": ["developerSlug", "developerName"],
  "0ad-terra-magna": ["developerSlug", "developerName"],
  "0ad-xiii-century": ["developerSlug", "developerName"],
  "0ad-yayoi-japan": ["developerSlug", "developerName"],
  "diablo-2-filter": ["developerSlug", "developerName"],
  "endless-sky-all-content": ["developerSlug", "developerName"],
  "endless-sky-arc-over": ["developerSlug", "developerName"],
  "endless-sky-asteroid-expansion": ["developerSlug", "developerName"],
  "endless-sky-beccas": ["developerSlug", "developerName"],
  "endless-sky-better-pirates": ["developerSlug", "developerName"],
  "endless-sky-blended-ships": ["developerSlug", "developerName"],
  "endless-sky-ciu-kreo": ["developerSlug", "developerName"],
  "endless-sky-endgame-alpha": ["developerSlug", "developerName"],
  "endless-sky-galactic-war": ["developerSlug", "developerName"],
  "endless-sky-high-dpi": ["developerSlug", "developerName"],
  "endless-sky-kgs": ["developerSlug", "developerName"],
  "endless-sky-logbook-help": ["developerSlug", "developerName"],
  "endless-sky-lost-in-midnight": ["developerSlug", "developerName"],
  "endless-sky-main-plot-plus": ["developerSlug", "developerName"],
  "endless-sky-midnight-expansion": ["developerSlug", "developerName"],
  "endless-sky-omnis": ["developerSlug", "developerName"],
  "endless-sky-prism": ["developerSlug", "developerName"],
  "endless-sky-sheragi": ["developerSlug", "developerName"],
  "endless-sky-spacecrate": ["developerSlug", "developerName"],
  "endless-sky-taskship": ["developerSlug", "developerName"],
  "endless-sky-world-forge": ["developerSlug", "developerName"],
  "flightgear-addon-aerotow-everywhere": ["developerSlug", "developerName"],
  "flightgear-addon-anothergui": ["developerSlug", "developerName"],
  "flightgear-addon-blacklist": ["developerSlug", "developerName"],
  "flightgear-addon-bombable": ["developerSlug", "developerName"],
  "flightgear-addon-cargo-towing": ["developerSlug", "developerName"],
  "flightgear-addon-fgcamera": ["developerSlug", "developerName"],
  "flightgear-addon-ground-services": ["developerSlug", "developerName"],
  "flightgear-addon-highairtrader": ["developerSlug", "developerName"],
  "flightgear-addon-hoppie-acars": ["developerSlug", "developerName"],
  "flightgear-addon-hud-heli": ["developerSlug", "developerName"],
  "flightgear-addon-kml-exporter": ["developerSlug", "developerName"],
  "flightgear-addon-landing-rate": ["developerSlug", "developerName"],
  "flightgear-addon-linuxtrack": ["developerSlug", "developerName"],
  "flightgear-addon-littlenavmap": ["developerSlug", "developerName"],
  "flightgear-addon-logbook": ["developerSlug", "developerName"],
  "flightgear-addon-menu-aggregator": ["developerSlug", "developerName"],
  "flightgear-addon-nogrounddamage": ["developerSlug", "developerName"],
  "flightgear-addon-ramp-marshall": ["developerSlug", "developerName"],
  "flightgear-addon-rcview": ["developerSlug", "developerName"],
  "flightgear-addon-simbrief": ["developerSlug", "developerName"],
  "flightgear-addon-vfr-flying-helper": ["developerSlug", "developerName"],
  "flightgear-addon-which-runway": ["developerSlug", "developerName"],
  "flightgear-airbus-a320neo": ["developerSlug", "developerName"],
  "flightgear-boeing-777": ["developerSlug", "developerName"],
  "flightgear-c172p": ["developerSlug", "developerName"],
  "flightgear-cessna-172p-hd": ["developerSlug", "developerName"],
  "flightgear-concorde": ["developerSlug", "developerName"],
  "flightgear-f16-falcon": ["developerSlug", "developerName"],
  "flightgear-san-francisco-hd": ["developerSlug", "developerName"],
  "freeciv-ampliolt": ["developerSlug", "developerName"],
  "freeciv-civ2civ3-earth": ["developerSlug", "developerName"],
  "freedoom-dsda": ["developerSlug", "developerName"],
  "freedoom-gzdoom": ["developerSlug", "developerName"],
  "freedoom-launcher": ["developerSlug", "developerName"],
  "freedoom-obaddon": ["developerSlug", "developerName"],
  "freedoom-project-brutality": ["developerSlug", "developerName"],
  "genshin-combat-sim": ["developerSlug", "developerName"],
  "genshin-gimi-framework": ["developerSlug", "developerName"],
  "genshin-optimizer": ["developerSlug", "developerName"],
  "hearthstone-firestone": ["developerSlug", "developerName"],
  "holocure-character-pack": ["developerSlug", "developerName"],
  "holocure-multiplayer": ["developerSlug", "developerName"],
  "holocure-qol-toolkit": ["developerSlug", "developerName"],
  "holocure-sandbox": ["developerSlug", "developerName"],
  "keeperfx-ancient-keeper": ["developerSlug", "developerName"],
  "keeperfx-creature-quest": ["developerSlug", "developerName"],
  "keeperfx-hd-sprite-overhaul": ["developerSlug", "developerName"],
  "keeperfx-heart-of-gold": ["developerSlug", "developerName"],
  "keeperfx-japanese-campaign": ["developerSlug", "developerName"],
  "luanti-3d-armor": ["developerSlug", "developerName"],
  "luanti-animalia": ["developerSlug", "developerName"],
  "luanti-asuna": ["developerSlug", "developerName"],
  "luanti-backrooms": ["developerSlug", "developerName"],
  "luanti-digtron": ["developerSlug", "developerName"],
  "luanti-draconis": ["developerSlug", "developerName"],
  "luanti-ethereal": ["developerSlug", "developerName"],
  "luanti-everness": ["developerSlug", "developerName"],
  "luanti-exile": ["developerSlug", "developerName"],
  "luanti-farming-redo": ["developerSlug", "developerName"],
  "luanti-i3": ["developerSlug", "developerName"],
  "luanti-mesecons": ["developerSlug", "developerName"],
  "luanti-mineclonia": ["developerSlug", "developerName"],
  "luanti-minetest-game": ["developerSlug", "developerName"],
  "luanti-mobs-animal": ["developerSlug", "developerName"],
  "luanti-mobs-monster": ["developerSlug", "developerName"],
  "luanti-mobs-redo": ["developerSlug", "developerName"],
  "luanti-nodecore": ["developerSlug", "developerName"],
  "luanti-pipeworks": ["developerSlug", "developerName"],
  "luanti-techage": ["developerSlug", "developerName"],
  "luanti-voxelibre": ["developerSlug", "developerName"],
  "luanti-worldedit": ["developerSlug", "developerName"],
  "mindustry-advance-content": ["developerSlug", "developerName"],
  "mindustry-aeyama": ["developerSlug", "developerName"],
  "mindustry-allure": ["developerSlug", "developerName"],
  "mindustry-asthosus": ["developerSlug", "developerName"],
  "mindustry-betamindy": ["developerSlug", "developerName"],
  "mindustry-commandblocks": ["developerSlug", "developerName"],
  "mindustry-cyberio": ["developerSlug", "developerName"],
  "mindustry-exogenesis": ["developerSlug", "developerName"],
  "mindustry-extra-utilities": ["developerSlug", "developerName"],
  "mindustry-informatis": ["developerSlug", "developerName"],
  "mindustry-mechanical-warfare": ["developerSlug", "developerName"],
  "mindustry-mi2-utilities": ["developerSlug", "developerName"],
  "mindustry-new-horizon": ["developerSlug", "developerName"],
  "mindustry-ohno-missiles": ["developerSlug", "developerName"],
  "mindustry-omaloon": ["developerSlug", "developerName"],
  "mindustry-revision": ["developerSlug", "developerName"],
  "mindustry-sapphirium": ["developerSlug", "developerName"],
  "mindustry-saturation-firepower": ["developerSlug", "developerName"],
  "mindustry-scheme-size": ["developerSlug", "developerName"],
  "mindustry-time-control": ["developerSlug", "developerName"],
  "mindustry-tool": ["developerSlug", "developerName"],
  "mindustry-uaw": ["developerSlug", "developerName"],
  "naev-auxiliary-bay": ["developerSlug", "developerName"],
  "naev-big-largeness": ["developerSlug", "developerName"],
  "naev-carrier-buffs": ["developerSlug", "developerName"],
  "naev-crewmates": ["developerSlug", "developerName"],
  "naev-easier-stringguess": ["developerSlug", "developerName"],
  "naev-easy-mapping": ["developerSlug", "developerName"],
  "naev-evo-genome": ["developerSlug", "developerName"],
  "naev-extra-bays": ["developerSlug", "developerName"],
  "naev-fractal-carriers": ["developerSlug", "developerName"],
  "naev-legion-smol": ["developerSlug", "developerName"],
  "naev-multiplayer": ["developerSlug", "developerName"],
  "naev-no-pirates": ["developerSlug", "developerName"],
  "naev-nomad": ["developerSlug", "developerName"],
  "naev-playground": ["developerSlug", "developerName"],
  "naev-sea-of-mayonnaise": ["developerSlug", "developerName"],
  "naev-simple-shaders": ["developerSlug", "developerName"],
  "naev-trans-logo": ["developerSlug", "developerName"],
  "naev-variants": ["developerSlug", "developerName"],
  "naev-void-saints-nova": ["developerSlug", "developerName"],
  "naev-yaev-classic": ["developerSlug", "developerName"],
  "naev-yes-pirates": ["developerSlug", "developerName"],
  "openra-cameo": ["developerSlug", "developerName"],
  "openra-combined-arms": ["developerSlug", "developerName"],
  "openra-fractured-realms": ["developerSlug", "developerName"],
  "openra-generals-alpha": ["developerSlug", "developerName"],
  "openra-opene2140": ["developerSlug", "developerName"],
  "openra-openhv": ["developerSlug", "developerName"],
  "openra-openkrush": ["developerSlug", "developerName"],
  "openra-opensa": ["developerSlug", "developerName"],
  "openra-ra2": ["developerSlug", "developerName"],
  "openra-romanovs-vengeance": ["developerSlug", "developerName"],
  "openra-schwerpunkt": ["developerSlug", "developerName"],
  "openra-shattered-paradise": ["developerSlug", "developerName"],
  "openra-tiberian-dawn-hd": ["developerSlug", "developerName"],
  "openttd-axis": ["developerSlug", "developerName"],
  "openttd-chips-1": ["developerSlug", "developerName"],
  "openttd-chips-2": ["developerSlug", "developerName"],
  "openttd-egrvts-v2": ["developerSlug", "developerName"],
  "openttd-firs-5": ["developerSlug", "developerName"],
  "openttd-heqs": ["developerSlug", "developerName"],
  "openttd-iron-horse-4": ["developerSlug", "developerName"],
  "openttd-iti": ["developerSlug", "developerName"],
  "openttd-multi-aspect-signals": ["developerSlug", "developerName"],
  "openttd-nuts": ["developerSlug", "developerName"],
  "openttd-opengfx-airports": ["developerSlug", "developerName"],
  "openttd-opengfx-landscape": ["developerSlug", "developerName"],
  "openttd-opengfx-stations": ["developerSlug", "developerName"],
  "openttd-opengfx-towns": ["developerSlug", "developerName"],
  "openttd-opengfx-trains": ["developerSlug", "developerName"],
  "openttd-rattroads": ["developerSlug", "developerName"],
  "openttd-road-hog": ["developerSlug", "developerName"],
  "openttd-swedish-rails": ["developerSlug", "developerName"],
  "openttd-timberwolf-rv": ["developerSlug", "developerName"],
  "openttd-timberwolf-stations": ["developerSlug", "developerName"],
  "openttd-timberwolf-tracks": ["developerSlug", "developerName"],
  "openttd-timberwolf-trains": ["developerSlug", "developerName"],
  "starcraft-bw-api": ["developerSlug", "developerName"],
  "starcraft-openbw": ["developerSlug", "developerName"],
  "tes-arena-dosbox": ["developerSlug", "developerName"],
  "wolfenstein-ecwolf-gh": ["developerSlug", "developerName"],
  "wolfenstein-sdl": ["developerSlug", "developerName"],
  "zerok-altair-crossing": ["developerSlug", "developerName"],
  "zerok-comet-catcher-redux": ["developerSlug", "developerName"],
  "zerok-hud-overlay-suite": ["developerSlug", "developerName"],
  "zerok-speed-metal-remastered": ["developerSlug", "developerName"],
  "zerok-tactical-nukes-mutator": ["developerSlug", "developerName"],
  "zerok-tangerine-oasis": ["developerSlug", "developerName"],

  /*
   * Second attribution pass: the hosts that needed a browser (mod.io renders
   * its CREATORS block client-side, ModDB refuses scripted clients) or their
   * own API (SourceForge). Three mods stay unlisted —
   * openra-anthras-horizon and openra-ymca publish no author field at all,
   * and openra-apocalyptic-doom's ModDB page no longer exists.
   */
  "0ad-10ad": ["developerSlug", "developerName"],
  "0ad-bigger-minimap": ["developerSlug", "developerName"],
  "0ad-community-mod": ["developerSlug", "developerName"],
  "0ad-delenda-est": ["developerSlug", "developerName"],
  "0ad-feldmap": ["developerSlug", "developerName"],
  "0ad-localratings": ["developerSlug", "developerName"],
  "0ad-mainland-twilight": ["developerSlug", "developerName"],
  "0ad-moderngui": ["developerSlug", "developerName"],
  "0ad-theban-greeks": ["developerSlug", "developerName"],
  "0ad-tower-defense": ["developerSlug", "developerName"],
  "flightgear-addon-red-griffin-atc": ["developerSlug", "developerName"],
  "freedoom-brutal": ["developerSlug", "developerName"],
  "openra-charred-earth": ["developerSlug", "developerName"],
  "openra-d2k-community": ["developerSlug", "developerName"],
  "openra-tiberian-aurora": ["developerSlug", "developerName"],
  "openra-tiberian-origins": ["developerSlug", "developerName"],
};
