/**
 * Allowlists for `scripts/insert-catalog-wave.ts` (deploy catalog wave).
 * Kept in a separate module so tests can import without connecting to Mongo.
 *
 * Insert lists create rows only when absent.
 * Patch maps $set ONLY the named fields on existing rows — never other games,
 * never other fields, never upsert.
 * Retire lists hide+archive existing editions — never delete, never upsert.
 */

/** Parent games to create only when absent. Draft until a human publishes. */
export const NEW_GAME_SLUGS: readonly string[] = [
  "trackmania",
  "the-spike-cross",
  "populous-the-beginning",
  "earth-2140-trilogy",
  "super-sidekicks",
  "baseball-stars-2",
  "soccer-brawl",
  "x-men-arcade-remake",
  "tmnt-rescue-palooza",
  "relic-hunters-zero-remix",
  "srb2kart",
  "lovers-in-a-dangerous-spacetime",
  "flatout-2",
  "stalker-anomaly",
  "s-t-a-l-k-e-r-clear-sky",
  "pokemon-blaze-online",
  "pokemmo",
  "castlevania-revamped",
  "hawken-hawkening",
];

/** `gameSlug/editionSlug` pairs to create only when absent. */
export const NEW_EDITION_KEYS: readonly string[] = [
  "s-t-a-l-k-e-r-call-of-pripyat/official",
  "stalker-anomaly/official",
  "stalker-anomaly/gamma",
  "s-t-a-l-k-e-r-clear-sky/official",
  "s-t-a-l-k-e-r-shadow-of-chernobyl/official",
  "s-t-a-l-k-e-r-shadow-of-chernobyl/lost-alpha",
  "s-t-a-l-k-e-r-shadow-of-chernobyl/true-stalker",
  "populous-the-beginning/official",
  "populous-the-beginning/populous-reincarnated",
  "earth-2140-trilogy/official",
  "earth-2140-trilogy/opene2140",
  "pokemon-blaze-online/official",
  "pokemon-blaze-online/windows-32",
  "pokemmo/official",
  "castlevania-revamped/official",
  "hawken-hawkening/official",
];

/**
 * Mod slugs to create only when absent. Empty this wave — OpenE2140 ships as
 * an edition of earth-2140-trilogy, not a free OpenRA mod row.
 */
export const NEW_MOD_SLUGS: readonly string[] = [];

/**
 * Existing catalog games: $set ONLY these fields.
 */
export const PATCH_GAME_FIELDS: Readonly<Record<string, readonly string[]>> = {
  /*
   * releaseYear audit, 2026-09-22.
   *
   * Sixteen published games claimed a 2026 release. The stored year was the
   * year the game was added to PlayBound, not the year it shipped — the
   * "added" dates line up exactly. Thief Gold did not come out in 2026.
   *
   * The first eight take their value from games.ts, which already held the
   * correct year; only the live row was wrong. red-eclipse, openclonk and
   * renegade-x have no seed row and are sourced from catalogCorrections.ts,
   * each with a citation. teeworlds, space-station-14 and
   * pokemon-blaze-online already had patch entries and are merged below.
   * next-gen-chess, opents and strikers-club are genuinely 2026.
   */
  "thief-gold": ["releaseYear"],
  mrboom: ["releaseYear"],
  "rollercoaster-tycoon": ["releaseYear"],
  "thief-2-the-metal-age": ["releaseYear"],
  "stronghold-crusader-hd": ["releaseYear"],
  triplea: ["releaseYear"],
  "star-wars-knights-of-the-old-republic": ["releaseYear"],
  "star-wars-knights-of-the-old-republic-ii-the-sith-lords": ["releaseYear"],
  // Stored 2019 was the 2.0 "Elara" release, not the original.
  "red-eclipse": ["releaseYear"],
  openclonk: ["releaseYear"],
  "renegade-x": ["releaseYear"],

  // Gaps found in the same audit: the only published game with no genres,
  // and the only one with no thatOneThing.
  "c-dogs-sdl": ["genres"],
  "next-gen-chess": ["thatOneThing"],

  "alien-swarm": [
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "faq",
    "installSteps",
    "systemRequirements",
    "hardwareRequirements",
  ],
  freetrain: [
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "faq",
    "installSteps",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
  ],
  "hurry-curry": ["platforms", "features", "launcherInstall"],
  "idle-slayer": [
    "platforms",
    "androidStoreUrl",
    "iosStoreUrl",
    "launchMethods",
    "steamDeck",
    "steamAppId",
    "browserPlayable",
    "launcherInstall",
    "website",
  ],
  "seven-kingdoms-ancient-adversaries": ["launcherInstall"],
  "s-t-a-l-k-e-r-call-of-pripyat": [
    "description",
    "aliases",
    "longDescription",
    "whyWePickedIt",
    "installSteps",
    "faq",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
  ],
  "s-t-a-l-k-e-r-shadow-of-chernobyl": [
    "description",
    "aliases",
    "installSteps",
    "faq",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
  ],
  "stalker-anomaly": [
    "description",
    "aliases",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "faq",
    "installSteps",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
  ],
  "s-t-a-l-k-e-r-clear-sky": [
    "description",
    "aliases",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "faq",
    "installSteps",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
  ],
  "sky-children-of-the-light": [
    "platforms",
    "androidStoreUrl",
    "iosStoreUrl",
    "launchMethods",
    "steamDeck",
    "steamAppId",
    "browserPlayable",
    "launcherInstall",
    "website",
    "installSteps",
  ],
  "slapshot-rebound": [
    "features",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
  ],
  "space-station-14": ["launcherInstall", "installSteps", "releaseYear"],
  teeworlds: [
    "platforms",
    "features",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
    "releaseYear",
  ],
  "super-nova-strike": [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "developerName",
    "genres",
    "tags",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "androidStoreUrl",
    "iosStoreUrl",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
    "art",
    "coverImage",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
  "the-dark-mod": [
    "platforms",
    "features",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
  ],
  "the-spike-cross": [
    "platforms",
    "androidStoreUrl",
    "iosStoreUrl",
    "features",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
    "installSteps",
  ],
  "unknown-horizons": [
    "platforms",
    "launcherInstall",
    "systemRequirements",
    "hardwareRequirements",
  ],
  "x-men-arcade-remake": ["launcherInstall", "firstPlaySteps", "multiplayerGamingSteps"],
  "tmnt-rescue-palooza": [
    "title",
    "aliases",
    "status",
    "maxPlayers",
    "launcherInstall",
    "firstPlaySteps",
    "multiplayerGamingSteps",
  ],
  morrowind: ["launcherInstall"],
  "dune-legacy": ["launcherInstall"],
  "pokemon-blaze-online": [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "genres",
    "tags",
    "aliases",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "maxPlayers",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "art",
    "coverImage",
    "screenshots",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
    "multiplayerGamingSteps",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
  "relic-hunters-zero-remix": [
    "launcherInstall",
    "longDescription",
    "whyWePickedIt",
    "installSteps",
  ],
  pokemmo: [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "genres",
    "tags",
    "aliases",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "maxPlayers",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "art",
    "coverImage",
    "screenshots",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
    "multiplayerGamingSteps",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
  "castlevania-revamped": [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "genres",
    "tags",
    "aliases",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "githubRepo",
    "art",
    "coverImage",
    "screenshots",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
  "hawken-hawkening": [
    "title",
    "tagline",
    "description",
    "developerSlug",
    "genres",
    "tags",
    "aliases",
    "license",
    "releaseYear",
    "sizeMB",
    "platforms",
    "features",
    "maxPlayers",
    "launchMethods",
    "browserPlayable",
    "steamDeck",
    "website",
    "art",
    "coverImage",
    "screenshots",
    "systemRequirements",
    "hardwareRequirements",
    "launcherInstall",
    "firstPlaySteps",
    "multiplayerGamingSteps",
    "qualityBar",
    "longDescription",
    "whyWePickedIt",
    "thatOneThing",
    "bestFor",
    "notFor",
    "comparableTo",
    "installSteps",
    "faq",
    "complete",
  ],
};

/** Existing editions: $set ONLY these fields. */
export const PATCH_EDITION_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "s-t-a-l-k-e-r-call-of-pripyat/official": [
    "name",
    "description",
    "shortDescription",
  ],
  "stalker-anomaly/official": [
    "name",
    "description",
    "shortDescription",
    "aliases",
    "requirements",
    "hardwareRequirements",
    "installConfig",
  ],
  "stalker-anomaly/gamma": [
    "name",
    "description",
    "shortDescription",
    "aliases",
    "links",
    "installMethod",
    "installConfig",
    "requirements",
    "hardwareRequirements",
  ],
  // OpenMW 0.51 ships Windows-x64.exe; live recipe still pointed at win64.zip.
  "morrowind/openmw": ["installConfig"],
  // Keep TES3MP desktop zip pattern in sync (VR-latest miss).
  "morrowind/tes3mp": ["installConfig"],
  // Lost Alpha / True Stalker: Standalone labeling (+ Lost Alpha XR_3DA launch).
  "s-t-a-l-k-e-r-shadow-of-chernobyl/lost-alpha": [
    "name",
    "description",
    "shortDescription",
    "aliases",
    "requirements",
    "hardwareRequirements",
    "installMethod",
    "installConfig",
  ],
  "s-t-a-l-k-e-r-shadow-of-chernobyl/true-stalker": [
    "name",
    "description",
    "shortDescription",
    "aliases",
    "requirements",
    "hardwareRequirements",
    "installConfig",
  ],
  "s-t-a-l-k-e-r-shadow-of-chernobyl/official": [
    "name",
    "description",
    "shortDescription",
  ],
  "s-t-a-l-k-e-r-clear-sky/official": [
    "name",
    "description",
    "shortDescription",
  ],
  // Dune Legacy: SourceForge 0.99.4 path 404s; use 0.98.0aplpha/0.99.5 with PAKs.
  "dune-legacy/modern-engine": ["installConfig"],
  "dune-legacy/playbound-edition": ["installConfig"],
  "pokemon-blaze-online/official": ["features", "tags", "installConfig"],
  "pokemon-blaze-online/windows-32": ["features", "tags", "installConfig"],
  "pokemmo/official": ["features", "tags", "installConfig"],
  "castlevania-revamped/official": ["features", "tags", "installConfig"],
  "hawken-hawkening/official": ["features", "tags", "installConfig"],
};

/**
 * Existing editions to retire (hide from public listings). $set only
 * visibility + status — never delete, never upsert.
 * CoP/anomaly → game stalker-anomaly; CoP/gamma → stalker-anomaly/gamma (new insert).
 */
export const RETIRE_EDITION_KEYS: readonly string[] = [
  "super-sidekicks/official",
  "baseball-stars-2/official",
  "soccer-brawl/official",
  "s-t-a-l-k-e-r-call-of-pripyat/gamma",
  "s-t-a-l-k-e-r-call-of-pripyat/gunslinger",
  "s-t-a-l-k-e-r-call-of-pripyat/anomaly",
];

/**
 * Existing catalog mods: $set ONLY these fields. No upsert.
 * holocure-rich-presence stays draft so seed cannot resurrect a public page.
 */
export const PATCH_MOD_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "holocure-rich-presence": ["status", "published"],
};
