/**
 * Upload PlayBound Setup + electron-updater metadata to Vercel Blob.
 *
 * Usage (from platform/):
 *   npx vercel env pull .env.local --environment=production
 *   cd ../launcher && npm run dist
 *   npm run upload:launcher -- ../launcher/dist/PlayBound-Setup-0.1.5.exe
 *
 * Uploads:
 *   - versioned Setup.exe (as named in latest.yml)
 *   - latest.yml + .blockmap (for in-app auto-update)
 *   - stable alias launcher/PlayBound-Launcher-Setup.exe (site download button)
 */
import { readFileSync, existsSync, readdirSync } from "fs";
import { basename, dirname, resolve } from "path";
import { loadEnvConfig } from "@next/env";
import { put } from "@vercel/blob";

loadEnvConfig(process.cwd());

async function uploadBlob(pathname: string, filePath: string, contentType: string) {
  const bytes = readFileSync(filePath);
  console.log(`  ${pathname} (${(bytes.length / 1024 / 1024).toFixed(2)} MB)`);
  const blob = await put(pathname, bytes, {
    access: "public",
    addRandomSuffix: false,
    allowOverwrite: true,
    contentType,
    multipart: bytes.length > 4 * 1024 * 1024,
    token: process.env.BLOB_READ_WRITE_TOKEN,
  });
  return blob.url;
}

async function main() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  if (!token) {
    console.error("BLOB_READ_WRITE_TOKEN is not set. Pull env with: npx vercel env pull");
    process.exit(1);
  }

  const args = process.argv.slice(2);
  const isMac = args.includes("--mac");
  /** Also overwrite production site/auto-update aliases even for unsigned admin-channel builds. */
  const promoteProd = args.includes("--promote-prod");
  const argPath = args.find(a => !a.startsWith("--"));
  const distDir = resolve(process.cwd(), "../launcher/dist");
  let setupPath = argPath ? resolve(argPath) : "";

  if (!setupPath || !existsSync(setupPath)) {
    const regex = isMac ? /^PlayBound-macOS-\d+\.\d+\.\d+\.dmg$/i : /^PlayBound-Setup-\d+\.\d+\.\d+\.exe$/i;
    const candidates = existsSync(distDir)
      ? readdirSync(distDir)
          .filter((f) => regex.test(f))
          .sort((a, b) => {
            const va = a.match(/(\d+)\.(\d+)\.(\d+)/);
            const vb = b.match(/(\d+)\.(\d+)\.(\d+)/);
            if (!va || !vb) return a.localeCompare(b);
            for (let i = 1; i <= 3; i++) {
              const d = Number(va[i]) - Number(vb[i]);
              if (d) return d;
            }
            return 0;
          })
      : [];
    if (candidates.length === 0) {
      console.error(`${isMac ? "DMG" : "Setup.exe"} not found. Build first: cd launcher && npm run dist${isMac ? ":mac" : ""}`);
      process.exit(1);
    }
    setupPath = resolve(distDir, candidates[candidates.length - 1]);
  }

  const setupName = basename(setupPath);
  const dir = dirname(setupPath);

  // If the admin.yml / admin-mac.yml file was generated by electron-builder,
  // we know this is an admin channel (unsigned) build.
  const isAdmin = existsSync(resolve(dir, isMac ? "admin-mac.yml" : "admin.yml"));

  const ymlName = isMac ? (isAdmin ? "admin-mac.yml" : "latest-mac.yml") : (isAdmin ? "admin.yml" : "latest.yml");
  const ymlPath = resolve(dir, ymlName);
  const blockmapPath = resolve(dir, `${setupName}.blockmap`);

  console.log(`Uploading updater package from ${dir}…`);

  const setupUrl = await uploadBlob(
    `launcher/${setupName}`,
    setupPath,
    "application/octet-stream"
  );

  let ymlUrl: string | null = null;
  if (existsSync(ymlPath)) {
    ymlUrl = await uploadBlob(`launcher/${ymlName}`, ymlPath, "text/yaml; charset=utf-8");
  } else {
    console.warn(`  warning: ${ymlName} missing — auto-update checks will fail until present`);
  }

  if (existsSync(blockmapPath)) {
    await uploadBlob(
      `launcher/${basename(blockmapPath)}`,
      blockmapPath,
      "application/octet-stream"
    );
  } else {
    console.warn("  warning: .blockmap missing — delta updates unavailable");
  }

  const aliasName = isMac 
    ? (isAdmin ? "PlayBound-Launcher-Setup-Admin.dmg" : "PlayBound-Launcher-Setup.dmg")
    : (isAdmin ? "PlayBound-Launcher-Setup-Admin.exe" : "PlayBound-Launcher-Setup.exe");
  const aliasUrl = await uploadBlob(
    `launcher/${aliasName}`,
    setupPath,
    "application/octet-stream"
  );

  // Unsigned Mac CI builds land on admin-* ; still promote to the public site download + latest-mac.yml
  // so users aren't stuck on an older production DMG after a successful CI build.
  let prodAliasUrl: string | null = null;
  let prodYmlUrl: string | null = null;
  if (promoteProd && isAdmin) {
    const prodYmlName = isMac ? "latest-mac.yml" : "latest.yml";
    const prodAliasName = isMac ? "PlayBound-Launcher-Setup.dmg" : "PlayBound-Launcher-Setup.exe";
    if (existsSync(ymlPath)) {
      prodYmlUrl = await uploadBlob(`launcher/${prodYmlName}`, ymlPath, "text/yaml; charset=utf-8");
    }
    prodAliasUrl = await uploadBlob(`launcher/${prodAliasName}`, setupPath, "application/octet-stream");
    console.log(`  also promoted admin build → ${prodAliasName} / ${prodYmlName}`);
  }

  const feedBase = (prodAliasUrl || aliasUrl).replace(/\/[^/]+$/, "/");

  console.log("");
  console.log("Uploaded.");
  console.log(`  Versioned: ${setupUrl}`);
  console.log(`  Site alias: ${prodAliasUrl || aliasUrl}`);
  if (isAdmin) console.log(`  Admin alias: ${aliasUrl}`);
  if (ymlUrl) console.log(`  Update feed: ${ymlUrl}`);
  if (prodYmlUrl) console.log(`  Prod update feed: ${prodYmlUrl}`);
  console.log(`  electron-updater url: ${feedBase}`);
  console.log("");
  console.log("Set on Vercel (Production + Preview) if changed:");
  const envVar = isMac ? "NEXT_PUBLIC_LAUNCHER_MAC_DOWNLOAD_URL" : "NEXT_PUBLIC_LAUNCHER_DOWNLOAD_URL";
  console.log(`  ${envVar}=${prodAliasUrl || aliasUrl}`);
}

main().catch((err) => {
  console.error("upload:launcher failed:", err);
  process.exit(1);
});
